### ISSUE TITLE
Setup on Mac OS X 

### ISSUE THREAD

**Issue by mikim** [cmusatyalab/openface#10]
I'm stuck at the following step.

sudo docker build -t openface .

I installed docker from 
https://www.docker.com/toolbox

And I created default VM.

How can I solve this issue? Or above step is only valid for Ubuntu?

**Comment by bamos** [comment]
Hi @mikim - is the docker container not building? Are you getting an error message? Can you run any of Docker's example containers?

**Comment by mikim** [comment]
Dear @bamos 

Error msg is:

Min-Uks-MacBook-Pro:openface-master m$ sudo docker build -t openface .
Password:
Post http:///var/run/docker.sock/v1.20/build?cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&memory=0&memswap=0&rm=1&t=openface&ulimits=null: dial unix /var/run/docker.sock: no such file or directory.
* Are you trying to connect to a TLS-enabled daemon without TLS?
* Is your docker daemon up and running?

And example container seems to working properly.
Min-Uks-MacBook-Pro:~ m$ docker run ubuntu:14.04 /bin/echo 'Hello world'
Unable to find image 'ubuntu:14.04' locally
14.04: Pulling from library/ubuntu

f9a9f253f610: Pull complete 
eeb7cb91b09d: Pull complete 
3c9a9d7cc6a2: Pull complete 
0a17decee413: Pull complete 
Digest: sha256:6a50ef3d008bf0bb9ed280a092c32d8b0a589240238c6bc0820bd502629d5bf4
Status: Downloaded newer image for ubuntu:14.04
Hello world

**Comment by bamos** [comment]
Hi @mikim - thanks for posting this, this issue is easy to overlook and I think it's because you don't have a docker machine running on OSX for the Ubuntu container, see the setup guide on OSX https://docs.docker.com/installation/mac/ as a reference. I think successfully running the following will correct the error.

```
docker-machine create --driver virtualbox default
eval $(docker-machine env default)
```

I've just clarified this in the README, and please re-open this issue if this still doesn't work.

**Comment by mikim** [comment]
FYI,

Without "sudo" in the following step works fine for me.

sudo docker build -t openface .
sudo docker run -t -i -v $PWD:/openface openface /bin/bash

With "sudo" docker produces the following error.

Min-Uks-MacBook-Pro:openface-master m$ sudo docker run -t -i -v $PWD:/openface openface /bin/bash
Password:
Post http:///var/run/docker.sock/v1.20/containers/create: dial unix /var/run/docker.sock: no such file or directory.
* Are you trying to connect to a TLS-enabled daemon without TLS?
* Is your docker daemon up and running?

**Comment by bamos** [comment]
Thanks, I've also noted this in the README. Hope it's working well now.
Let me know if you notice any other inconsistencies in the documentation or code.

**Comment by convolvetolearn** [comment]
Hi,

Even though I have scavenged through blogs, forums and groups on the internet, I am unable to install and import OpenFace into the python shell. My current predicament is as follows :

1. Installed all dependencies including OpenCV, dlib, torch, coreutils, XQuartz, TBB
2. Cloned git repository
3. Made/Compiled the build by creating the build folder in the OpenFace root directory.

I am unable to find the setup.py file in the OpenFace root directory which will place the .egg-info file in site-packages.

I am running OS X 10.12.5 with Python 2.7. I have been stuck, racking my brains for the past couple of days to solve this. Any help in this regard is greatly appreciated. TIA.

Vibhor
