### ISSUE TITLE
Training: Add LFW validation for testing.

### ISSUE THREAD

**Issue by bamos** [cmusatyalab/openface#100]

**Comment by melgor** [comment]
I have some code with LFW testing. But it does not work with "donkeys". Main issue is that with data I have to send the paths to images, which are strings. And sending tensor only works with Long or Float Tensors. 
My code do following stuff:
1. Read images from disk do DataLoader. 
2. Extract features from images, in serial manner.
3. Based on patches to images and file "pairs.txt", computer distance between images.
4. Search best threshold for all images at once (no split to folds)

What do you think about it?

**Comment by bamos** [comment]
Hi @melgor - I was planning on:

1. Freeing the training GPU memory.
2. Calling `batch-represent` on LFW data with the latest model,
  using all GPU memory with only batched forward passes.
3. Calling the Python LFW experiment to output results in the work dir.

The advantage I see of this is that we can leverage a lot of existing code
and won't have to maintain or debug inconsistencies between
two separate LFW implementations.
The disadvantage is that externally calling programs seems hacky.

**Comment by bamos** [comment]
Hi @melgor - I just added my implementation of this to the commit attached to the issue.

**Comment by bamos** [comment]
Note: It doesn't correctly plot the ROC curve, but accuracy is good enough for me now
