### ISSUE TITLE
error in crossmapnormalization

### ISSUE THREAD

**Issue by AkankshaJ** [cmusatyalab/openface#101]
Hi,
I am trying to test my trained model using compare.py. I am getting this error.

torch/install/bin/luajit: ...rch/install/share/lua/5.1**/fbnn/CrossMapNormalization.lua:43: attempt to call field 'CrossMapNormalization_updateOutput' (a nil value)**
stack traceback:
        ...rch/install/share/lua/5.1/fbnn/CrossMapNormalization.lua:43: in function 'updateOutput'
        ...e/akanksha/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
        ...torch/demos/openface-master/openface/openface_server.lua:71: in main chunk
        [C]: in function 'dofile'
        ...ksha/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x00406670

It would be great someone can help resolve the error.

thanks

**Comment by bamos** [comment]
Hi @AkankshaJ - OpenFace doesn't use fbnn.CrossMapNormalization. We instead use https://github.com/torch/nn/blob/master/SpatialCrossMapLRN.lua. However I've faced the same issue when trying out fbnn.CrossMapNormalization and filed this issue with some more information in their issue tracker: https://github.com/facebook/fbnn/issues/10

-Brandon.

**Comment by AkankshaJ** [comment]
Hi Brandon,

If i dont use fbnn, i get the following error


Error getting result from Torch subprocess.

Line read: 

Exception:

could not convert string to float: 

============

stdout: 

============

stderr: /home/akanksha/torch/install/bin/luajit: /home/akanksha/torch/install/share/lua/5.1/torch/File.lua:334: unknown Torch class <nn.CrossMapNormalization>
stack traceback:
        [C]: in function 'error'
        /home/akanksha/torch/install/share/lua/5.1/torch/File.lua:334: in function 'readObject'
        /home/akanksha/torch/install/share/lua/5.1/torch/File.lua:360: in function 'readObject'
        /home/akanksha/torch/install/share/lua/5.1/torch/File.lua:360: in function 'readObject'
        /home/akanksha/torch/install/share/lua/5.1/nn/Module.lua:154: in function 'read'
        /home/akanksha/torch/install/share/lua/5.1/torch/File.lua:342: in function 'readObject'
        /home/akanksha/torch/install/share/lua/5.1/torch/File.lua:391: in function 'load'
        ...torch/demos/openface-master/openface/openface_server.lua:46: in main chunk
        [C]: in function 'dofile'
        ...ksha/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x00406670

Should i rectify it at the training level?? Since it seems that it uses fbnn crossmapnormaliztion during training ?

**Comment by bamos** [comment]
Hi @AkankshaJ - did you train a model with an older version of OpenFace that uses fbnn.crossmapnormalization? If so I recommend updating OpenFace because we don't use it anymore.
