### ISSUE TITLE
Docker env: detach from /usr/bin/env in cmd when launching representation from python interface

### ISSUE THREAD

**Issue by sin-mike** [cmusatyalab/openface#105]
Guys, I have a small but painful issue considering docker container with openface

I managed to find, that, when using face representation function in python interface via Popen and cmd = [...] openface container fails to launch theano due to inconsistent environment. The environment is usually overwritten after linking or specifying env file. So /usr/bin/env becomes useless and even insecure. Even openface demos fail to work.

Local fix: run bare openface container, copy /usr/bin/env output to file and store it on host machine, then pass it to openface container externally.

Best regards,
Mike

**Comment by bamos** [comment]
Hi @sin-mike - can you provide more information to help us reproduce this?

-Brandon.

**Comment by sin-mike** [comment]
Hi, Brandon

I've found a minimalistic example of how to crash env:
```
$ docker run -it bamos/openface:latest /usr/bin/env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=5666db332f56
TERM=xterm
HOME=/root
```

The same comes with the docker-compose
```
openface:
  restart: always
  image: bamos/openface:latest
  command: /usr/bin/env
```

BR,
Mike

**Comment by bamos** [comment]
Hi @sin-mike - thanks for the examples.
However, I don't see understand how they crash env or what
kind of OpenFace change you want to see fixing this.
Can you provide an example of OpenFace crashing because of this?

If you're trying to run some programs directly with `docker run`
you need to use a Bash as a login shell for the correct environment:

```
docker run -p 9000:9000 -p 8000:8000 -t -i bamos/openface /bin/bash -l -c '/root/src/openface/demos/web/start-servers.sh'
```

-Brandon.

**Comment by sin-mike** [comment]
Dear Brandon,

The problem appeared to be in the docker behavior. With /bin/sh shell a user doesn't have an environment for lua and torch, so the representation function fails. When logging with bash everything works:
`docker run -it bamos/openface:latest bash`

I made a quick search on the problem and indeed it's the feature of docker. It runs by default /bin/sh for commands, but openface relies on the environment built with bash. So I could imagine changing default system /bin/sh to bash like in this issue https://github.com/docker/docker/issues/8100, but it would be such a dirty trick to implement.

For a quick solution I would suggest adding a point to your pretty disclaimer in the lua interface for python
```
OpenFace: `openface_server.lua` subprocess has died.

+ Is the Torch command `th` on your PATH? Check with `which th`.
+ If `th` is on your PATH, try running `./util/profile-network.lua`
  to see if Torch can correctly load and run the network.
  If this gives illegal instruction errors, see the section on
  this in our FAQ at http://cmusatyalab.github.io/openface/faq/
+ Ensure running bash shell for proper environment when running docker containers
+ See this GitHub issue if you are running on
  a non-64-bit machine:
  https://github.com/cmusatyalab/openface/issues/42
+ Please post further issues to our mailing list at
  https://groups.google.com/forum/#!forum/cmu-openface

Diagnostic information:

cmd: {}

============

stdout: {}
```

**Comment by bamos** [comment]
Hi @sin-mike - thanks! That sounds reasonable and I've added a note in the error message about this.

-Brandon.
