### ISSUE TITLE
If I want to run the code, the requires number of GPU?

### ISSUE THREAD

**Issue by getengqing** [cmusatyalab/openface#109]
### Context of the issue.
[Provide more detailed introduction to the issue itself and why it is relevant]

### Expected behavior.
[Describe what you would expect to have resulted from this process.]

### Actual behavior.
[Describe what you currently experience from this process, and thereby explain the bug.]

### Steps to reproduce.
[Present a minimal example and steps to produce the issue.]

### OS and hardware information.

+ Operating system: [todo]
+ Torch version: [todo]
+ CPU architecture: [todo]
+ GPU type (if using): [todo]

**Comment by bamos** [comment]
No
