### ISSUE TITLE
Testing on LFW after an epoch fails

### ISSUE THREAD

**Issue by daydreamt** [cmusatyalab/openface#112]
Hello there,
### Context of the issue.

Openface is having trouble when calling the LFW testing code after every epoch.
### Expected behavior.

I would expect it to test on LFW. My aligned folder is in ../data/lfw/aligned.

This folder is generated as per the instructions of http://cmusatyalab.github.io/openface/models-and-accuracies/, but I renamed it to aligned so that test.lua can find it.
### Actual behavior.

Training works OK, but testing uses all RAM and swaps, irregardless of the -testBatchSize parameter.
### Steps to reproduce.

I made a 224 sized dataset [1]. I did the same for LFW as per the instructions and put it to ~/openface/data/lfw/aligned

My training command is th ~/openface/training/main.lua -data <path_to_large_ds> -imgDim 224 -modelDef ~/openface/models/openface/nn2.def.lua

cudnn is set to false, imgDim to 224, peoplePerBatch to 8, imagesPerPerson 11 to fit on the GPU.
### OS and hardware information.
- Operating system: Linux
- Torch version: Lua 5.1, master branch from today
- CPU architecture: x86_64
- GPU type (if using): Tesla K40c

I would be grateful for any assistance or information on how I could solve this.

[1] On a new dataset that I really hope to share after my thesis is complete :-)

**Comment by bamos** [comment]
Hi @daydreamt - I just committed some minor changes to the training code that adds `imgDim` to `batchRepresent`, before it was defaulting to 96 instead of 224. I wouldn't expect this to cause the swapping issue though. Can you try manually running `batch-represent` on your LFW aligned images to see if you still have swapping issues?

-Brandon.

**Comment by daydreamt** [comment]
Hello, thank you for your quick response!

I took a closer look (with print statements),

and the actual line that causes my program to freeze is 
``
local nnModel = model:float():clone():clearState()
``
in train.lua

I will try running batch-represent now!

**Comment by bamos** [comment]
\cc @melgor

**Comment by melgor** [comment]
Hi @daydreamt. Are you sure about that line? This line convert model to float, clone it and then clear all buffers not needed for prediction. I am now testing this code and  everything works fine.
Could you verify which of the commend (float, clone, clearState) cause freeze?

**Comment by bamos** [comment]
The code is also working well and not hanging on my system, but we just added these changes over the past few days in #106. @daydreamt - can you try reverting to b8de89375a14ec26f90c817bfd917b23b23b491d and running the training code again? This way we'll know if #106 is causing the issue or not.

**Comment by daydreamt** [comment]
Hello @melgor,

yes, that is the one.

``
   print("Converting model to float")
   local nnModel = model:float()
   print("Converted to float")
   nnModel = nnModel:clone()
   print("Cloned.")
   nnModel = nnModel:clearState()
   print("Cleared state.")
``
 
I attach my program output.

[output.txt](https://github.com/cmusatyalab/openface/files/181008/output.txt)

@bamos regarding batchRepresent, the trained nn4.small2.v1.t7 model works fine on 96 dimensional images. Will retrain with the older revision now!

**Comment by daydreamt** [comment]
Retraining on the older revision unfortunately did not fix it. This is a fresh installation of everything, but I think I messed up installing cunn.  The descriptions do not specify it - should luarocks install cunn be sufficient for installing it?

Terribly sorry for the misleading issue name.

**Comment by bamos** [comment]
This is strange, it's hanging converting the model to a float. #106 could have introduced more memory demands on the host, but I think you'll have the same issue on the previous commit I sent you. How much RAM does your system have? I run on a machine with 64GB of RAM and haven't optimized or profiled memory usage and requirements for training.

**Comment by bamos** [comment]
Can you try adding a `collectgarbage()` call immediately before the float conversion?

**Comment by daydreamt** [comment]
This machine has 16GB, and I successfully trained the same model with openface in the past. Then something  changed (I think the inception layer - 
In 24 module of nn.Sequential:
~/torch/install/share/lua/5.1/nn/THNN.lua:109: bad argument #2 to 'v' (input image smaller than kernel size at ~/torch/nn/lib/THNN/generic/SpatialAveragePooling.c:68)
 and I had to reinstall everything.

**Comment by bamos** [comment]
If you can find a commit with training code that works, can you try using `git bisect` to find where the issue was introduced?

**Comment by daydreamt** [comment]
Sure, I will try a fresh installation and older commits. Do you usually install cunn through luarocks?

**Comment by bamos** [comment]
Thanks @daydreamt - I'm hope you find a version that works. And yes, I install cunn and cutorch with luarocks.

**Comment by daydreamt** [comment]
Thank you @bamos, it seems more memory is needed than before. On a 32GB machine the testing progresses farther.

Actually, I never got the testing on LFW to work, and I had always disabled it. This might be a good opportunity to report it.

It seems that  part of the LFW path (the "..") gets lost, and I am not sure how to fix it. I would thankful for any ideas.

/home/username/openface/training/work/010/model_1.t7
/home/username/openface/training/work/010/lfw-1
{
  data : "../data/lfw/aligned"
  imgDim : 224
  cache : false
  model : "/home/username/openface/training/work/010/model_1.t7"
  outDir : "/home/username/openface/training/work/010/lfw-1"
  cuda : true
  batchSize : 800
}
../data/lfw/aligned
cache lotation:         /home/username/openface/data/lfw/aligned/cache.t7
Loading metadata from cache.
If your dataset has changed, delete the cache file.
nImgs:  13233
Index start, end: 1 800
The imgpath is data/lfw/dlib-affine-sz:224/Dalia_Rabin-Pelosoff/Dalia_Rabin-Pelosoff_0001.jpg
/home/username/torch/install/bin/luajit: ...e/username/torch/install/share/lua/5.1/image/init.lua:346: data/lfw/dlib-affine-sz:224/Dalia_Rabin-Pelosoff/Dalia_Rabin-Pelosoff_0001.j$g: No such file or directory
stack traceback:
        [C]: in function 'error'
        ...e/username/torch/install/share/lua/5.1/image/init.lua:346: in function 'load'
        /home/username/openface/batch-represent/dataset.lua:329: in function 'sampleHookTest'
        /home/username/openface/batch-represent/dataset.lua:388: in function 'get'
        ...username/openface/batch-represent/batch-represent.lua:41: in function 'batchRepresent'
        ../batch-represent/main.lua:42: in main chunk
        [C]: in function 'dofile'
        ...akis/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x00406670


And this happens when I specify the lfwDir absolutely:

{
  data : "/home/username/openface/data/lfw/aligned"
  imgDim : 224
  cache : false
  model : "/home/username/openface/training/work/011/model_1.t7"
  outDir : "/home/username/openface/training/work/011/lfw-1"
  cuda : true
  batchSize : 800
}
/home/username/openface/data/lfw/aligned
cache lotation:         /home/username/openface/data/lfw/aligned/cache.t7
Loading metadata from cache.
If your dataset has changed, delete the cache file.
nImgs:  13233
Index start, end: 1 800
The imgpath is data/lfw/dlib-affine-sz:224/Dalia_Rabin-Pelosoff/Dalia_Rabin-Pelosoff_0001.jpg
/home/username/torch/install/bin/luajit: ...e/username/torch/install/share/lua/5.1/image/init.lua:346: data/lfw/dlib-affine-sz:224/Dalia_Rabin-Pelosoff/Dalia_Rabin-Pelosoff_0001.jpg: No such file or directory
stack traceback:
        [C]: in function 'error'
        ...e/username/torch/install/share/lua/5.1/image/init.lua:346: in function 'load'
        /home/username/openface/batch-represent/dataset.lua:329: in function 'sampleHookTest'
        /home/username/openface/batch-represent/dataset.lua:388: in function 'get'
        ...username/openface/batch-represent/batch-represent.lua:41: in function 'batchRepresent'
        ../batch-represent/main.lua:42: in main chunk
        [C]: in function 'dofile'
        ...akis/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x00406670

Thank you for your trouble.

**Comment by bamos** [comment]
Hi @daydreamt - I'm not sure what's causing that. Let me know if you find a fix on your system.

**Comment by jaharkes** [comment]
Could those incorrect data paths be stored in the cache.t7 file?

**Comment by albualexandru** [comment]
@daydreamt are you still active on this project?
