### ISSUE TITLE
when dose provide the cpp or c interface for the library?

### ISSUE THREAD

**Issue by berli** [cmusatyalab/openface#114]
### Context of the issue.
[Provide more detailed introduction to the issue itself and why it is relevant]

### Expected behavior.
[Describe what you would expect to have resulted from this process.]

### Actual behavior.
[Describe what you currently experience from this process, and thereby explain the bug.]

### Steps to reproduce.
[Present a minimal example and steps to produce the issue.]

### OS and hardware information.

+ Operating system: [todo]
+ Torch version: [todo]
+ CPU architecture: [todo]
+ GPU type (if using): [todo]

**Comment by bamos** [comment]
Hi @berli - we don't have a C++ or C interface and we don't have plans to create one.

-Brandon.
