### ISSUE TITLE
Maybe unnecessary extra dataset load?

### ISSUE THREAD

**Issue by myme5261314** [cmusatyalab/openface#117]
### Context of the issue.

I'm reading the source code of openface now. Even though I haven't gone through all the codes once, I came across some weird code that I couldn't understand. So I came here to ask somebody who can explain it.

The main problem is about `multiple thread data loader`.

``` lua
-- data.lua
      donkeys = Threads(
         opt.nDonkeys,
         function()
            require 'torch'
         end,
         function(idx)
            opt = options -- pass to all donkeys via upvalue
            tid = idx
            local seed = opt.manualSeed + idx
            torch.manualSeed(seed)
            print(string.format('Starting donkey with id: %d seed: %d', tid, seed))
            paths.dofile('donkey.lua')  # the problem.
         end
      );
```

``` lua
-- donkey.lua
paths.dofile('dataset.lua') # the problem.
```

I have gone through all the code in `dataset.lua` and find its code as a complete sequential "file list generator".

So when it cooperates with the above snippet of `data.lua`, the sequential "generator" was executed multiple times in seperate threads, resulting multiple `dataset` object.

**Is it waste of time to do unnecessary extra work of loading files? I mean the "file path list" related stuff need only handled once enough.**
### Expected behavior.

I think we don't need to generate multiple different copies of the "file list" right? Am I taking the procedure wrong? I'm a newbie to lua, and not familiar with torch. Maybe I'm wrong with what's going on under the code.
### Actual behavior.

Here's the actual output of the `main.lua`.

``` shell
Starting donkey with id: 2 seed: 4
Starting donkey with id: 1 seed: 3
Creating train metadata
dataset init once!!!!
table: 0x405dc8a0
Creating train metadata
dataset init once!!!!
table: 0x416617e0
running "find" on each class directory, and concatenate all those filenames into a single file containing all image paths for a given class
running "find" on each class directory, and concatenate all those filenames into a single file containing all image paths for a given class
now combine all the files to a single large file
now combine all the files to a single large file
load the large concatenated list of sample paths to self.imagePath
load the large concatenated list of sample paths to self.imagePath
510487 samples found.===================== 510000/510487 =============================>.]  ETA: 0ms | Step: 0ms         
Updating classList and imageClass appropriately
510487 samples found.===================== 510000/510487 =============================>.]  ETA: 0ms | Step: 0ms                
Updating classList and imageClass appropriately
===>........................................... [.=.=.=>..........................................................................................] .   ... . ... . ..  .  .... . .   . . ..   [==========================================>>............................................................................................................................] . ... ]            [============================>..................................................=..=..=.] === == === === =  ===== =  =  =    =    =    =   =  =  =...........................]                [======================================== 10938/10938 ================================>]  Tot: 5m6s | Step: 27ms       
Cleaning up temporary files=============== 10935/10938 ===============================>.]  ETA: 81ms | Step: 27ms       
 [======================================== 10938/10938 ================================>]  Tot: 5m6s | Step: 27ms       
Cleaning up temporary files
nClasses:   10938
```
### Steps to reproduce.

Configure the data path in `opts.lua`, comment out all the code below "paths.dofile('data.lua')" of `training/main.lua`
### OS and hardware information.
- Operating system: Ubuntu 14.04.3
- Torch version: HEAD
- CPU architecture: no need
- GPU type (if using): no need

**Comment by ajdroid** [comment]
This is the overhead of threads. Each worker thread needs to have it's own copy of all the variables it needs to run the worker function independently.
