### ISSUE TITLE
Train with washed up CASIA-WebFace

### ISSUE THREAD

**Issue by bamos** [cmusatyalab/openface#119]
https://groups.google.com/forum/#!topic/cmu-openface/Xue_D4_mxDQ

**Comment by charleshu** [comment]
Hi Basos,
Have you finally trained on this cleaned Casia ?
Unfortunately the link on Baidu of the Washed up list is gone.  I am wondering if you can post the list somewhere? or please kindly send me a copy to  charleshutx@gmail.com  ?  I am keen to know how much difference they make.   Thank you very much.
Changbo

**Comment by charleshu** [comment]
Thank you very much, Allen. I am downloading. Very slow, though and often being interrupted .  I thought it was a files list; Appear to be images.
I thought VGG triplet tuning must be on their cleaned dataset.  I tried tuning on VGG raw data,   triplet training error going down but test error on LFW keeps going up after a few epochs. It seems not overfitting since only one additional FC layers added;  The only reason I can think of is that the data too noisy.  VGG paper mentioned training on noisy data even better than cleaned data. I guess they referred to classifier training. 
I also tried triplet selection  beta < |n|-|p| <alpha. (following FaceNet). A little bit help but curves remain the same tendency.
Any comments, please let me know.
Thanks,Changbo 

    On Tuesday, July 19, 2016 2:17 AM, allenxcp <notifications@github.com> wrote:
 

 链接: http://pan.baidu.com/s/1jIqBIcu 密码: eb7h this is the cleaned CASIA-WebFace—

**Comment by DetionDX** [comment]
Hi, Bamos

Thanks for sharing this cleaned dataset. During the training, I have one question: how do you splits the data into training and validating parts?

**Comment by Coderx7** [comment]
@allenxcp :Thanks alot, but how do we download this ? where should I click?!

**Comment by allenxcp** [comment]
baidu cloud disk
链接: http://pan.baidu.com/s/1kVwRn75 密码: 3225





At 2017-02-25 01:36:36, "Seyyed Hossein Hasan Pour" <notifications@github.com> wrote:


@allenxcp :Thanks alot, but how do we download this ? where should I click?!

**Comment by sidgan** [comment]
Is there any working link for the washed CASIA-Webface dataset? All the links mentioned above do not work.

**Comment by Honzys** [comment]
> Is there any working link for the washed CASIA-Webface dataset? All the links mentioned above do not work.

@sidgan 
Hi, i've found this link: https://pan.baidu.com/s/1kUUP0IN#list/path=%2F, It should work :).

**Comment by monktastic** [comment]
Does anyone know of a link that will work for an English speaker? The Baidu links all seem to require me to download the Baidu downloader, which is exclusively in Chinese.

**Comment by beimingmaster** [comment]
Downloading data from this link(https://pan.baidu.com/s/1kUUP0IN#list/path=%2F),  CASIA-maxpy-clean.zip could not decompress correctly, had another link?

**Comment by sidgan** [comment]
See @kihyuks comment on https://github.com/happynear/FaceVerification/issues/30


$ zip -F CASIA-maxpy-clean.zip --out CASIA-maxpy-clean_fix.zip
$ unzip CASIA-maxpy-clean_fix.zip

**Comment by beimingmaster** [comment]
thanks very much!

**Comment by mrwen00** [comment]
thanks very much for solving my problem.

**Comment by Allloginsbusy** [comment]
How many photos  and classes must be in washed casia-web-face? In this  link(https://pan.baidu.com/s/1kUUP0IN#list/path=%2F) in casia-maxpy-clean 494414 photos,but it is number of original casia.

**Comment by tiwarishiv** [comment]
@sidgan  https://pan.baidu.com/s/1kUUP0IN#list/path=%2F,  The Baidu links all seem to require me to download the Baidu downloader, which is exclusively in Chinese. so we have any link that will work for an English speaker? 
The Chrome extension baidudl is not working for me somehow.

**Comment by timho102003** [comment]
@charleshu all the download link here seems dead, can u provide a valid link for Cleaned CASIA Dataset?
Thanks!!!!

**Comment by markyugen** [comment]
Are there ANY valid links for the CASIA dataset anymore, dirty or clean?

**Comment by Yangel-hide** [comment]
I need CASIA dataset's download link, too! 
Thanks!!

**Comment by Yangel-hide** [comment]
@markyugen @timho102003 happynear/AMSoftmax#14

**Comment by sumbara** [comment]
@Yangel-hide That download link seems dead,too... 
I nedd CASIA dataset's downaload link.. Are there valid links for the CASIA? :D

**Comment by markyugen** [comment]
I couldn't get that latest link to work for me either. It kept asking for a code and wouldn't accept the correct answer.

**Comment by timho102003** [comment]
@sumbara @markyugen  You should check if ur country has been block from the website since most of the valid links are from baidu cloud

**Comment by Yangel-hide** [comment]
@sumbara @markyugen 
the link will be invalid after one week，please download it as soon as possible.
happynear/AMSoftmax#18

**Comment by markyugen** [comment]
When I click on download button I get error Sorry, currently only extract files smaller than 4G

**Comment by markyugen** [comment]
The other option is to download some kind of app, but when I do so and click on it after it is installed, nothing happens.

**Comment by Yangel-hide** [comment]
You should install Baidu cloud client first, and use Baidu cloud client download it.
[http://pan.baidu.com/download](url)
I don‘t have google drive link.

**Comment by sumbara** [comment]
Thank you!
I really aprreciate with you!!!! 
-----Original Message-----

**Comment by markyugen** [comment]
http://pan.baidu.com/download link leads to 404 error.

**Comment by Yangel-hide** [comment]
you can copy it to your browser，direct click it can not work, I dont know why

**Comment by markyugen** [comment]
The Baidu cloud app is waiting for me to type something in. What do I type? I don't read Chinese.

**Comment by sumbara** [comment]
@markyugen You must sing up the Baidu. You can use Chrome and translate that site

**Comment by markyugen** [comment]
It won't let me sign up, it says system error try again later!

**Comment by Yangel-hide** [comment]
I have uploaded it to google drive, you can download it now
[https://drive.google.com/open?id=1Of_EVz-yHV7QVWQGihYfvtny9Ne8qXVz](url)

**Comment by Yangel-hide** [comment]
I have uploaded it to google drive, you can download it now

https://drive.google.com/open?id=1Of_EVz-yHV7QVWQGihYfvtny9Ne8qXVz

**Comment by markyugen** [comment]
That seems to be working Thank you for all your assistance! I really appreciate it!

**Comment by cllyldz** [comment]
When I run the command src/align/align_dataset_mtcnn.py , I get this error "No such file or directory: '/home/pi/datasets/casia/CASIA-maxpy-clean/'". How can I figure out this problem?

**Comment by cliffworkman** [comment]
sudo mkdir /home/pi/datasets/casia/CASIA-maxpy-clean/

**Comment by CharlesNord** [comment]
> I have uploaded it to google drive, you can download it now
> 
> https://drive.google.com/open?id=1Of_EVz-yHV7QVWQGihYfvtny9Ne8qXVz

I think this is the original database, not the washed up one

**Comment by cliffworkman** [comment]
thanks for this! I managed to track down a copy of the cleaned database in some dark corner of the web -- any future visitors to this page should feel free to contact me should they need a copy of this. thanks again, charles,

**Comment by mauxam** [comment]
Thank you so much!!!

**Comment by zylo117** [comment]
> I have uploaded the washed dataset to OneDrive:
> https://1drv.ms/u/s!AjMP8wpvXdkfhMhnbzw1noJ6QkTg5A
> Change 1drv.ms to 1drv.ws if you can't access this link.
> (I downloaded it from the baidu link in the first comment.)

Great Thanks! Life Saver!

**Comment by kevinisbest** [comment]
@chenmingjiongjiong 
Thanks!!!

**Comment by alkoba** [comment]
@chenmingjiongjiong
The link is dead. Please, can you upload it again?

**Comment by alkoba** [comment]
> I have uploaded the washed dataset to OneDrive:
> https://1drv.ms/u/s!AjMP8wpvXdkfhMhnbzw1noJ6QkTg5A
> Change 1drv.ms to 1drv.ws if you can't access this link.
> (I downloaded it from the baidu link in the first comment.)

The link is dead. Please, can you upload it again? Thanks

**Comment by chenmingjiongjiong** [comment]
> 
> 
> > I have uploaded the washed dataset to OneDrive:
> > https://1drv.ms/u/s!AjMP8wpvXdkfhMhnbzw1noJ6QkTg5A
> > Change 1drv.ms to 1drv.ws if you can't access this link.
> > (I downloaded it from the baidu link in the first comment.)
> 
> The link is dead. Please, can you upload it again? Thanks

OK. I have modified the link.

**Comment by Coderx7** [comment]
@chenmingjiongjiong  The links dead it seems . could you kindly reupload?

**Comment by chenmingjiongjiong** [comment]
> @chenmingjiongjiong The links dead it seems . could you kindly reupload?

I can open it. Maybe you clicked the wrong link.
https://1drv.ms/u/s!AjMP8wpvXdkfhMhnmNDEdj5oor7M_A

**Comment by Coderx7** [comment]
@chenmingjiongjiong  Thanks a lot man. yeah it seems I clicked the wrong link. this very link worked just fine :)

**Comment by wencoast** [comment]
> 链接: http://pan.baidu.com/s/1jIqBIcu 密码: eb7h this is the cleaned CASIA-WebFace

This link is not available anymore.

**Comment by sureatgithub** [comment]
> I have uploaded the washed dataset to OneDrive:
> [https://1drv.ms/u/s!AjMP8wpvXdkfhMhnmNDEdj5oor7M_A]https://1drv.ms/u/s!AjMP8wpvXdkfhMhnmNDEdj5oor7M_A)
> Change 1drv.ms to 1drv.ws if you can't access this link.
> (I downloaded it from the baidu link in the first comment.)

The year 2020, this onedrive link works for me!

**Comment by markyugen** [comment]
THANKS, WORKS!

**Comment by bjzhb666** [comment]
Thanks for your sharing. I am new to casia-webface dataset. I wonder our casia-maxpy-clean dataset. I wonder is our dataset independent of lfw dataset? Thanks!
