### ISSUE TITLE
Package manager listings

### ISSUE THREAD

**Issue by semeion** [cmusatyalab/openface#12]
Could be nice an Arch Linux tarball/PKGBUILD to install openface from AUR!

**Comment by bamos** [comment]
I'd love to make this project easily accessible in the AUR! I don't have any experience maintaining AUR packages, so it might be a while before I can get to this, so I've added the `help wanted` tag if anybody wants to help here.

**Comment by semeion** [comment]
Thanks, i will wait for it!

**Comment by bamos** [comment]
Expanding for:

+ [ ] Arch Linux
+ [ ] Ubuntu
+ [ ] homebrew

**Comment by kylesferrazza** [comment]
I made an arch linux package and put it in the AUR
https://aur.archlinux.org/packages/openface-git
