### ISSUE TITLE
run-tests.sh failed in tests.openface_neural_net_training_tests.test_dnn_training

### ISSUE THREAD

**Issue by tornadomeet** [cmusatyalab/openface#120]
Hello,all,
when i download openface and installed all its dependencies,  then i run ```./run-test.sh```, The previous five test is OK, but it failed in the last test:tests.openface_neural_net_training_tests.test_dnn_training, with the error messages:
```
~/openface/training/train.lua:91: attempt to call method 'clearState' (a nil value)
stack traceback:
	~/openface/training/train.lua:91: in function 'train'
	./main.lua:44: in main chunk
	[C]: in function 'dofile'
	...ject/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x004064d0
```
i refer to https://github.com/cmusatyalab/openface/issues/112, and reinstalled torch, but no solved, so how to fix this?thanks~

**Comment by bamos** [comment]
`clearState` is included in the latest Torch release, I'm surprised this isn't working since you reinstalled Torch. Does the following Torch code work on your system?

```lua
require 'nn'
f = nn.Linear(3, 2)
f:clearState()
```

-Brandon.

**Comment by tornadomeet** [comment]
@bamos thanks very much! i just test your code, and i found it output error, so this means i did not installed the newest torch. because i installed the other newest torch model, not the torch itself, so i reinstalled torch again, and it fixed! all passed!

**Comment by bamos** [comment]
Great to hear, glad it's working now!
