### ISSUE TITLE
Help for delete image

### ISSUE THREAD

**Issue by jihademir** [cmusatyalab/openface#124]
How can we delete the saved image and name from the browser

**Comment by bamos** [comment]
Hi @jihademir - the GitHub issue tracker isn't meant for support questions like this. That's why we have the following comment in our issue template:

```
<!-- The GitHub issue tracker is for development discussions and bug tracking.
     Please direct questions to our mailing list at
     https://groups.google.com/forum/#!forum/cmu-openface -->
```

Happy to help you on our mailing list.

-Brandon.
