### ISSUE TITLE
Add simple tests

### ISSUE THREAD

**Issue by bamos** [cmusatyalab/openface#13]
+ [x] Python alignment
+ [x] Torch network
+ [x] Python -> Torch Communication (depends on better solution from #4)
+ [x] Demos on example images
+ [x] DNN training pipeline
+ [x] util scripts

**Comment by Strateus** [comment]
Brandon, why do you have this test in python alignment warped image?:

    if 0 <= l <= w and 0 <= r <= w and 0 <= b <= h and 0 <= t <= h:

There is quite big probability one of the points will be out of this range, dont you think its too strict?

**Comment by bamos** [comment]
Hi @Strateus - since this isn't related to testing, I've filed a new issue to continue this discussion: #39

**Comment by bamos** [comment]
Travis CI now pulls the Docker automated build and runs our unit tests in it after every commit.


Build passing!
https://travis-ci.org/cmusatyalab/openface/builds/98588632

**Comment by bamos** [comment]
Automated tests are working well and passing in the Travis build! Already, they've helped uncover a small bug in `batch-represent`, described [here](https://groups.google.com/forum/#!topic/cmu-openface/NHm0sm23564).
