### ISSUE TITLE
Minimize the size of opencv-dlib-torch docker image

### ISSUE THREAD

**Issue by luinstra** [cmusatyalab/openface#133]
A small enhancement I would suggest for the opencv-dlib-torch.Dockerfile you are using would be to add the following to the end of the opencv build step
```
cd ../.. && \
rm ocv.zip && \
rm -rf opencv-2.4.11
```
and this to the dlib build step
```
cd ~ && \
rm -rf src
```
It reduces the final image size to 1.45 GB from 4.6 GB. I wouldn't expect this to have any adverse effects, and the web demo still seems to work properly.

**Comment by bamos** [comment]
Thanks @luinstra! Good idea, trying it now.

**Comment by bamos** [comment]
The latest Docker container contains these improvements and Travis downloads the container three times as fast! (77 seconds instead of 230 seconds)
