### ISSUE TITLE
Add support for larger datasets to create a classifier.pkl file

### ISSUE THREAD

**Issue by neuraldomi** [cmusatyalab/openface#134]
### Context of the issue.

My current dataset has 7500 persons and 250000 faces. When I try to create the classifier.pkl file with a GPU i am running out of memory after a couple of hours. 

I am very interested in solving this problem. I noticed that with smaller datasets (eg. 500 persons with 10000 faces) the training of the classifier goes fairly quick and without problems. The max. limit of persons currently seems to be around 1000.
### Expected behavior.

There should be no limit of persons/faces in order to create a classifier.pkl file.
### Actual behavior.

The only output I see:

```
Argument parsing and import libraries took 52.7680699825 seconds.
Loading the dlib and OpenFace models took 28.5321800709 seconds.
Loading embeddings.
Training for 7782 classes.
```
### Steps to reproduce.

Try tp create a classifier.pkl with a dataset with 1000+ person and you will run into the problem.
### OS and hardware information.
- Operating system: Linux 64-Bit (Ubuntu 14.04)
- GPU type (if using): g2.2xlarge
### Input from Brandon on how to solve this issue:

I never intended for the classification demo (which doesn't use dataset.lua) to be used at that scale. For better performance you should:

1) add minibatch support to the Python interface
2) add some garbage collection calls to openface_server.lua
3) add cudnn support to openface_server.lua
4) investigate better Python-based classifiers for this scale (potentially neural net-based)

**Comment by fedyunin** [comment]
hi all! 

I look for create classifier from large data.

I found that there are classifiers with incremental learning (http://scikit-learn.org/stable/modules/scaling_strategies.html#incremental-learning).

Question: Does anyone know - will works face recognition with incremental learning classifiers?
May be someone can provide some comments about it.

Thanks!

**Comment by biruwon** [comment]
I'm interested on this too but so far I have found nothing
