### ISSUE TITLE
Training produces strange accuracy

### ISSUE THREAD

**Issue by aaronnech** [cmusatyalab/openface#136]
### Context of the issue.
Attempting to train by following the training instructions. Attempted to train on LFW as well to no avail. Is there any tests I can do to narrow down the issue?

### Expected behavior.
LFW accuracy should go up, or at least change between epoches. Triple error should decrease after about 20 epoches from graphs I've seen here

### Actual behavior.
cat test.log
```
lfwAcc
 5.0000e-01
 5.0000e-01
 5.0000e-01
 5.0000e-01
 5.0000e-01
 5.0000e-01
 5.0000e-01
 5.0000e-01
 5.0000e-01
 5.0000e-01
 5.0000e-01
 5.0000e-01
 5.0000e-01
 5.0000e-01
 5.0000e-01
 5.0000e-01
 5.0000e-01
 5.0000e-01
```

cat train.log
```
avg triplet loss (train set)
 2.0113e-01
 2.0006e-01
 2.0003e-01
 2.0002e-01
 2.0001e-01
 2.0002e-01
 2.0001e-01
 2.0001e-01
 2.0001e-01
 2.0001e-01
 2.0001e-01
 2.0001e-01
 2.0001e-01
 2.0001e-01
 2.0001e-01
 2.0001e-01
 2.0000e-01
 2.0001e-01
```

### Steps to reproduce.
Follow training instructions

### OS and hardware information.

+ Operating system: linux
+ Torch version: latest
+ CPU architecture: x86
+ GPU type (if using): NVIDIA titan

**Comment by bamos** [comment]
I'm not able to reproduce this, I just trained a model from scratch to 91.98% LFW accuracy with the latest master branch (5a7e265). I think training's still working well for @melgor. @cocoakeith is experiencing convergence issues and just filed #138, but that doesn't look as bad as this.

Just to be sure, did you delete the prior data cache files from when you were modifying `dataset.lua`?

**Comment by aaronnech** [comment]
I reinstalled everything yesterday (torch, luarocks, openface) and am running again. Yesterday I was able to get Increasing LFW accuracies yesterday on a very small subset of my dataset (~10k images). I'm hoping the problem is resolved now. I'll report back. If anyone is experiencing the same thing try reinstalling :)

**Comment by cocoakeith** [comment]
Hello @aaronnech When I first train the new DNN, I meet the same thing like you, however I change the value of peoplePerBatch and imagesPerPerson, the LFW accuracy increases. And then I meet the #138 problems. Maybe you can change the value of peoplePerBatch and imagesPerPerson.

**Comment by aaronnech** [comment]
Hi!

Any intuition on why changing those parameters would drastically alter the course of training like that?

**Comment by aaronnech** [comment]
Closing this for now, as it's not a technical bug that's able to be reproduced.
