### ISSUE TITLE
Python requirements conflict

### ISSUE THREAD

**Issue by GreenKing** [cmusatyalab/openface#137]
I noticed that [openface/requirements.txt](https://github.com/cmusatyalab/openface/blob/master/requirements.txt) conflicting with [openface/demos/web/requirements.txt](https://github.com/cmusatyalab/openface/blob/master/demos/web/requirements.txt).

[openface/requirements.txt](https://github.com/cmusatyalab/openface/blob/master/requirements.txt) requires:
```
scikit-learn >= 0.17, < 0.18
```
But [openface/demos/web/requirements.txt](https://github.com/cmusatyalab/openface/blob/master/demos/web/requirements.txt) requires:
```
scikit-learn >= 0.14, < 0.17
```

When you install packages following both requirement, it will cause a `python importing error`, and report a `Segmentation Fault`.

What I have done is deleting following lines in [openface/demos/web/requirements.txt](https://github.com/cmusatyalab/openface/blob/master/demos/web/requirements.txt) to solve this problem.
```
scipy >= 0.13, < 0.17
scikit-learn >= 0.14, < 0.17
```

**Comment by bamos** [comment]
Thanks @GreenKing - I've bumped the scikit-learn dependency in the demo's requirements to the version used in the main requirements.
