### ISSUE TITLE
Converging too slowly while training

### ISSUE THREAD

**Issue by cocoakeith** [cmusatyalab/openface#138]
### Context of the issue.
I'm training a new DNN on a big dataset(~10M images), however the LFW accuracy is only 0.8035 after 333 epoch. Is the convergence too slow ? or is there sth wrong with my parameter setting?@bamos 

### Expected behavior.
[Describe what you would expect to have resulted from this process.]

### Actual behavior.
![roc](https://cloud.githubusercontent.com/assets/12630218/15103627/fbbf2b00-15df-11e6-96d8-2e8833046f3b.png)

main Parameter 
-nEpochs 1000
-epochSize 250
-peoplePerBatch 10
-imagesPerPerson 20
-modelDef nn4.small2.def.lua
-alpha 0.2

### Steps to reproduce.
[Present a minimal example and steps to produce the issue.]

### OS and hardware information.

+ Operating system: [ubuntu]
+ Torch version: [latest]
+ CPU architecture:[x86]
+ GPU type (if using): [Tesla k20C]

**Comment by melgor** [comment]
Hi,
Could you provide the plots/files which show Train Loss and LFW accuracy in epochs? 
And it is strange behavior, as 333 epochs, each 1000*200 examplse give you 66M images. I think that accuracy should we higher.

**Comment by cocoakeith** [comment]
Thank you  @melgor, the plots/files are provided. Is the imagesPerPerson too slow?
[plotfiles.zip](https://github.com/cmusatyalab/openface/files/254511/plotfiles.zip)

**Comment by bamos** [comment]
Hi @cocoakeith, potentially the `nn4.small2` model might not fit well to your data since it's an order of magnitude larger than what I tuned `nn4.small2` for. Can you try retraining with the original `nn4` model?

-Brandon.

**Comment by melgor** [comment]
I think that bamos have right. 
And based on logs, it is making progress, so maybe you should wait longer. 

> Is the imagesPerPerson too small
I do not think so. But you current config use 20*10 images. If you have enough GPU memory, you can try increase imagesPerPerson (to 25 or even more)

**Comment by cocoakeith** [comment]
Hi @bamos @melgor ,I try retraining with the original nn4 model, after one night training(56 epochs), the LFW accuracy has decreased, maybe I should wait longer. Besides, my dataset is noisy, but it's very big, is it necessary to do some data cleaning ?

lfwAcc	
 7.7200e-01	
 7.7250e-01	
 7.7050e-01	
 7.6180e-01	
 7.7180e-01	
 7.5400e-01	
 7.4580e-01	
 7.4450e-01	
 7.3650e-01	
 7.5180e-01	
 7.4930e-01	
 7.4170e-01	
 7.3180e-01	
 7.3320e-01	
 7.4520e-01	
 7.2450e-01	
 7.2800e-01	
 7.2420e-01	
 7.3450e-01	
 7.4750e-01	
 7.2980e-01	
 7.1880e-01	
 7.5070e-01	
 7.3800e-01	
 7.3170e-01	
 7.4770e-01	
 7.0950e-01	
 7.3970e-01	
 7.4120e-01	
 7.2570e-01	
 7.4200e-01	
 7.2630e-01	
 7.3980e-01	
 7.3250e-01	
 7.2420e-01	
 7.4300e-01	
 7.3530e-01	
 7.5220e-01	
 7.4650e-01	
 7.4020e-01	
 7.3480e-01	
 7.4730e-01	
 7.5030e-01	
 7.4330e-01	
 7.4050e-01	
 7.4900e-01	
 7.5230e-01	
 7.0770e-01	
 7.3070e-01	
 7.3750e-01	
 7.5170e-01	
 7.2130e-01	
 7.2080e-01	
 7.3520e-01	
 7.2330e-01	
 7.3170e-01

avg triplet loss (train set)	
 2.1304e-01	
 2.0462e-01	
 2.0219e-01	
 2.0321e-01	
 2.0260e-01	
 2.0206e-01	
 2.0186e-01	
 2.0201e-01	
 2.0157e-01	
 2.0200e-01	
 2.0117e-01	
 2.0161e-01	
 2.0176e-01	
 2.0140e-01	
 2.0180e-01	
 2.0118e-01	
 2.0118e-01	
 2.0128e-01	
 2.0045e-01	
 2.0146e-01	
 2.0138e-01	
 2.0141e-01	
 2.0083e-01	
 2.0108e-01	
 2.0093e-01	
 2.0134e-01	
 1.9996e-01	
 2.0190e-01	
 2.0030e-01	
 2.0112e-01	
 2.0026e-01	
 2.0152e-01	
 2.0157e-01	
 1.9998e-01	
 2.0007e-01	
 2.0129e-01	
 2.0088e-01	
 2.0061e-01	
 2.0090e-01	
 2.0106e-01	
 1.9957e-01	
 2.0089e-01	
 2.0083e-01	
 2.0049e-01	
 2.0124e-01	
 2.0042e-01	
 2.0047e-01	
 2.0062e-01	
 2.0109e-01	
 2.0124e-01	
 2.0071e-01	
 2.0023e-01	
 2.0104e-01	
 2.0026e-01	
 2.0082e-01	
 2.0127e-01

**Comment by bamos** [comment]
Yeah, your data might be too noisy and you might need to clean it. I was just able to re-train a model from scratch to 91.9% LFW accuracy, so I'm going to close this issue since it's not development-related or a bug. Feel free to continue this discussion on our mailing list.

-Brandon.
