### ISSUE TITLE
Can not load celeb-classifier.nn4.small2.v1.pkl with pickle

### ISSUE THREAD

**Issue by apollo-time** [cmusatyalab/openface#145]
### Context of the issue.

I install the torch and openface.
And I download the model celeb-classifier.nn4.small2.v1.pkl from http://openface-models.storage.cmusatyalab.org/celeb-classifier.nn4.small2.v1.pkl using by models/get-model.sh.
And I test the run-test.sh.
I receive the OK status but the only test_classification_demo_pretrained is FAIL because of pickle can not load the model.

tests.openface_api_tests.test_pipeline ... ok
tests.openface_batch_represent_tests.test_batch_represent ... ok
tests.openface_demo_tests.test_compare_demo ... ok
tests.openface_demo_tests.test_classification_demo_pretrained ... FAIL
tests.openface_demo_tests.test_classification_demo_training ... ok
tests.openface_neural_net_training_tests.test_dnn_training ...
ok
# 
## FAIL: tests.openface_demo_tests.test_classification_demo_pretrained

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/ubuntu/openface/tests/openface_demo_tests.py", line 51, in test_classification_demo_pretrained
    assert "Predict SteveCarell with 0.97 confidence." in out
AssertionError:
-------------------- >> begin captured stdout << ---------------------

libdc1394 error: Failed to initialize libdc1394
Traceback (most recent call last):
  File "/home/ubuntu/openface/demos/classifier.py", line 201, in <module>
    infer(args)
  File "/home/ubuntu/openface/demos/classifier.py", line 120, in infer
    (le, clf) = pickle.load(f)
  File "/usr/lib/python2.7/pickle.py", line 1378, in load
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 1090, in load_global
    klass = self.find_class(module, name)
  File "/usr/lib/python2.7/pickle.py", line 1126, in find_class
    klass = getattr(mod, name)
AttributeError: 'module' object has no attribute '_passthrough_scorer'

--------------------- >> end captured stdout << ----------------------

---

Ran 6 tests in 96.334s

FAILED (failures=1)

How can I load the celeb-classifier.nn4.small2.v1.pkl model with pickle?
### Expected behavior.

I think it is because of the pickle version.
### Steps to reproduce.

./run-tests.sh
### OS and hardware information.
- Operating system: Ubuntu 14.04.4 LTS
- Torch version: the last git version
- CPU architecture:AWS tiny2
- GPU type (if using): none

**Comment by bamos** [comment]
Hi, what scikit-learn version are you using? I've listed scikit-learn 0.17 as a dependency in requirements.txt. I think you're getting this error because you're using a scikit-learn version that is incompatible with the one I saved this file with.

-Brandon.

**Comment by apollo-time** [comment]
Thanks for reply.
How can I check the scikit-learn version?

**Comment by bamos** [comment]
How did you install scikit-learn?

**Comment by apollo-time** [comment]
I installed it using by sudo pip install scikit-learn.

**Comment by bamos** [comment]
With pip you can see what package version you installed. Since you didn't explicitly specify sklearn 0.17, I think you got a different version.

**Comment by hayderm** [comment]
Please have you solved this issue ? because I have the same

**Comment by elahia** [comment]
I got the same error, 
my sklearn is version 19, how can i downgrade to 17.1 ?
