### ISSUE TITLE
ArgumentError

### ISSUE THREAD

**Issue by melowYX** [cmusatyalab/openface#148]
@bamos 
$ ./compare.py images/examples/{lennon*,clapton*}
Traceback (most recent call last):
  File "./compare.py", line 58, in <module>
    align = openface.AlignDlib(args.dlibFacePredictor)
  File "/usr/local/lib/python2.7/dist-packages/openface/align_dlib.py", line 91, in __init__
    self.predictor = dlib.shape_predictor(facePredictor)
Boost.Python.ArgumentError: Python argument types in
    shape_predictor.__init__(shape_predictor, str)
did not match C++ signature:
    __init__(boost::python::api::object, std::string)
    __init__(_object*)

**Comment by bamos** [comment]
Hi @melowYX - I think your dlib model is corrupted (check the md5sum from get-models.sh) or that you're using an incompatible dlib version.

-Brandon.

**Comment by melowYX** [comment]
@bamos
I checked the md5sum from get-models.sh and the version of dlib is dlib-18.16. But I used Ubuntu 15.10 in my machine,and the version of gcc was 4.9.Because of using gcc-4.8 to compile the dlib occured error,so I transformed the version.

**Comment by bamos** [comment]
Hi @melowYX - I noticed you deleted your response from last time. Are you still having this issue?

-Brandon.

**Comment by melowYX** [comment]
@bamos  Yes，I didn’t solve this problem.And I'm continue my work with docker. I think the problem is probably  caused by a different version of the Ubuntu.I have installed it many times，checked  the md5sum from get-models.sh and the version of dlib and OpenCv but Ubuntu.So I think Ubuntu15.10  maybe an incompatible version.But now I didn't have time to change it.

**Comment by melowYX** [comment]
@bamos  But I think Docker is a good thing. :）

**Comment by melowYX** [comment]
@bamos  And I think Docker is a good thing. ：）

**Comment by bamos** [comment]
Ok, it could be something in Ubuntu 15.10, I have developed and tested the code in Ubuntu 14. Glad Docker's working well. I'll close this issue for now.
