### ISSUE TITLE
finetune vgg face module, got error

### ISSUE THREAD

**Issue by northeastsquare** [cmusatyalab/openface#150]
### Context of the issue.

I want to reuse vgg face module for torch7, to retrain tripplet,
### Expected behavior.

start training 
### Actual behavior.

 got error:
/home/silva/torch/install/bin/luajit: /home/silva/torch/install/share/lua/5.1/nn/Container.lua:67: 
In 33 module of nn.Sequential:
/home/silva/torch/install/share/lua/5.1/nn/Linear.lua:99: invalid arguments: CudaTensor number CudaTensor CudaTensor 
expected arguments: _CudaTensor~2D_ [CudaTensor~2D] [float] CudaTensor~2D CudaTensor~2D | _CudaTensor~2D_ float [CudaTensor~2D] float CudaTensor~2D CudaTensor~2D
### Steps to reproduce.

[Present a minimal example and steps to produce the issue.]
1. Change module.lua:
if opt.retrain ~= 'none' then
   assert(paths.filep(opt.retrain), 'File not found: ' .. opt.retrain)
   print('Loading model from file: ' .. opt.retrain);
   model = torch.load(opt.retrain)
   model:remove(#model.modules)
   model:remove(#model.modules)
   model:remove(#model.modules)
   model:remove(#model.modules)
   model:remove(#model.modules)
   --model.modules
   lnr = nn.Linear(4096, opt.embSize)
   model:add(lnr)
   model:evaluate()
2 ./main.lua -data ../data/casia-aligned -retrain ../models/openface/VGG_FACE.t7  -imgDim 224
### OS and hardware information.

Ubuntu 14.04 , Titanx
- Operating system: [Ubuntu 14.04]
- Torch version: [latest]
- CPU architecture: [x64]
- GPU type (if using): [Titanx]

**Comment by northeastsquare** [comment]
And after google, I got similar error, but I don't know how to correct.
https://github.com/karpathy/char-rnn/issues/21

**Comment by bamos** [comment]
Hi @northeastsquare - to reduce the model's size, the VGG Torch model doesn't contain gradient buffers used for backpropogation. If you look at the full stack trace of the error you provided, the error is coming from `nn.Linear`:

```
/home/bamos/torch/install/bin/luajit: /home/bamos/torch/install/share/lua/5.1/nn/Container.lua:67:
In 33 module of nn.Sequential:
/home/bamos/torch/install/share/lua/5.1/nn/Linear.lua:99: invalid arguments: CudaTensor number CudaTensor CudaTensor
expected arguments: *CudaTensor~2D* [CudaTensor~2D] [float] CudaTensor~2D CudaTensor~2D | *CudaTensor~2D* float [CudaTensor~2D] float CudaTensor~2D CudaTensor~2D
stack traceback:
        [C]: in function 'addmm'
        /home/bamos/torch/install/share/lua/5.1/nn/Linear.lua:99: in function 'accGradParameters'
        /home/bamos/torch/install/share/lua/5.1/nn/Module.lua:32: in function </home/bamos/torch/install/share/lua/5.1/nn/Module.lua:29>
        [C]: in function 'xpcall'
        /home/bamos/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
        /home/bamos/torch/install/share/lua/5.1/nn/Sequential.lua:84: in function 'backward'
        /home/bamos/openface/training/OpenFaceOptim.lua:135: in function 'optimizeTriplet'
        /home/bamos/openface/training/train.lua:209: in function 'f2'
        /home/bamos/openface/training/data.lua:35: in function 'addjob'
        /home/bamos/openface/training/train.lua:55: in function 'train'
        ./main.lua:49: in main chunk
        [C]: in function 'dofile'
        ...amos/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x00406670
```

I added the following print statements to `nn.Linear` to better understand what's going on here:

```
function Linear:accGradParameters(input, gradOutput, scale)
   scale = scale or 1
   if input:dim() == 1 then
      self.gradWeight:addr(scale, gradOutput, input)
      if self.bias then self.gradBias:add(scale, gradOutput) end
   elseif input:dim() == 2 then
      print(self.gradWeight:size())
      print(scale)
      print(gradOutput:size())
      print(input:size())
      self.gradWeight:addmm(scale, gradOutput:t(), input)
      if self.bias then
         -- update the size of addBuffer if the input is not the same size as the one we\
 had in last updateGradInput
         updateAddBuffer(self, input)
         self.gradBias:addmv(scale, gradOutput:t(), self.addBuffer)
      end
   end
end
```

The output is:

```
===
  128
 4096
[torch.LongStorage of size 2]

1
  56
 128
[torch.LongStorage of size 2]

   56
 4096
[torch.LongStorage of size 2]

===
[torch.LongStorage of size 0]

1
   56
 4096
[torch.LongStorage of size 2]

    56
 25088
[torch.LongStorage of size 2]
```

The first one works correctly because it's of the new linear layer you created. However the next one doesn't because `self.gradWeight` has been deleted from VGG's model, which shows as `size 0` here.

To fix this, you could:

1. Create a new VGG model definition (like our [nn4.small2.def.lua](https://github.com/cmusatyalab/openface/blob/master/models/openface/nn4.small2.def.lua)) to created a new trainable network. Then initialize the weights from VGG's pre-trained model. If you do this, can you send me a PR or post the model definition? I'm interested in training an OpenFace VGG-style network from scratch.
2. Manually restore the gradient weights.

Hope this helps!
-Brandon.

**Comment by bamos** [comment]
By the way, you'll also need to add mean subtraction to OpenFace to be compatible with VGG's pre-trained model.

**Comment by bamos** [comment]
Hi @northeastsquare - I just committed the original and a modified VGG face model definition at https://github.com/cmusatyalab/openface/commit/e534fa9c7f6585ef8f02f69300a4cbe680f2d746. Does my definition of the original network seem correct to you?

Also on your modification for re-training, make sure to add l2 normalization to the embedding so it's on the hypersphere.

-Brandon.

**Comment by northeastsquare** [comment]
Thank you,I will go  with your great suggestion! And share my experience.

**Comment by northeastsquare** [comment]
Hi, @bamos ,###  I train the vgg module, initialize weight with VGG_FACE.t7. But it runs out of gpu memory, which output:
THCudaCheck FAIL file=/tmp/luarocks_cutorch-scm-1-9192/cutorch/lib/THC/generic/THCStorage.cu line=41 error=2 : out of memory

### I train with the command:
./main.lua -data /media/silva/abcd1/face/casia-webface-alignedv2-224/ -modelDef ../models/openface/vgg-face.def.lua  -imgDim 224
### I initialize the weight with the following code:
  _vggm = torch.load('../models/openface/VGG_FACE.t7')
   vggm:remove(#model.modules)
   model:get(1).weight:copy(vggm:get(1).weight)
   model:get(1).bias:copy(vggm:get(1).bias)
   model:get(3).weight:copy(vggm:get(3).weight)
   model:get(3).bias:copy(vggm:get(3).bias)
   model:get(6).weight:copy(vggm:get(6).weight)
   model:get(6).bias:copy(vggm:get(6).bias)
   model:get(8).weight:copy(vggm:get(8).weight)
   model:get(8).bias:copy(vggm:get(8).bias)
   model:get(11).weight:copy(vggm:get(11).weight)
   model:get(11).bias:copy(vggm:get(11).bias)
   model:get(13).weight:copy(vggm:get(13).weight)
   model:get(13).bias:copy(vggm:get(13).bias)
   model:get(15).weight:copy(vggm:get(15).weight)
   model:get(15).bias:copy(vggm:get(15).bias)
   model:get(18).weight:copy(vggm:get(18).weight)
   model:get(18).bias:copy(vggm:get(18).bias)
   model:get(20).weight:copy(vggm:get(20).weight)
   model:get(20).bias:copy(vggm:get(20).bias)
   model:get(22).weight:copy(vggm:get(22).weight)
   model:get(22).bias:copy(vggm:get(22).bias)
   model:get(25).weight:copy(vggm:get(25).weight)
   model:get(25).bias:copy(vggm:get(25).bias)
   model:get(27).weight:copy(vggm:get(27).weight)
   model:get(27).bias:copy(vggm:get(27).bias)
   model:get(29).weight:copy(vggm:get(29).weight)
   model:get(29).bias:copy(vggm:get(29).bias)
   model:get(33).weight:copy(vggm:get(33).weight)
   model:get(33).bias:copy(vggm:get(33).bias)
   model:get(36).weight:copy(vggm:get(36).weight)
   model:get(36).bias:copy(vggm:get(36).bias)_

**Comment by bamos** [comment]
Hi @northeastsquare - how much GPU memory do you have? Try decreasing `imagesPerPerson` and/or `peoplePerBatch`.

-Brandon.

**Comment by pabloapast** [comment]
Hi @northeastsquare @bamos 
the last layers of the vgg network are:
```
 (33): nn.Linear(25088 -> 4096)
 (34): nn.ReLU
 (35): nn.Dropout(0.500000)
 (36): nn.Linear(4096 -> 4096)
 (37): nn.ReLU
 (38): nn.Dropout(0.500000)
 (39): nn.Linear(4096 -> 2622)
 (40): nn.SoftMax
```
so if I understand correctly, I need to delete the layers 40, 39, 38, 37 and in the file training/model.lua add the following code:
```
vggm = torch.load('../models/openface/VGG_FACE.t7')
vggm:remove(#model.modules)
model:get(1).weight:copy(vggm:get(1).weight)
model:get(1).bias:copy(vggm:get(1).bias)
model:get(3).weight:copy(vggm:get(3).weight)
model:get(3).bias:copy(vggm:get(3).bias)
model:get(6).weight:copy(vggm:get(6).weight)
model:get(6).bias:copy(vggm:get(6).bias)
model:get(8).weight:copy(vggm:get(8).weight)
model:get(8).bias:copy(vggm:get(8).bias)
model:get(11).weight:copy(vggm:get(11).weight)
model:get(11).bias:copy(vggm:get(11).bias)
model:get(13).weight:copy(vggm:get(13).weight)
model:get(13).bias:copy(vggm:get(13).bias)
model:get(15).weight:copy(vggm:get(15).weight)
model:get(15).bias:copy(vggm:get(15).bias)
model:get(18).weight:copy(vggm:get(18).weight)
model:get(18).bias:copy(vggm:get(18).bias)
model:get(20).weight:copy(vggm:get(20).weight)
model:get(20).bias:copy(vggm:get(20).bias)
model:get(22).weight:copy(vggm:get(22).weight)
model:get(22).bias:copy(vggm:get(22).bias)
model:get(25).weight:copy(vggm:get(25).weight)
model:get(25).bias:copy(vggm:get(25).bias)
model:get(27).weight:copy(vggm:get(27).weight)
model:get(27).bias:copy(vggm:get(27).bias)
model:get(29).weight:copy(vggm:get(29).weight)
model:get(29).bias:copy(vggm:get(29).bias)
model:get(33).weight:copy(vggm:get(33).weight)
model:get(33).bias:copy(vggm:get(33).bias)
model:get(36).weight:copy(vggm:get(36).weight)
model:get(36).bias:copy(vggm:get(36).bias)
```
but the two last lines of the code above correspond to the layer: ``` (36): nn.Linear(4096 -> 4096) ``` and in the code of models/openface/vgg-face.def.lua corresponds to ```net:add(nn.Linear(4096, opt.embSize))```. 
In first place, when I run main.lua with opt.embSize != 4096 I get an error and is something reasonably. I really want to use a value opt.embSize << 4096 because my gpu memory only have 2gb.
Second, can I delete the lines:
```
model:get(36).weight:copy(vggm:get(36).weight)
model:get(36).bias:copy(vggm:get(36).bias)
``` 
?
or are really necessary?

Thanks in advance!
