### ISSUE TITLE
Update to dlib 19.0 for faster face detection

### ISSUE THREAD

**Issue by bamos** [cmusatyalab/openface#157]
From @dwalle on gitter:

> Thanks for setting up this openface system! I have been enjoying tinkering around with it. I have noticed that Openface is currently using Dlib 18.16
And I have seen that among many features added to Dlib, they have also introduced GPU support on their object detector from their most recent release (Dlib 19.0 http://dlib.net/release_notes.html). I am wondering if you have any plans to upgrade the docker image to also be using the newest version of Dlib to see if the face detection can be any faster. Thanks!

**Comment by bamos** [comment]
Hi @dwalle - can you send a reference to the GPU-accelerated object detector? After a closer look (and thanks to https://twitter.com/pierreletes/status/751034557059784704 on Twitter), I can't find where this is mentioned or included in the release.

**Comment by dwalle** [comment]
Maybe I got ahead of myself in declaring that the DLIB face detection was faster solely due to GPU acceleration. However, the link I sent you for the release notes specify: "New Features: A deep learning toolkit using CPU and/or GPU hardware...." 
And later states: " Faster fHOG feature extraction / face detection"

I suppose I just set in my mind that the statement of the "Faster fHOG...face detection" was due to the GPU being introduced to Dlib for the first time. However, It may be that there were just improvements to the code so it runs a bit faster than before. I can go to the Dlib Sourceforge Discussion boards(https://sourceforge.net/p/dclib/discussion/442518/) to ask the author himself, since he seems to be replying to other people's questions quite often.

**Comment by Vijayenthiran** [comment]
I just complied dlib 19.0.0 in release mode with AVX instruction on my Macbook Pro 2012 (No GPU/CUDA support).

Here are the result of face detection when comparing with dlib 18.18.0

| Image Name       | dlib 18.18.0 (in seconds)          | dlib 19.0.0  (in seconds) |
| ------------- |:-------------:| -----:|
| images/examples/carell.jpg      | 0.521862983704 | 0.621522188187 |
| images/examples/adams.jpg      | 0.801635026932 | 0.751926898956 |
| images/examples/lennon-1.jpg | 1.34576201439 | 1.28734087944 |
| images/examples/lennon-2.jpg | 1.27731609344 | 1.38542199135 |

So, will the detection time will get improved only if I have GPU support?

**Comment by bamos** [comment]
Hi @Vijayenthiran - I assume these are just the results of a single execution. They're a little difficult to interpret since dlib 19 is sometimes faster and sometimes slower. Can you run my [profile-pipeline.py](https://github.com/cmusatyalab/openface/blob/master/util/profile-pipeline.py) script for dlib 18.18 and dlib 19 on your machine for these images? This will run detection and every other part of the pipeline 100 times (by default) and gives the means and std of the execution time. With these I expect dlib 19.0 to be equal to or faster than dlib 18.18. I plan to run this on my system soon so we understand the performance differences between dlib 18.18 and dlib 19.0.

Also I don't think the face detector has GPU support.

-Brandon.

**Comment by Vijayenthiran** [comment]
Thanks for the feedback @bamos. I ran  [profile-pipeline.py ](https://github.com/cmusatyalab/openface/issues/157#issuecomment-231735029) with dlib 18.18 and dlib 19 and here are the results:


| Image Name       | dlib 18.18.0 (in seconds)          | dlib 19.0.0  (in seconds) |
| ------------- |:-------------:| -----:|
| images/examples/carell.jpg      | 0.4336 +/- 0.0373 | 0.3697 +/- 0.0117 |
| images/examples/adams.jpg      | 0.7321 +/- 0.0738 | 0.6362 +/- 0.0982 |
| images/examples/lennon-1.jpg | 1.2371 +/- 0.0957 | 1.0428 +/- 0.0771 |
| images/examples/lennon-2.jpg | 1.2511 +/- 0.1574 | 1.0332 +/- 0.0532 |
| images/examples/clapton-1.jpg | 0.2004 +/- 0.0071 | 0.1927 +/- 0.0212 |
| images/examples/clapton-2.jpg | 0.1269 +/- 0.0065 | 0.1194 +/- 0.0121 |

dlib 19.0 does increase the detection speed but not very significantly in my laptop.

**Comment by bamos** [comment]
Thanks @Vijayenthiran, those numbers look better and a 10-20% improvement isn't bad. I'm getting a similar improvement on my server from 18.16 to 19.0 (both with AVX). (dlib on your laptop is faster than it is on my server!)

| Image Name       | dlib 18.16 (in seconds)          | dlib 19.0  (in seconds) | Improvement |
| ------------- |:-------------:| -----:|---:|
| carell.jpg      | 0.5495 +/- 0.0407 | 0.5035 +/- 0.0592 | 9.14%
| adams.jpg      | 0.9658 +/- 0.0983 | 0.8725 +/- 0.0865 | 10.7%
| lennon-1.jpg | 1.8377 +/- 0.1768 | 1.6584 +/- 0.1952 | 10.8%
| lennon-2.jpg | 1.8763 +/- 0.1597 | 1.6889 +/- 0.1479 | 11.1%
| clapton-1.jpg | 0.2670 +/- 0.0132 | 0.2163 +/- 0.0113 | 23.4%
| clapton-2.jpg | 0.1838 +/- 0.0136 | 0.1511 +/- 0.0105 | 21.6%

I have updated our Dockerfiles and pre-built containers to use dlib 19.0. Thanks for the improvement @davisking!

-Brandon.

**Comment by davisking** [comment]
No problem.  But we should thank @e-fominov, he did most of the speedup work. :)

**Comment by e-fominov** [comment]
If you are interested in details:
1. Dlib's face detector has no GPU support
2. Detector does not use color information - greyscale images will work faster
3. For best performance you can downscale images, because dlib works with small 80x80 faces for detection and use scanner.set_max_pyramid_levels(1) to exclude scanning of large faces. And also face detector has 5 cascades inside - they can be splitted if you need only frontal-looking faces for example; 
4. GCC-compiled code works much faster than any MSVC. MSVC 2015 works much faster than MSVC 2013
5. OpenCV's function cv::equalizeHist will make it find more faces

**Comment by Vijayenthiran** [comment]
Thanks @e-fominov for the details. I am interested in optimising dlib face detection for ARM platforms (esp. odroid xu4). Dlib face detection seems to be very slow when compared to opencv for ARM platforms. But I prefer dlib than opencv. 
I just compared opencv 2.4.11 and dlib 19.0 detection time:

| Image Name       | Img size for opencv          | opencv 2.4.11 | Img size for dlib </br> (Grayscale and half size)        | dlib 19.0 |
| ------------------------------- |-------------|--------------|-------|--------|
| [carell.jpg](https://github.com/cmusatyalab/openface/blob/master/images/examples/carell.jpg) | (891, 601, 3) | 0.9085 +/- 0.1241 | (446, 300) | 2.4800 +/- 0.0866 |
| [adams.jpg](https://github.com/cmusatyalab/openface/blob/master/images/examples/adams.jpg) | (1061, 800, 3) | 1.0296 +/- 0.0113 | (530, 400) | 4.0225 +/- 0.2669 |
| [lennon-1.jpg](https://github.com/cmusatyalab/openface/blob/master/images/examples/lennon-1.jpg) | (1050, 1400, 3) | 2.1386 +/- 0.019 | (525, 700) | 7.6231 +/- 0.4746 |
| [lennon-2.jpg](https://github.com/cmusatyalab/openface/blob/master/images/examples/1ennon-2.jpg) | (1200, 1200, 3) | 1.8136 +/- 0.0093 | (600, 600) | 7.3315 +- 0.4055 |
| [clapton-1.jpg](https://github.com/cmusatyalab/openface/blob/master/images/examples/clapton-1.jpg) | (420, 624, 3) | 0.3799 +/- 0.0284 | (210, 312) | 1.4729 +/ 0.1362 |
| [clapton-2.jpg](https://github.com/cmusatyalab/openface/blob/master/images/examples/clapton-2.jpg) | (400, 400, 3) |  0.2801 +/- 0.0241 | (200, 200) | 0.9659 +/- 0.1012 |


I would like to start with the 3rd point you mentioned in the previous comment. Are there api's for scanner.set_max_pyramid_levels(1) and splitting cascades in python? I couldn't fine any in the [dlib doc](http://dlib.net/python/index.html).

**Comment by e-fominov** [comment]
@Vijayenthiran, Unfortunately, scanner.set_max_pyramid_levels is not available for python API. Splitting cascades can be done in C++: you should split in C++, serialize into file and load splitted detector in python

About ARM processors - Dlib uses SIMD instructions in face detection algorithm. ARM processor's SIMD instructions set (NEON) is not compatible with SSE2 and Dlib works with basic CPU functions

Also I found that when calling dlib's detector you are telling it to increase image resolution:
align_dlib.py:104 (https://github.com/cmusatyalab/openface/blob/master/openface/align_dlib.py)
`            return self.detector(rgbImg, 1)
`

You can try run 
`return self.detector(rgbImg, 0)`

This should increase performance about 2x

**Comment by davisking** [comment]
NEON instructions are similar enough in overall structure that you should
be able to implement alternative versions of the simd classes in dlib (e.g.
https://github.com/davisking/dlib/blob/master/dlib/simd/simd8f.h).  All the
simd usage is through these classes, so if there were NEON versions of them
then things would be much faster on ARM.  I've had this on my todo list for
a long time but haven't gotten around to it yet.  You should give it a go :)

**Comment by bamos** [comment]
Related SO post: http://stackoverflow.com/questions/38525007/how-to-split-cascades-levels-in-dlib-frontal-face-detector

**Comment by fastfastball** [comment]
@Vijayenthiran, have you tried the 3rd point mentioned by  @e-fominov? if yes, do you have any update for detection time test result ? BTW, maybe you can also take a look at https://github.com/tzutalin/dlib-android/issues/15 for possible methods to improve the performance.

@davisking, do you have NEON version now? :)

**Comment by davisking** [comment]
No, I haven't made any NEON version.  I'm probably not going to do so for
quite a while either, so if anyone wants one someone else will probably
need to do it :)

**Comment by fastfastball** [comment]
@davisking, got it. I may write one if free :)

One more question : Does Dlib's face detector support multi-threading? That is if i have a 4 cores arm processor(for ex: Qualcomm snapdragon 810), does Dlib's face detector use all 4 cores to speed up the detection procedure? If the answer is No, is it possible to re-write Dlib's face detector by OpenCL to use GPU to speed up?

**Comment by e-fominov** [comment]
@fastfastball , no Dlib's face detector does not support multi-threading in object detection and it does not support GPU. Some parts of its code can be rewrited to make it run parallel
If you need to process video I recommend you to process each frame in separate thread - much easier and it will give you required speedup, but please notice that you will need separate copy of detector for each thread and you can use one global shape predictor for all threads

**Comment by fastfastball** [comment]
@e-fominov, thanks for your suggestion, i will try it for processing video. BTW, the video i will process comes from camera. And, the os/chipset i use is android/snapdragon 810(not a x86 chipset), so performance is an important issue. opencv has better performance, however, i do not want to use it because it has many false positive.

**Comment by fastfastball** [comment]
@davisking, in order to reduce the face detect time, I follow e-fominov's suggestion to modify object_detector.h as below to reduce "num_detectors" from 5 to 3. 
===
    void deserialize (
        object_detector<T>& item,
        std::istream& in 
    )
    {
...... 
        else if (version == 2)
        {
......
            unsigned long num_detectors = 0;
            deserialize(num_detectors, in);
	    num_detectors = 3; <== I add this line
            item.w.resize(num_detectors);
......
}
===
After modification, I found that there is no false positive and also no false negative while testing the pics in https://github.com/davisking/dlib/tree/master/examples/faces . However, I know there must be some side effects. Could you please show me some pics will be impacted by my modification? 

Another question is : if setting num_detectors to 3, which 2 detectors will be removed? Are they front-rotate-right detector and front-rotate-left detector? (I saw that your comments in frontal_face_detector.h mention 5 detectos)

Thanks

**Comment by e-fominov** [comment]
@fastfastball , i can answer your question. last 2 detectors will be removed - for the faces rotated left/right 27 degrees. this will make it be less-preciese and skip some faces in a future. i.e. false positive rate will decrease, false negative rate will increase

https://github.com/davisking/dlib/tree/master/examples/faces is a very small set of faces. you should try something larger - download lfw dataset and test with it http://vis-www.cs.umass.edu/lfw/. One image = one face, very easy to check

have you got any performance gain? how much?

**Comment by fastfastball** [comment]
@e-fominov, i try 5/3/1 detectors and the detection time is 1.4s/1.06s/0.77s.
my test setup is as below
os : andoird 5.0 w/ dlib in https://github.com/tzutalin/dlib-android/tree/master/jni
hw: snapdragon615(cortex a53@1.4G)
test image : 2007_007763.jpg in https://github.com/davisking/dlib/tree/master/examples/faces. I enlarge it by 2X2 because in my application I need to detect small face.

**Comment by fastfastball** [comment]
@e-fominov, i modify the code to add neon support to dlib, and also modify some functions to run parallel on 3 cpus. The number of detectors is 1. After these modifications, the detection time is reduced to 0.16s.(4.8X faster) Before modification, the time is 0.77s. My test setup is the same as one in my previous comment.

@davisking, I have finished the very first version of simd4f.h and simd4i.h for supporting neon in dlib. The code is in https://github.com/fastfastball/arm_neon_for_dlib_simd . I have roughly tested it by doing face detection on several pictures. The results are correct. To make sure every function works correctly, may I know if you have any test code to verify it?  If you have, I can test it and issue a pull request.

**Comment by davisking** [comment]
@fastfastball Awesome.  There isn't any explicit simd test code.  But a number of the image processing functions use it and those functions are part of the unit tests.  So running the regular unit tests is reasonable.  Although it wouldn't be a bad idea to add explicit simd test cases to the unit test suite.

**Comment by tsingjinyun** [comment]
@fastfastball ,how to use your neon code, and i plan to accelerate cuda version code of face detect module, any hints?

**Comment by fastfastball** [comment]
@tsingjinyun, you can just replace simd4f.h, simd4i.h, and simd_check.h with the ones in https://github.com/fastfastball/arm_neon_for_dlib_simd . Then, compile it with __ARM_NEON compile option enabled. The 3 files are in dlib/simd/ folder.

I am doing my job on Android. So, for me, I follow this link https://developer.android.com/ndk/guides/cpu-arm-neon.html to turn on the compile option.

for cuda version, i have no idea. maybe davis or e-fominov can give u useful suggestion :)

**Comment by tvd2840** [comment]
@fastfastball Do you know how to compile it with NEON instruction enabled for iOS? Thanks!

**Comment by fastfastball** [comment]
for iOS, i have no idea

**Comment by amirmaessence** [comment]
@fastfastball  thank you, i tested your optimization and it greatly reduced detection time
can you also add the modified code for working in parallel?

**Comment by fastfastball** [comment]
@amirmaessence, what's your test result? And, which platform did you test? android 5.0 on cortex-a53?

**Comment by amirmaessence** [comment]
@fastfastball, i'v tested it with debian on cortex-a53
detection time now is about x5 faster

**Comment by davisking** [comment]
@amirmaessence sweet.  Are you going to submit a pull request back to dlib? :)

**Comment by pythonanonuser** [comment]
i've tested it on the cortex a57 and while there is an improvem it's still a fair bit slower than SSE4. I'm assuming this is because there isn't any converstions done for `simd8f.h` and `simd8i.h`. Any advice?@davisking @fastfastball @amirmaessence

**Comment by fastfastball** [comment]
@pythonanonuser, arm simd instructions only support 128bits. So, I do not know how to convert simd8x.h into arm instructions. simd8 is now supported by 2 simd4. I think it's a limitation for arm

**Comment by fastfastball** [comment]
@amirmaessence, for "the modified code for working in parallel", i upload it in https://github.com/fastfastball/dlib_for_arm . enjoy it. :-) 

This link also includes simd modification. So, you don't need to apply simd patch again. For the detail, plz check https://github.com/fastfastball/dlib_for_arm/blob/master/README.md . 

BTW, the code uploaded is to quickly check how much performance gain i can get if TLP is phased into dlib. So, code looks ugly :-( . however, it is faster and stable (at least in my testing :p)

**Comment by pythonanonuser** [comment]
@fastfastball  Can you specify what files were altered as far as the "working in parallel" changes are concerned?

**Comment by tsingjinyun** [comment]
@pythonanonuser ,@fastfastball  thanks for your great work, and how to compile with __ARM_NEON parameter with cmake?
as i use cmake .. -DARM_NEON=1 ,but it doesn't open arm options.

**Comment by pythonanonuser** [comment]
Try setting -mcpu or -fmpu flags.

**Comment by fastfastball** [comment]
@pythonanonuser, the list is as below
array_kernel.h in dlib\array
array2d_kernel.h in dlib\array2d
frontal_face_detector.h in dlib\image_processing
object_detector.h in dlib\image_processing
scan_fhog_pyramid.h in dlib\image_processing
fhog.h in dlib\image_transforms
image_pyramid.h in dlib\image_transforms
interpolation.h in dlib\image_transforms

**Comment by pythonanonuser** [comment]
@fastfastball thanks! I will play around with some of this stuff and see what's most effective.

**Comment by piliwilliam0306** [comment]
@fastfastball 
Would adding libjpeg-turbo help speeding up??

**Comment by fastfastball** [comment]
@piliwilliam0306, i think it may decrease the time to decode a jpeg file. However, the detection time will still be the same as before.

**Comment by pythonanonuser** [comment]
I'm surprised you're getting less than 70 ms. With all the modifications, I'm only able to achieve a max of 12 fps for face detection. Still better than the 5 fps I got with just adding NEON, but looks I'm missing something?

**Comment by fastfastball** [comment]
@pythonanonuser, 
1) which ARM SOC are you using? for ex: qualcomm msm8939
2) did you apply my modification in objection_detection.h?
3) are you using clang? I found that clang is better than gcc
4) did you pay attention to the thermal issue? plz use command "cat /sys/devices/system/cpu/cpu*/cpufreq/cpuinfo_cur_freq" to check if all CPUs are all working at highest speed.

**Comment by pythonanonuser** [comment]
@fastfastball 
1) I'm using the Jetson TX1 
2) Yes, I pulled directly from your linked repo
3) No I'm using gcc. I prefer gcc just because the Jetson comes prepackaged with libraries optimized for it (such as OpenCV) that I believe are compiled using gcc. I've had issues trying to link a gcc compiled library with a clang one in the past, but I will give clang a try and see if it works.
4) The TX1 has a `jetson_clocks.sh` script which maximizes CPU performance but I didn't notice a speedup with or without it. I'm using about 45-50% of each core when its running. 
5) I had to comment out the logging because I was getting conflict errors with dlib's own timer functions while compiling. I'll see if I can figure out another way to time it.
6) No, I've just been using standard static libraries (.a and .so) to link. I hadn't heard of arm binaries. Whats the benefit and how do you compile into these?

**Comment by abinlee** [comment]
@fastfastball Does dlib_for_arm support to build python library? and how?

**Comment by amirmaessence** [comment]
@abinlee , yes. 
simply make sure that DLIB_HAVE_NEON is defined on the simd_check.h file
and compile to python the usual way

**Comment by thomasd3** [comment]
Regarding multi-threading, on x64:
I load the shape predictor once, and share it across all threads.
and I'm trying to get one detector per thread.

So for each call I have:
frontal_face_detector detector = get_frontal_face_detector();

and this works; but to save the creation at every call, I tried to have the following, outside the function call:

thread_local frontal_face_detector detector = get_frontal_face_detector();

but I keep getting 'divide by 0' exceptions; any idea why this could be causing a problem?

**Comment by davisking** [comment]
You are probably accidentally sharing an object between threads that you
don't realize.

**Comment by maybepossible** [comment]
@fastfastball  I am new to Android, How to run this code on Android? Could you give some hints? Thanks a lot.

**Comment by fastfastball** [comment]
@maybepossible, you can download https://github.com/tzutalin/dlib-android .
This project is buildable under android build environment.
You can build it first, then replace its dlib folder with mine.

**Comment by maybepossible** [comment]
@fastfastball Do I need to use the Android version of boost and tbb then? but I didn't find android tbb on the web.

**Comment by fastfastball** [comment]
I think no. I have implemented multi-threading by pthread in my project

2017/1/19 下午1:52，"maybepossible" <notifications@github.com>寫道：

@fastfastball <https://github.com/fastfastball> Do I need to use the
Android version of boost and tbb then? but I didn't find android tbb on the
web.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/cmusatyalab/openface/issues/157#issuecomment-273688371>,
or mute the thread

**Comment by pencoa** [comment]
[how-to-use-mmod-human-face-detector-dat-in-dlib-frontal-face-detector](http://stackoverflow.com/questions/43203459/how-to-use-mmod-human-face-detector-dat-in-dlib-frontal-face-detector)

**Comment by gicheonkang** [comment]
hi @fastfastball @e-fominov 
I read all the comments you guys said above, "Optimization of dlib"
I'm making a app which detects facial landmark ( 68 points, dlib HOG)

I'm in trouble optimizing a size of frame. you know android-platform is poor than laptop. 
I also use cortex a53@1.4Ghz :)  I tried my best minimizing frame size  but, it is not a joke..
Do you have any updated approach ??
Thanks a lot !

**Comment by JansHub** [comment]
Hi guys!

I'm using dlib with Python API and I can't figure out how to compile it in release mode.

For example to compile it with AVX instruction I can use this line:
python setup.py install --yes USE_AVX_INSTRUCTIONS 
as told here: https://pypi.python.org/pypi/dlib But unfortunately I can't find how to specify that I want to compile it in debug mode.

Maybe somebody knows how to do that?

**Comment by mgilge** [comment]
@fastfastball awesome work. I was wondering which tool you are using to profile ARM code? I am using VisualGDB for cross compiling but the environment is lacking any profiling tools.

**Comment by mgilge** [comment]
Hi guys,
I have retrained the facial landmark detector for a subset of only 11 landmarks instead of 68. This reduces the size of the model data down to 2.9MB (from 97.4MB originally) and speeds up detection. For training I used the face databases which davis has provided. Retained were the landmarks no. 8, 27, 30, 36, 39, 42, 45, 48, 51, 54, 57.

**Comment by vchatterji** [comment]
Dlib 19.4 ships with trained model without a need for Torch. It is available as a package for Anaconda/Miniconda via conda-forge.

**Comment by vchatterji** [comment]
https://anaconda.org/conda-forge/dlib
(not my repo)

**Comment by thomasd3** [comment]
@mgilge: the smaller model data for the faces, is it part of 19.4?

**Comment by mgilge** [comment]
No, it is trained on the data provided by dlib but using only a subset of landmarks.

Sent from my iPhone

**Comment by thomasd3** [comment]
can you share the code to do the training?

**Comment by jyurek** [comment]
@fastfastball I see the code for NEON is in dlib proper now, but is there a way to use your modifications to only detecting front-facing faces and using multithreading to master (or v19.4) dlib?

**Comment by RoyiAvital** [comment]
@e-fominov , Could you share numbers for speed improvement between MSVC 2015 and GCC?

Could you be specific on the GCC version you use?

Moreover, when you say Histogram Equalization makes it find more faces, do you mean find the face in hard illumination conditions or just for cases of many faces in the same image?

Thank You.

**Comment by sharpstill** [comment]
@bamos  How to compile dlib in IBM power8 machine and use it in python(get optimized compiled speed)
I have submitted in
https://stackoverflow.com/questions/46657938/how-to-compile-dlib-in-ibm-power8-machine-and-use-it-in-pythonget-optimized-com

**Comment by Nesh108** [comment]
@mgilge could you share the retrained data? :smile:

**Comment by kallivad** [comment]
@sharpstill  Your link is not working. Could you describe somewhere how to compile dlib for IBM Power8 platform?
