### ISSUE TITLE
Hosting A Web Demo

### ISSUE THREAD

**Issue by TylerL-uxai** [cmusatyalab/openface#16]
I'd be happy to get a heroku or AWS version of the web demo up. 

Based on my actual behavioral evidence, **"web demo" was the first link I clicked.** Going on that data (the Human-Computer Interaction department at CMU might appreciate this), I think setting up a simple heroku deployment is worthwhile. 

Only obstacle is hosting fees, if you guys have a budget, or someone's server space.

**Comment by bamos** [comment]
Hi Tyler,

Great idea, I agree. Hosting the web demo would be incredibly valuable and would allow people to experiment with the system in their browser without having to set up the environment.

However, I don't think the current server will scale well to more than a few clients at the same time. The structure of the app inefficiently transfers a lot of data: video feed from the browser to server, then annotated video back to the browser. This can be improved, but wasn't an initial focus of the project.

What are your thoughts on providing AWS or a Heroko deploy button? See https://aws.amazon.com/codedeploy/ and https://devcenter.heroku.com/articles/heroku-button.
Then, users will be able to quickly spin up the web demo using their AWS/Heroku instances.

-Brandon.

**Comment by TylerL-uxai** [comment]
Hey Brandon,

You can scale but it might cost something like 1$ an hour for 10 instances. That's the nice thing about heroku or amazon. Websites like facebook or youtube are built on top of platforms where they just drag the slider for number of instances they want to distribute the CPU load to and their job is to take care of the hardware side of it. I think AWS costs like 10 cents an hour and if you're getting a few people to run on one cpu, you might need more. I can show you a screen shot of the heroku interface and the process of scaling the number of CPUs you have dedicated to a website.

**Comment by TylerL-uxai** [comment]
2 or 3 years ago when I built this website, it cost 34.50$/month for my heroku website. Now it only costs 7 for a simple site. The cost of computing is getting cheaper!
