### ISSUE TITLE
Windows error 2 : The system cannot find the file specified (startupinfo)

### ISSUE THREAD

**Issue by Manasip8** [cmusatyalab/openface#164]
### Context of the issue
I am running torch subprocess on windows 10 and I get this error
windows error [error 2] : The system cannot find the file specified

  File "C:\Users\Aim\Miniconda2\lib\subprocess.py", line 959, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

### Expected behavior.
[Describe what you would expect to have resulted from this process.]

### Actual behavior.
[Describe what you currently experience from this process, and thereby explain the bug.]

### Steps to reproduce.
[Present a minimal example and steps to produce the issue.]

### OS and hardware information.

+ Operating system: [todo]
+ Torch version: [todo]
+ CPU architecture: [todo]
+ GPU type (if using): [todo]

**Comment by bamos** [comment]
Hi @Manasip8 - we currently do not support Windows. If you're interested in making OpenFace work on Windows, I'd be happy to accept a PR adding it.

-Brandon.

**Comment by aarti9** [comment]
Hi Brandon, I am interested in making it work on Windows. 

I have Visual Studio 2015 installed as mentioned in the wiki. I did get initial error build tools for v141 not found, for which I corrected each sub module's properties to set it to v140. Now I get CL.exe not found.

If you have any pointers let me know. Also guide me how can I contribute

**Comment by Mahdidrm** [comment]
Dear @bamos ;
Thank you very much for this amazing program;
Could you please tell me, did you prepare open face's Python code for windows or not? because I face the same problem and need to run in in Windows 7 - 6bit

Thanks again and regards
