### ISSUE TITLE
Bus error in extracting features in Odroid C2

### ISSUE THREAD

**Issue by nitish11** [cmusatyalab/openface#168]
### Context of the issue.
I was setting up a sample example [environment](https://cmusatyalab.github.io/openface/demo-3-classifier/#minimal-working-example-to-extract-features), I got error while executing command to extract features for aligned images. I am using Odroid C2.

### Command executed : 
`odroid@odroid64:~/face-recognition/openface$ ./batch-represent/main.lua -outDir classify-test/features -data classify-test/aligned`

### Actual behavior.
```
{
  outDir : "classify-test/features"
  imgDim : 96
  device : 1
  data : "classify-test/aligned"
  model : "/home/odroid/face-recognition/openface/models/openface/nn4.small2.v1.t7"
  cuda : false
  batchSize : 50
  cache : false
}
**Bus error**


```
Based on my observation and debugging on ./batch-represent/main.lua file, I observed, the error coming from the below two lines

```
paths.dofile('dataset.lua')
paths.dofile('batch-represent.lua')
```

### OS and hardware information.

+ Operating system: Ubuntu 14.04
+ Torch version: torch7
+ CPU architecture: 64-bit
+ Device : Linux odroid64 3.14.65-61 aarch64 GNU/Linux

**Comment by bamos** [comment]
Hi @nitish11 - what line of `batch-represent` is causing this?

**Comment by nitish11** [comment]
@bamos : 

The error is coming from  below from [line](https://github.com/cmusatyalab/openface/blob/master/batch-represent/main.lua#L30).

When I checked dataset.lua, I error came at [line](https://github.com/cmusatyalab/openface/blob/master/batch-represent/dataset.lua#L14)
```
local initcheck = argcheck{ ....
...........
```

**Comment by nitish11** [comment]
The issue was in installation of Torch. Install torch using following instructions.


```
rm -rf ~/torch

# in a terminal, run the commands WITHOUT sudo
git clone https://github.com/torch/distro.git ~/torch --recursive
./clean.sh
cd ~/torch; bash install-deps;
./install.sh

# On Linux with bash
source ~/.bashrc

luarocks install nn
luarocks install dpnn
```

Test torch installation using :

` th -lnn -e "nn.test()"`
