### ISSUE TITLE
Error in loading model on Raspberry PI

### ISSUE THREAD

**Issue by nitish11** [cmusatyalab/openface#169]
### Context of the issue.
I was setting up a sample example [environment](https://cmusatyalab.github.io/openface/demo-3-classifier/#minimal-working-example-to-extract-features), I got error while executing command to extract features for aligned images. I am using raspberrypi.

### Command executed : 
_pi@raspberrypi:~/face-recognition/openface $ ./batch-represent/main.lua -outDir classify-test/features -data classify-test/aligned_

### Actual behavior.
```
{
  data : "classify-test/aligned"
  imgDim : 96
  model : "/home/pi/face-recognition/openface/models/openface/nn4.small2.v1.t7"
  device : 1
  outDir : "classify-test/features"
  cache : false
  cuda : false
  batchSize : 50
}
/home/pi/torch/install/bin/luajit: /home/pi/torch/install/share/lua/5.1/torch/File.lua:370: table index is nil
stack traceback:
	/home/pi/torch/install/share/lua/5.1/torch/File.lua:370: in function 'readObject'
	/home/pi/torch/install/share/lua/5.1/nn/Module.lua:158: in function 'read'
	/home/pi/torch/install/share/lua/5.1/torch/File.lua:351: in function 'readObject'
	/home/pi/torch/install/share/lua/5.1/torch/File.lua:409: in function 'load'
	./batch-represent/main.lua:38: in main chunk
	[C]: in function 'dofile'
	...e/pi/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00014f88
```

### OS and hardware information.

+ Operating system: Ubuntu 14.04
+ Torch version: torch7
+ CPU architecture: 64-bit
+ Device :Linux raspberrypi 4.4.15-v7+ armv7l GNU/Linux

**Comment by nitish11** [comment]
Hi,

I resolved the issue, I checked similar [issue](https://github.com/cmusatyalab/openface/issues/42).
I resolved by downloading ascii neural net model and updating the model load path.

I updated the [line](https://github.com/cmusatyalab/openface/blob/master/batch-represent/main.lua#L33) 
with `model = torch.load('models/openface/nn4.small2.v1.ascii.t7','ascii')`


For own classifier, I edited line 46  in _/usr/local/lib/python2.7/dist-packages/openface/openface_server.lua_
`net = torch.load(opt.model)`

Replace with 
`net = torch.load('./models/openface/nn4.small2.v1.ascii.t7','ascii')
`

**Comment by bamos** [comment]
Great, glad the ASCII model's working! Our website doesn't make this very clear for users on ARM, so I just added a section in the FAQ saying that ARM users should use the ASCII model. By the way, to load it faster, you can load the ASCII model on ARM and then save it as binary model.

-Brandon.

**Comment by soumith** [comment]
if you want to load the binary model directly on ARM (32-bit or 64-bit) here's how (assuming "filename" is the model file):

```lua
file = torch.DiskFile(filename, 'r')
file:longSize(8)
net = file:readObject()
file:close()
```

**Comment by nitish11** [comment]
@soumith : I tried your approach to convert the model file. I got the below error. 

```
/home/ubuntu/torch/install/bin/luajit: /home/ubuntu/torch/install/share/lua/5.1/torch/File.lua:259: read error: read 0 blocks instead of 1 at /home/ubuntu/torch/pkg/torch/lib/TH/THDiskFile.c:332
stack traceback:
[C]: in function 'readInt'
/home/ubuntu/torch/install/share/lua/5.1/torch/File.lua:259: in function 'readObject'
...lib/python2.7/dist-packages/openface/openface_server.lua:50: in main chunk
[C]: in function 'dofile'
...untu/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
[C]: at 0x00014895
```

**Comment by weiqifa0** [comment]
Thank you !!

**Comment by AdamMiltonBarker** [comment]
This helped me solve the issue also, RE Raspberry Pi, is it normal for identification to take up to 30 seconds, with Tensorflow on the RPI I have been able to do it in a couple of seconds max but still unable to solve the unknown issue with Tensorflow.

**Comment by KGOURAV** [comment]
hey @bamos,
as you have said to save the model in ascii format i have saved it and i have tried these commands they are perfectly working

$ th
th> require 'nn'
th> require 'dpnn'
th> net = torch.load('nn4.v1.ascii.t7', 'ascii')

but again when i try this `command ./batch-represent/main.lua -outDir ./generated-embeddings/ -data ./aligned-images/

this is the error i am getting

/home/pi/torch/install/share/lua/5.1/torch/File.lua:375: unknown object
stack traceback:
[C]: in function 'error'
/home/pi/torch/install/share/lua/5.1/torch/File.lua:375: in function 'readObject'
/home/pi/torch/install/share/lua/5.1/torch/File.lua:409: in function 'load'

./batch-represent/main.lua:33: in main chunk
[C]: in function 'dofile'
...e/pi/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
[C]: at 0x00014fa8

**Comment by nitish11** [comment]
@KGOURAV : try the solution suggested by @soumith as below:

```
file = torch.DiskFile(filename, 'r')
file:longSize(8)
net = file:readObject()
file:close()
```

**Comment by KGOURAV** [comment]
Hi when I run ./demos/classifier.Py/ infer
./generated-embeddings/classifier.pkl test.jpg I get the same error
Pls help me out

**Comment by BarbaL** [comment]
@KGOURAV i got the same issue.

I've changed the _/openface_server.lua_ on line 47 to the same model as i enter in _main.lua_:
`net = torch.load('~biometriafacial/openface/models/openface/nn4.small2.v1.ascii.t7','ascii')`

But still i get error. Someone has found any solution for this? In compare.py it work ok, but not to classifier.py

Error Log:

> cannot open <models/openface/nn4.small2.v1.ascii.t7> in mode r  at /home/biometriafacial/torch```
/pkg/torch/lib/TH/THDiskFile.c:670
stack traceback:
	[C]: at 0x76adb1e9
	[C]: in function 'DiskFile'
	...ometriafacial/torch/install/share/lua/5.1/torch/File.lua:405: in function 'load'
	...lib/python2.7/dist-packages/openface/openface_server.lua:47: in main chunk
	[C]: in function 'dofile'
	...cial/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00014895
> 
> 
> Error getting result from Torch subprocess.
> 
> Line read: 
> 
> Exception:
> 
> could not convert string to float: 
> 
> ============
> 
> stdout: 
>

**Comment by tengqi200** [comment]
@BarbaL Excuse me, have you solved the problem? The classifier.py can work normal in my PI, but not to the files I wrote.
