### ISSUE TITLE
Documentation Fix - "Please Use Responsibly!"

### ISSUE THREAD

**Issue by TylerL-uxai** [cmusatyalab/openface#17]
This documentation is fantastic. I really like all the pictures and I'm just making an effort to improve it further.

"Please use responsibly!" section possibly violates the TOS for open source software. I think one of the definitions of "open" is not limiting people's ability to use the software, depending on the license you use.

**Comment by TylerL-uxai** [comment]
I'd like to further add that it's important you communicate your personal involvement with the project. There's a sentence about your work focusing on helping disabled people. An "About Us" section seems appropriate or perhaps adding some detail near your names. Another possible suggestion is including this fact as part of a concrete example of how this technology is used. Helping people see is pretty inspiring.

**Comment by jaharkes** [comment]
The license of the code and models is Apache 2.0.

The "Please use responsibly" section of the readme is not part of the license. I believe it is important as it does make people think about how their work interacts with the world around them.

**Comment by bamos** [comment]
Hi @TylerL-uxai - thanks for your thoughts on this and for submitting the PR.
I agree with @jaharkes - I think the section is important to have.
It presents our views, but does not restrict the licensing of the code or models.

-Brandon.
