### ISSUE TITLE
Train with MS-Celeb-1M Dataset

### ISSUE THREAD

**Issue by bamos** [cmusatyalab/openface#170]
- ECCV paper published on arxiv on July 27: http://arxiv.org/abs/1607.08221
- Download link: https://www.microsoft.com/en-us/research/project/ms-celeb-1m-challenge-recognizing-one-million-celebrities-real-world/

**Comment by FedericoRuiz1** [comment]
This is awesome! Do you have access to a computer that can handle this?

**Comment by bamos** [comment]
Training will probably take a while, I just use a Titan X on data from an HDD. Resolving #132 and #117 will help speed up some data-related parts of training.

**Comment by GabrielLIN** [comment]
The idea is great. However, MS-Celeb-1M Dataset is absolutely dirty. How do you deal with this issue?

**Comment by bamos** [comment]
Training with MS-Celeb-1M is looking great so far. We're currently at ~95% accuracy and it's (slowly) rising, our best published model gets 92.92% accuracy. I have temporarily made the model available [here](http://joule.isr.cs.cmu.edu:1359/model_150.t7) if anybody's interested. It uses the `innerEyesAndBottomLips` alignment.

![image](https://cloud.githubusercontent.com/assets/707462/17908731/9deaab62-694f-11e6-9682-35394396b0f1.png)

**Comment by bamos** [comment]
(I started training this network 2 days ago.)

**Comment by shimen** [comment]
Hi @bamos,
It is strange, I got better results with the old model. I had used the innerEyesAndBottomLips alignment.
I had tested it on 2 of my datasets. The model that I trained with the VGG data as I mentioned in https://github.com/cmusatyalab/openface/issues/103 gets far better results.

here are the results:
**# DATA1: 893id**
**893id_nn4 small2 v1**
![893id_nn4 small2 v1](https://cloud.githubusercontent.com/assets/10295217/17976914/2b4c09e8-6af8-11e6-8c84-b4bf0630f684.jpg)

**893id_ms-celeb-1m_150_innereyesandbottomlips**
![893id_ms-celeb-1m_150_innereyesandbottomlips](https://cloud.githubusercontent.com/assets/10295217/17976919/34962740-6af8-11e6-9d13-f6c524372d4d.jpg)

**893id_vgg_120**
![893id_vgg_120](https://cloud.githubusercontent.com/assets/10295217/17976930/44b26a76-6af8-11e6-9164-1adf7a8b05ea.jpg)

**DATA2: myprofile**
**myprofile_nn4 small2 v1**
![myprofile_nn4 small2 v1](https://cloud.githubusercontent.com/assets/10295217/17976935/4b327f4e-6af8-11e6-8b12-f22230b111af.jpg)

**myprofile_ms-celeb-1m_150_innereyesandbottomlips**
![myprofile_ms-celeb-1m_150_innereyesandbottomlips](https://cloud.githubusercontent.com/assets/10295217/17976932/4819e5d6-6af8-11e6-96d6-6e7bfa6664d0.jpg)

**myprofile_vgg_120**
![myprofile_vgg_120](https://cloud.githubusercontent.com/assets/10295217/17976937/4eeaceac-6af8-11e6-97eb-106e8792b213.jpg)

**Comment by FedericoRuiz1** [comment]
@bamos @shimen I haven't actually ran any benchmarks, but at first glance it also seems like It performs worse for me. I ran both models in parallel and the new one gave false positives more often.

Its weird that Its more accurate for LFW but less accurate for us. Any ideas of what might be happening?

**Comment by skrew** [comment]
@bamos How do you do that in 2 days (with partial results of model) ? I running the last part for 2 days with a Titan X (Pascal) and got nothing ! :)

```
./demos/classifier.py --cuda train ../ms-generated-embeddings/
/usr/local/lib/python2.7/dist-packages/sklearn/lda.py:4: DeprecationWarning: lda.LDA has been moved to discriminant_analysis.LinearDiscriminantAnalysis in 0.17 and will be removed in 0.19
  "in 0.17 and will be removed in 0.19", DeprecationWarning)
Loading embeddings.
Training for 99832 classes.
```

It just eating CPU and 88% of my memory (i have 32Go)...
Seem something got wrong for me ;)

**Comment by saurav111** [comment]
Hey @bamos , the link to the ~95% accuracy model is broken. Also, what accuracy did you get finally?
Thanks.

**Comment by bamos** [comment]
Hi @saurav111 - as I mentioned, the link was only temporary :) I've been using my GPUs for other experiments and haven't yet been able to resume training on this.

**Comment by cggaurav** [comment]
Hey @bamos do you have the trained model by any chance? We humans don't have access to supercomputers.

**Comment by MaxwellNM** [comment]
Hi,
I want to reproduce the classification of MS-Celeb through your article http://arxiv.org/abs/1607.08221
I' have ubuntu 16.04 and Pascal GPU 375 driver, Cuda is already install, when i train with DBN classifier with cuda option it seems the code is still running in CPU. No see GPU impact. 
I didn't want to re install cuda from the openface Docker's configuraton file, to prevent removal of the previous cuda installed in my OS
Ps what's wrong ?
