### ISSUE TITLE
Error in output on Jetson

### ISSUE THREAD

**Issue by nitish11** [cmusatyalab/openface#180]
### Context of the issue.
I am setting up a sample example [environment](https://cmusatyalab.github.io/openface/demo-3-classifier/#minimal-working-example-to-extract-features) on NVIDIA Jetson tegra. <br/>
I am not getting any error in building. I am getting error in output. The representations coming out from deep net trained model are not as expected. 

### Command executed : 
`root@tegra-ubuntu:/home/ubuntu/face-recognition/openface# ./demos/classifier.py infer ./models/openface/celeb-classifier.nn4.small2.v1.pkl images/examples/{carell,adams,lennon}*`

### Actual behavior.
```
=== images/examples/carell.jpg ===
Predict BenStiller with 0.67 confidence.

=== images/examples/adams.jpg ===
Predict BenStiller with 0.67 confidence.

=== images/examples/lennon-1.jpg ===
Predict BenStiller with 0.67 confidence.

=== images/examples/lennon-2.jpg ===
Predict BenStiller with 0.67 confidence.

```

### OS and hardware information.

+ Operating system: Ubuntu 14.04
+ Torch version: torch7
+ CPU architecture: 64-bit
+ Device : Linux tegra-ubuntu 3.10.96-tegra aarch64 GNU/Linux

**Comment by bamos** [comment]
This is potentially related to https://groups.google.com/forum/#!topic/cmu-openface/O029A5QQDm0. The latest Torch version temporarily had an issue causing the network to always output the same value regardless of the input that has been fixed in the latest version. Can you re-install Torch or the nn/cunn packages?

```
luarocks install nn
# If using CUDA
luarocks install cunn
```

**Comment by nitish11** [comment]
@bamos  :+1:  thanks. 
The issue was in latest torch build.  Follow the below commands. 

```
git clone https://github.com/torch/distro.git ~/torch
cd ~/torch 
git checkout f95379d8512ab96939b0d797c489bbaedf7fa313 
git submodule update --init --recursive 
./install-deps 
./install.sh 
. ~/.bashrc
luarocks install dpnn
```
