### ISSUE TITLE
"double free or corruption" error when running batch represent on a directory with Japanese folder names

### ISSUE THREAD

**Issue by AlvarHHM** [cmusatyalab/openface#181]
Context of the issue.

I am following the tutorial code in here 
https://medium.com/@ageitgey/machine-learning-is-fun-part-4-modern-face-recognition-with-deep-learning-c3cffc121d78#.qxwjbkn93

I am running with japanese folder name, I think I cause the error

Expected behavior.

No error

Actual behavior.

root@f3778037c099:~/openface# ./batch-represent/main.lua -outDir ./generated-embeddings/ -data ./aligned-images/
{
  data : "./aligned-images/"
  imgDim : 96
  model : "/root/openface/models/openface/nn4.small2.v1.t7"
  device : 1
  outDir : "./generated-embeddings/"
  cache : false
  cuda : false
  batchSize : 50
}
./aligned-images/
cache lotation:         /root/openface/aligned-images/cache.t7
Creating metadata for cache.
{
  sampleSize :
    {
      1 : 3
      2 : 96
      3 : 96
    }
  split : 0
  verbose : true
  paths :
    {
      1 : "./aligned-images/"
    }
  samplingMode : "balanced"
  loadSize :
    {
      1 : 3
      2 : 96
      3 : 96
    }
}
running "find" on each class directory, and concatenate all those filenames into a single file containing all image paths for a given class
now combine all the files to a single large file
load the large concatenated list of sample paths to self.imagePath
**\* Error in `/root/torch/install/bin/luajit': double free or corruption (!prev): 0x00000000013e4e50 ***

Steps to reproduce.

Run with japanese folder name in the training-image folder

https://medium.com/@ageitgey/machine-learning-is-fun-part-4-modern-face-recognition-with-deep-learning-c3cffc121d78#.qxwjbkn93

OS and hardware information.

Operating system: osx
Torch version: [todo]
CPU architecture: mac 2015
GPU type (if using): 2015

**Comment by bamos** [comment]
Hi, thanks for contributing to OpenFace by filing an issue. We require all issues to follow [this issue template](https://github.com/cmusatyalab/openface/blob/master/.github/ISSUE_TEMPLATE.md) that is displayed by default when filing a new issue to make it easier to understand and debug. Please modify this issue to follow our issue template.

-Brandon.

**Comment by AlvarHHM** [comment]
I think I have found the problem here, I was running with japanese folder name. Once I change to english english name, it run without giving error

**Comment by bamos** [comment]
Strange error, thanks for letting us know. I think in some places the code assumes that directory names only use ASCII characters. Ideally this should be fixed. Minimally, OpenFace should output a better error message.

-Brandon.
