### ISSUE TITLE
torch.load('nn4.small2.v1.ascii.t7.xz','ascii') on windows error

### ISSUE THREAD

**Issue by honghuCode** [cmusatyalab/openface#185]
@bamos 
I install openface on windows  platform ,when i use torch.load('nn4.small2.v1.ascii.t7.xz','ascii') openface_server.lua tells me about..
 ![error](https://cloud.githubusercontent.com/assets/14934309/18031328/358d0250-6d0e-11e6-903f-18c94811c45c.jpg)
ps:I can run the following codes:
t = torch.Tensor(10)
torch.save('test-binary.t7', t)
t2 = torch.load('test-binary.t7')
torch.save('test-ascii.t7', t, 'ascii')
t3 = torch.load('test-ascii.t7', 'ascii')
t:eq(t2):all()
t:eq(t3):all()

Here is my modified openface_server.lua 
########
require 'torch'
require 'nn'
require 'dpnn'
require 'image'
require "socket"

--io.stdout:setvbuf 'no'
torch.setdefaulttensortype('torch.FloatTensor')
local cmd = torch.CmdLine()
cmd:text()
cmd:text('Face recognition server.')
cmd:text()
cmd:text('Options:')
cmd:option('-model', 'F://v1.ascii.t7', 'Path to model.')
cmd:option('-imgDim', 96, 'Image dimension. nn1=224, nn4=96')
cmd:option('-cuda', false)
cmd:text()
opt = cmd:parse(arg or {})
print(opt.model)
torch.load(opt.model,'ascii')
######

**Comment by bamos** [comment]
Hi @honghuCode - when you filed this, I thought it was a Windows issue, but you should uncompress the model with `unxz` before loading it with Torch. I'm not sure how to do it in Windows. I'm closing this issue for now, but please re-open or file another issue if you find any other Windows issues.

-Brandon.
