### ISSUE TITLE
Installation documentation for Mac should be updated for new dlib and better python handling

### ISSUE THREAD

**Issue by tilmans** [cmusatyalab/openface#187]
### Context of the issue.

The described steps for installing dlib and other dependencies are causing issues and are more complicated than needed.
### Suggested Changes
- brew install python
- brew install opencv
- brew install boost
- brew install boost-python
- brew install dlib
- Download current dlib 0.19
  *\* python dlib installation is simply "python setup.py install" in the dlib directory
- never use sudo, neither for pip nor for brew. Everything should be user writeable in brew

If you want I can create a pull request for the docs
### OS and hardware information.
- Mac 10.10

**Comment by bamos** [comment]
Hi @tilmans -sure, thanks. Can you send in a PR adding a new section `By hand (OSX)`? For now let's also keep the current sections as they are because they're still useful in Linux.

**Comment by PrasenjitGiri** [comment]
@tilmans I tried to follow your steps but I'm getting segmentation 11 error from import dlib
I have anaconda distro and I'm not sure what has happened now - as I tried to do everything without having a fair idea. 

Can you please make one with screenshots? list all of your dependencies ?

**Comment by AbuHelweh** [comment]
Hi am looking for a freelancer to develop for me a system using this tool. please let me know if you know
