### ISSUE TITLE
How to generate the verification threshold?

### ISSUE THREAD

**Issue by sun9700** [cmusatyalab/openface#190]
When a list of l2 distance is inferred from samples like in demo 2

Image 1	Image 2	Distance
Lennon 1	Lennon 2	0.763
Lennon 1	Clapton 1	1.132
Lennon 1	Clapton 2	1.145
Lennon 2	Clapton 1	1.447
Lennon 2	Clapton 2	1.521
Clapton 1	Clapton 2	0.318

How to calculate the threshold 0.99?
Could you please add the python code for threshold estimation?

**Comment by bamos** [comment]
Hi @sun9700 - you should base this threshold on your data. In the Lennon/Clapton example, you can compute the averages and then find the middle of them like this:

```
In [3]: s = np.mean((0.763,0.318))
In [4]: d = np.mean((1.132,1.145,1.447,1.521))
In [5]: m = s+(d-s)/2.
In [6]: (s,d,m)
Out[6]: (0.54049999999999998, 1.31125, 0.925875)
```

**Comment by MrXu** [comment]
Hi @bamos , thanks for the answer. Sorry I know the issue has been closed but I am wondering if there's other ways to better distinguish if the two faces belong to same person.
