### ISSUE TITLE
Not able to make openface in ubuntu 16.04 and opencv 2.4.10

### ISSUE THREAD

**Issue by aquibjaved** [cmusatyalab/openface#192]
I am installing OpenFace, steps are:
1. git clone https://github.com/TadasBaltrusaitis/OpenFace.git
2. cd OpenFace
3. mkdir build
4. cd build
5. cmake -D CMAKE_BUILD_TYPE=RELEASE ..
6. make 
In the 6th step **$ make** 
At the 65% I am getting an error:

In file included from /home/aquib/OpenFace/lib/local/LandmarkDetector/src/CCNF_patch_expert.cpp:59:0:
/home/aquib/OpenFace/lib/local/LandmarkDetector/./include/stdafx.h:8:31: fatal error: opencv2/imgproc.hpp: No such file or directory
compilation terminated.
lib/local/LandmarkDetector/CMakeFiles/LandmarkDetector.dir/build.make:62: recipe for target 'lib/local/LandmarkDetector/CMakeFiles/LandmarkDetector.dir/src/CCNF_patch_expert.cpp.o' failed
make[2]: *** [lib/local/LandmarkDetector/CMakeFiles/LandmarkDetector.dir/src/CCNF_patch_expert.cpp.o] Error 1
CMakeFiles/Makefile2:140: recipe for target 'lib/local/LandmarkDetector/CMakeFiles/LandmarkDetector.dir/all' failed
make[1]: *** [lib/local/LandmarkDetector/CMakeFiles/LandmarkDetector.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

How can I solve it.

**Comment by bamos** [comment]
Hi, this OpenFace project is unrelated to the one by @TadasBaltrusaitis
