### ISSUE TITLE
Get DepreciationWarnings

### ISSUE THREAD

**Issue by DanMossa** [cmusatyalab/openface#193]
### Context of the issue.

When I try to infer which person the image is closest to I get a few warnings.

```
/home/daniel/.local/lib/python2.7/site-packages/sklearn/lda.py:4: DeprecationWarning: lda.LDA has been moved to discriminant_analysis.LinearDiscriminantAnalysis in 0.17 and will be removed in 0.19
  "in 0.17 and will be removed in 0.19", DeprecationWarning)
/home/daniel/.local/lib/python2.7/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
/home/daniel/.local/lib/python2.7/site-packages/sklearn/grid_search.py:43: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. This module will be removed in 0.20.

```
### Expected behavior.

To get no warnings
### Actual behavior.

I received warnings about a few things being depreciated. I posted the warning message in the first section
### OS and hardware information.
- Operating system: Arch
- Torch version: Torch7
- CPU architecture: Intel i5-2500

**Comment by bamos** [comment]
Hi, I'll merge a PR if anybody updates how we use sklearn for this.

**Comment by Mikebarson** [comment]
I'm also getting the same warning. Is there a fix for this yet?

**Comment by Dgameman1** [comment]
@Mikebarson  , I don't think it's that much of a big deal right now but I have a feeling it will be eventually. So don't worry too much about it right now

**Comment by Dgameman1** [comment]
Pretty sure I fixed it

**Comment by qacollective** [comment]
When I was doing PR #231 as recently as January 2017 I also got the deprecation warning:

/usr/local/lib/python3.5/dist-packages/sklearn/lda.py:4: DeprecationWarning: lda.LDA has been moved to discriminant_analysis.LinearDiscriminantAnalysis in 0.17 and will be removed in 0.19
  "in 0.17 and will be removed in 0.19", DeprecationWarning)

I may try to fix this if I have time, but if someone else @Dgameman1 already knows where to find the dependent code it may be faster for him to look into it.
