### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by pythonanonuser** [cmusatyalab/openface#197]
### Context of the issue.
When running the webcam classifier demo, for example, I've noticed that the luajit process has some sort of a memory leak, in the sense that the memory keeps increasing over time, which I don't think should happen. I've tested this with other programs as well that call a forward pass of the net repeatedly, and have observed the same behavior. Perhaps we need to do some sort of a garbage collection somewhere? Though I don't think any new objects are being created repeatedly.

### Expected behavior.
Memory usage for the luajit process should stabilize. I've worked with other DNN libraries where repeated forward passes of a network are made for inference purposes and haven't observed the same behavior.

### Actual behavior.
Memory keeps increasing for the luajit process.

### Steps to reproduce.
Run the classifier_webcam.py demo and observe how much memory the luajit process consumes over time. 

### OS and hardware information.

+ Operating system: Ubuntu 16.04
+ Torch version: 7
+ CPU architecture: x86_64 (Intel i7 6500U)
+ GPU type (if using): Nvidia GeForce 940MX

**Comment by pythonanonuser** [comment]
Any update on this bug?

**Comment by bamos** [comment]
Hi @pythonanonuser - I'm not sure what's causing it, let me know if you find anything and I can merge in fixes if the leak is on our end.

-Brandon.

**Comment by pythonanonuser** [comment]
@bamos can you replicate the issue? Want to make sure it's not just a problem with my config before I go ahead and try to solve it.

**Comment by sidgan** [comment]
This might be because torch allocates memory on each available GPU. You can avoid this by prefixing the torch command with`CUDA_VISIBLE_DEVICES=x` where `x` is the gpuid.

Reference: https://github.com/torch/cutorch/issues/180

**Comment by pythonanonuser** [comment]
@sidgan my setup only has 1 GPU

**Comment by BKNio** [comment]
I am observing same behavior for dnn training procedure (trainnig/main.lua): Starting with 4105 Mib gpu memory and increasing every epoch. After ~16  epochs training procedure terminates with out of memory error. 

Ubuntu 16.04.3 LTS
Tesla P100

**Comment by xugaoxiang** [comment]
ubuntu 16.04 64bit with nvidia gtx 1070, memory leak.
