### ISSUE TITLE
is we forgot to find squre of value of distance between represent?

### ISSUE THREAD

**Issue by ninearif** [cmusatyalab/openface#199]
### Context of the issue.
file :  https://github.com/cmusatyalab/openface/blob/6343e404417cbe17db6139e62de691c3520148ce/demos/compare.py#L104

### Expected behavior.
I think it should print squared value of l2 distance between representations (which is dot product value).

### Actual behavior.
In line 104 we just print dot product without having any squared root. should we find square root for this value?

if this code is already work correctly, could you give me some explanation, please?

**Comment by bamos** [comment]
Hi @ninearif - see [our tech report](http://reports-archive.adm.cs.cmu.edu/anon/2016/CMU-CS-16-118.pdf). We use the **squared** L2 distance, which does not have the `sqrt`.

-Brandon.
