### ISSUE TITLE
Alignment: Only use three fiducial points

### ISSUE THREAD

**Issue by bamos** [cmusatyalab/openface#2]
We currently use dlib's pre-trained pose estimation models to detect 68 landmarks, but only use 3 points (eyes and tip of the nose) to perform an affine transformation on the images: http://blog.dlib.net/2014/08/real-time-face-pose-estimation.html

The alignment speed can be substantially improved if a new dlib model is trained that will only detect the 3 points we use.

**Comment by inspirit** [comment]
the alignment precision will drop due to lack of data in training/predicting. 
this will be a serious issue when the face is rotated/tilted

**Comment by bamos** [comment]
Thanks @inspirit - good intuition to have, but using 3 of the 68 landmarks seems wasteful.

**Comment by inspirit** [comment]
thats true from model size perspective. however runtime performance is around several (2-3) milliseconds for 68 points prediction. i think the good idea is to reduce the amount by excluding some points that will not affect overall model badly. for example you can easily remove outer shape points and only keep internal features

**Comment by bamos** [comment]
Closing since the alignment time is negligible.
