### ISSUE TITLE
getting the wrong person id in the callback

### ISSUE THREAD

**Issue by volkovmqx** [cmusatyalab/openface#20]
Hello,
Any idea what is causing this, AFAIK it's from server.py sending the -1 index instead of 0, in the meantime, the rendered picture is correct, while the detected faces IDs shown in the #peopleInVideo are wrong.

![ID Issue](http://i70.imgup.net/Screenshoteece.png)

**Comment by bamos** [comment]
I think this is being caused by faulty logic in `server.py`, starting at line 302: https://github.com/cmusatyalab/openface/blob/5ca23547fcae51e922de9e7e261fffec39f28e58/demos/web/server.py#L302

**Comment by bamos** [comment]
I'll fix this over the weekend
