### ISSUE TITLE
Age classification && building nn vs classifier

### ISSUE THREAD

**Issue by aviramberg** [cmusatyalab/openface#204]
Greetings, 
If I want to build an age or gender classification, I need to create a new nn, and train it on data with labels of  age, gender respectively?
Or can I use the the nn4.small2.v1 nn for example, and build a classifier of age/gender?

The given nn is good just for classification between different people?

Best regards,
Aviram

**Comment by bamos** [comment]
Hi Aviram, right, you'll probably need to train a new network, but the existing network may have some useful features that you could use.

-Brandon.

**Comment by aviramberg** [comment]
Hi, thank you for the answer.
Useful features like what?
Im sorry about all of the question, but I  just want to make sure that I
understand what is the purpose of the given nn.
Is just for classification of known people that i have trained?

Best,
Aviram

בתאריך 11 בנוב׳ 2016 08:18 PM,‏ "Brandon Amos" <notifications@github.com>
כתב:
