### ISSUE TITLE
Is this support for iOS app?

### ISSUE THREAD

**Issue by prakashidesign** [cmusatyalab/openface#205]
I want to develop the iOS and android app for facial recognition using OpenFace Lib. When i surf, came to know that openface lib is the best solution for facial recognition. 
Please let me know this lib will support for iOS and android devlopement.

Thanks.

**Comment by bamos** [comment]
Hi @prakashidesign - no, we don't currently support iOS or Android, but I'd be happy to link to a new project from our website if you or somebody else gets it running on iOS or Android and releases the code.

-Brandon.
