### ISSUE TITLE
ROC Curve for own datasets?

### ISSUE THREAD

**Issue by JotaroS** [cmusatyalab/openface#206]
### Drawing ROC curve for any datasets(not only LFW)
Hi,there. I'm planning to validate the accuracy for my own face dataset so I can check how openface can recognize people.
But currently it looks like validation script on this page 
( https://cmusatyalab.github.io/openface/models-and-accuracies/ ) 
is _only_ for LFW benchmark.
I thought it will be great if we can check the accuracy like this for our own dataset.

### I (locally) changed some of your script
looks like some of these need to be changed to do this.
1.
`lfw.py`

```python

#around loadPairs
def loadPairs(pairsFname):
    print("  + Reading pairs.")
    pairs = []
    with open(pairsFname, 'r') as f:
        for line in f.readlines()[1:]:
            pair = line.strip().split()
            pairs.append(pair)
    #assert(len(pairs) == 6000) --number of datasets can vary
    return np.array(pairs)

...
#around veryfyExp
N=400
N_FOLDS  = 2
def verifyExp(workDir, pairs, embeddings):
    print("  + Computing accuracy.")
    folds = KFold(n=N, n_folds=N_FOLDS, shuffle=False) #--number of datasets can vary
    thresholds = arange(0, 4, 0.01)
```
2.
We need `pairs.txt`. some auto-generated x-validation needed? 🎱 

3.
Format of image names and directory needs to be exactly same as LFW like this:
`Queen_Elizabeth_II_0001.jpg`

....maybe and so on.

Anyway, I'd be happy to evaluate my dataset, and hope we can add some useful scripts for this and of course I'd be happy to help this out.

Thanks.

--Jotaro

**Comment by bamos** [comment]
Hi Jotaro, sure, it would be great to have a generalized script to generate the ROC curve for any dataset. It could randomly generate the pairs and to stay consistent with the rest of OpenFace, the dataset should be separated into different directories for each person and the image names don't matter.

Also, if you are interested in classification accuracies, you might also be interested in taking some parts out of this script that created [Figure 10 in our TR](http://reports-archive.adm.cs.cmu.edu/anon/2016/CMU-CS-16-118.pdf): https://github.com/cmusatyalab/openface/blob/master/evaluation/lfw-classification.py

-Brandon.

**Comment by khadijakhaldi** [comment]
Hello, please why do we need the pairs.txt file ?
