### ISSUE TITLE
Running VGG Errors: inconsistent tensor size at /home/mohammad/torch/pkg/torch/lib/TH/generic/THTensorCopy.c:7

### ISSUE THREAD

**Issue by mohammad-py** [cmusatyalab/openface#207]
Hi, I've faced with this error when i ran my code
local numClass = 115;
local numSig = 72;
local numFeature = 25088;
print(numFeature);
result = torch.Tensor(numClass, numFeature, numSig);

line 47: local img = image.load( genRoot .. class ..'/'.. gen .. '.PNG');
line 48: result[{class, {}, totlaIndex}] = net:forward(img);

The error:
/torch/install/bin/luajit: inconsistent tensor size at /home/mohammad/torch/pkg/torch/lib/TH/generic/THTensorCopy.c:7
stack traceback:
	[C]: at 0x7f39b386aaf0
	[C]: in function '__newindex'
	featureExtraction.lua:48: in main chunk
	[C]: in function 'dofile'
	...mmad/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x55950b353470

Could you help me how to solve this?

**Comment by bamos** [comment]
Hi, thanks for your message. Somebody on our mailing list might be able to help you with this, but I am closing this issue because it does not seem to be a bug in our examples or API.

-Brandon.
