### ISSUE TITLE
Question: Does OpenFace Work For Django? 

### ISSUE THREAD

**Issue by Mikebarson** [cmusatyalab/openface#208]
Hi! I'm trying to implement face recognition for a website that I'm working on. 

I tried doing:
import subprocess
import numpy as np 
from PIL import Image
import glob
import cv2
import re

def align_faces(inputDir, outputDir):
	os.system("./util/align-dlib.py"+ " " + inputDir + " " + "align outerEyesAndNose"+ " " + outputDir + " " +"--size 96")

def generate_embeddings_files(path, company):
	os.system("./batch-represent/main.lua -outDir"+" "+path+" "+"-data ./aligned-images/"+company+"/")

def train_embeddings(company):
	os.system("./demos/classifier.py train ./generated-embeddings/"+company+"/")

def predict_face(company, image_path):
	conf = subprocess.check_output(["./demos/classifier.py", "infer", "./generated-embeddings/"+company+"/"+"classifier.pkl", image_path])
	return conf

After refreshing my local server it worked perfectly. However after uploading it to Google Cloud Server the images won't show up. 

I'm sorry for the really broad question, please ask for my clarification below. I'll answer them the best that I can. Thanks!

**Comment by bamos** [comment]
Hi, thanks for your message. Somebody on our mailing list might be able to help you with this, but I am closing this issue because it does not seem to be a bug in our examples or API.

-Brandon.

**Comment by Mikebarson** [comment]
Where will I find your mailing list?

**Comment by bamos** [comment]
Hi @Mikebarson - it's here: https://groups.google.com/forum/#!forum/cmu-openface

-Brandon.

**Comment by Mikebarson** [comment]
@bamos Alright. Thanks!

**Comment by Mikebarson** [comment]
@bamos Hey! Can I ask you a question?
