### ISSUE TITLE
Build does not work on Ubuntu 16

### ISSUE THREAD

**Issue by joov** [cmusatyalab/openface#211]
### Context of the issue.
The build of opencv-dlib-torch fails with ubuntu 16.
Dependencies to libqt4-core and libqt-gui cannot be resolved

I detected this while doing an arm-based (raspberry starting from armv7/armhf-ubuntu base image on hypriot-Os) build but it seems to be a general problem: 
http://askubuntu.com/questions/766615/how-to-install-libqt4-core-and-libqt4-gui-on-ubuntu-16-04 which might contain a solution already

The operating system dependencies are in https://raw.githubusercontent.com/torch/ezinstall/master/install-deps which should be changed
Thanks

**Comment by pythonanonuser** [comment]
I was able to get it running on 16.04. You can try manually calling `find_package` for the qt packages that are giving you trouble in CMakeLists.txt

**Comment by qacollective** [comment]
apt-get install libqtgui4 libqtcore4
