### ISSUE TITLE
How to build this library using jhbuild in my project, Please help !!

### ISSUE THREAD

**Issue by Dhvanish1299** [cmusatyalab/openface#214]
### Context of the issue.
[I want to build this library in my project using jhbuild but there is no cmake file so how can i build in my project using jhbuild?]

### Expected behavior.
[There is no issue of result but i want to build this in my project]

### Actual behavior.
[I have build this library externally and woking fine but i am not able to build in my project using jhbuild]

### Steps to reproduce.
[1)
I have successfully clone openface repository from github and setup torch,dlib and it's all depedancy and get two face comparison result successfully.
2)
Now, I want to build this library on project using jhbuild but i am unable to get idea how i can do, so can anybody please to give me idea how to do it? ]

### OS and hardware information.

+ Operating system: [Virtual - XUbantu 16.04]
+ Torch version: [git clone https://github.com/torch/distro.git ~/torch --recursive]
+ CPU architecture: [i3-x86/8gbRAM]
+ GPU type (if using): [todo]

@bamos @melgor

**Comment by bamos** [comment]
Hi, we don't have a cmake build file, see the setup portion on our website for how we set this up. I'll close this issue since this isn't supported, but somebody on our mailing list might also be able to help you.

-Brandon.

**Comment by Dhvanish1299** [comment]
Actually I am new so was stuck but thanks - Brandon @bamos  for giving valuable comment.
