### ISSUE TITLE
ImportError: numpy.core.multiarray failed to import

### ISSUE THREAD

**Issue by IrumZahraAwan** [cmusatyalab/openface#215]
['/usr/local/lib/python2.7/dist-packages/numpy']
Traceback (most recent call last):
  File "faceRec5DEC.py", line 2, in <module>
    import numpy, cv2, sys, os
  File "/usr/local/lib/python2.7/dist-packages/numpy/__init__.py", line 163, in <module>
    from . import random
  File "/usr/local/lib/python2.7/dist-packages/numpy/random/__init__.py", line 99, in <module>
    from .mtrand import *
  File "mtrand.pyx", line 149, in init mtrand (numpy/random/mtrand/mtrand.c:37623)
  File "/home/irum/Desktop/Face-Recognition/thakarrecog/threading.py", line 6, in <module>
    import logging
  File "/usr/lib/python2.7/logging/__init__.py", line 201, in <module>
    _lock = threading.RLock()
AttributeError: 'module' object has no attribute 'RLock'

numpy libraray was working fine yesterday but today it has got the above issue

numpy and its dependencies are already installed on my laptop.

i have tried uninstall , reinstall and updating the numpy but none of it has worked. i am still getting the error. i do not have any idea what caused this error. its the same code that was working yesterday and now its giving me errors.

i am working on python with open CV for faec detection and recognition.
Operating system: linux

**Comment by lucascorrea10** [comment]
Do you solved this problem? If yes, how? I'm in the same problem right now...

**Comment by qacollective** [comment]
What changed on your computer between the day it was working and the day it wasn't?
Computers don't just change behaviour with no event causing it - so finding that event will be key.  Perhaps a software update performed overnight or installing another seemingly unrelated package?

Failing to find the issue, you may be able to get it working by using a technology that does a good job of isolating your python environment like virtualenv or docker.  There are 2 docker build files in the OpenFace repo for this.  Virtualenv has lots of documentation online you can find with Google in case you don't already know about it.

If you have time to learn about Docker, I'd say a simple re-build in a docker container would be very reliable and most likely to continue working for you into the future.
