### ISSUE TITLE
Set up by hand on Osx 

### ISSUE THREAD

**Issue by xin-xinhanggao** [cmusatyalab/openface#216]
Hello, I come to use openface from your blog http://bamos.github.io/2016/08/09/deep-completion/.

Under Osx 10.12
I install opencv and dlib  and torch successfully.
After that, I install findutils and coreutils then type python setup.py install
I get information like this:
running install
running build
running build_py
running install_lib
running install_egg_info
Removing /usr/local/lib/python2.7/site-packages/openface-0.2.1-py2.7.egg-info
Writing /usr/local/lib/python2.7/site-packages/openface-0.2.1-py2.7.egg-info

Then I type ./openface/util/align-dlib.py ./raw align innerEyesAndBottomLip ./aligned --size 64
get that 
**Intel MKL FATAL ERROR: Cannot load libmkl_intel_thread.dylib.**
Thanks for your help.

**Comment by xin-xinhanggao** [comment]
The docker seems work normally, but I am a new comer to docker. Would you please tell me how can I use docker to align my images?
```
docker pull bamos/openface
docker run -p 9000:9000 -p 8000:8000 -t -i bamos/openface /bin/bash
cd /root/openface
./demos/compare.py images/examples/{lennon*,clapton*}
./demos/classifier.py infer models/openface/celeb-classifier.nn4.small2.v1.pkl ./images/examples/carell.jpg
./demos/web/start-servers.sh
```

**Comment by qacollective** [comment]
Hello @xin-xinhanggao,

Did you try to type your original command after entering the docker container command prompt?  Like:

> sudo docker pull bamos/openface
> docker run -p 9000:9000 -p 8000:8000 -t -i bamos/openface /bin/bash
> ./openface/util/align-dlib.py ./raw align innerEyesAndBottomLip ./aligned --size 64

**Note:** if you've already run the first command, you won't have to run that again.

**Comment by xin-xinhanggao** [comment]
Everything is OK, thank you! @qacollective
