### ISSUE TITLE
How is the facial recognition works?

### ISSUE THREAD

**Issue by Ripppah** [cmusatyalab/openface#217]
Hi,

I saw the facial recognition demo video on youtube. So I saw you first click the train to train the face and then it could recognize the people. So how does this exactly works? How did you use your pre-trained model to train new faces and how are new face class added to the original model? I don't really understand the code there. Can anyone just give me quick explanation on that? 

Thanks!

**Comment by bamos** [comment]
Hi @Ripppah - see our tech report [here](http://reports-archive.adm.cs.cmu.edu/anon/2016/CMU-CS-16-118.pdf) for details about how OpenFace and that demo works. In that demo, we use an SVM to classify faces and re-train it as new frames are added.

-Brandon.

**Comment by Ripppah** [comment]
So do you have to train on the whole dataset whenever the new frames are added? Will that be possible that you based on the pre-trained model, you get information from there and add person class? For example on the demo, you already trained two people, will that be possible add the third person without training the whole dataset again? Otherwise it's gonna took a while as the dataset is getting larger.

**Comment by bamos** [comment]
Right, you have to re-train the classifier (but not the neural network) on the dataset you want to classify. For 100's to 1000's of images, re-training an SVM like we use in our examples is very fast. If you want to scale beyond this, you can post on our or another related mailing list and somebody else might have some advice.

**Comment by Ripppah** [comment]
Thank you for the reply! I'll try your SVM here. To be honest, I don't really know how to solve this problem. Only the re-train seems to be the best way to do that. I was thinking that if there is anyway that computer can remember the faces that it has already trained and learn the new face. It will be much faster if it can but It seems no because once the new faces are added, everything changes. 

I'll keep following you guys. Which other mailing list you are talking about here?
