### ISSUE TITLE
Question: How to Integrate OpenFace with Django 

### ISSUE THREAD

**Issue by Mikebarson** [cmusatyalab/openface#218]
Hi. I've already asked this question before here: 
https://groups.google.com/forum/#!topic/cmu-openface/8c72RC_zSIM
and here:
http://stackoverflow.com/questions/41302234/openface-with-django

I've imported the files and folders necessary to train and predict the faces. There was return with the confidence level with the photo of the image. However when uploading it to the Google Cloud Platform Server, the result was different. There was no confidence level and no photo returned. 

You can check out those links for more detail. For any more clarifications please comment below. 

Thanks!

**Comment by bamos** [comment]
Hi @Mikebarson - I've responded on your mailing list post, let's continue the discussion there.

-Brandon.

**Comment by Ripppah** [comment]
@Mikebarson 

For Django, how do you setup the database? embedding is type of numpy array. Also, in Django, how to call all the functions? I am also trying to write a web app on Django of the demo but I am really new to Django. Could you give some instructions?

**Comment by Mikebarson** [comment]
Hi @Ripppah! Sure!  

Setting up the database really depends on what database you're using. It's recommended you use Postgresql. Here are some [details](https://djangogirls.gitbooks.io/django-girls-tutorial-extensions/content/optional_postgresql_installation/) about how to set that up. I can't teach you everything here. You'll need to get into some basics of Django here's the [link](https://tutorial.djangogirls.org/en/). That tutorial should help get familiar with Django. After you've done that, reply to me again and hopefully I can help you call the functions for OpenFace.

Side Note:
My Django project involved taking a bunch of pictures from the database, reading them, training them, and then recognizing another set of pictures from the database with the same people using the trained embeddings. This worked quite perfectly in my local PC. The result is that the pictures read will be displayed together with the confidence value. But when deploying it to a web  (the one I'm using is Google Cloud Platform) no images show up, and no confidence value. I've been trying to contact Bamos about how to fix this, but so far no solution has been found.

**Comment by Ripppah** [comment]
Thanks for replying me @Mikebarson !

I wrote a simple django code just for having cv2.videoCapture work. However, there is no error but the process just stuck there forever. Like cam is not open but it's trying to open forever. Do you have any solution on that?

**Comment by Mikebarson** [comment]
I'm afraid not. However, perhaps you need JS to communicate with the browser that you want to access the camera.

**Comment by Ripppah** [comment]
I cannot find bug. Otherwise there should be error. However, in my backend, if I just open local images instead of open the videoCapture, it works.

**Comment by Ripppah** [comment]
hey @Mikebarson , i think i have successfully applied some algorithms in my Django application. Right now I'm using opencv so every time i still open the cam locally even in the web app. I have already added the getUserMedia to the javascript and also video window is on my html page. So how can I work on the video from live streaming on web app? Like apply all opencv functions? Thanks

**Comment by Mikebarson** [comment]
@Ripppah so now, are you trying to detect, train, and recognize the faces on live video stream?

**Comment by Ripppah** [comment]
Training can be done in the original backend. But I don't know how to get the frame from live video stream like in the demo. Since I'm not familiar with socket. Just wonder what's your solution to that since we both use Django.

**Comment by Mikebarson** [comment]
@Ripppah Currently I don't have any solution that yet. I'm more focused on trying to do the training in the backend and then produce the results to the frontend. This is also the problem that I'm currently facing right now. Doing things locally works but when uploading it to a server things don't go so well. I'm not entirely sure how to do things with what you are trying to do. Perhaps start [here](https://www.fullstackpython.com/websockets.html). That should get you started with web sockets.

**Comment by Ripppah** [comment]
@Mikebarson Will anything in Ajax gonna do the same thing as the web socket do?
