### ISSUE TITLE
docker build fail

### ISSUE THREAD

**Issue by sag911** [cmusatyalab/openface#219]
Hi Guys,
 At step 6,  get-models.sh seems to be missing. I get this error.

/bin/sh: 1: ./models/get-models.sh: not found
The command '/bin/sh -c cd ~/openface &&     ./models/get-models.sh &&     pip2 install -r requirements.txt &&     python2 setup.py install &&     pip2 install -r demos/web/requirements.txt &&     pip2 install -r training/requirements.txt' returned a non-zero code: 127

**Comment by jessejohnson** [comment]
Hey @katticot how did you get round this issue? I'm having the same problem

**Comment by washizzle** [comment]
@katticot, @jessejohnson I am having the same issue at the moment. Were you able to solve it? If so, do you remember how?

**Comment by jessejohnson** [comment]
@washizzle I don't remember what I did with it, or if I continued to use it. Vaguely remember being able to run it though. Sorry.

**Comment by washizzle** [comment]
I managed to solve it by removing it from the dockerfile and doing it in the command line after "docker run -p 9000:9000 -p 8000:8000 -t -i openface /bin/bash" (in the setup guide).

**Comment by jessejohnson** [comment]
@washizzle yes, that's probably it. I came back to tell you I must have run the command in the `Dockerfile`'s shell, after going over my own `Dockerfile`, when I saw your reply. Glad you found it.
