### ISSUE TITLE
web demo and python code

### ISSUE THREAD

**Issue by Ripppah** [cmusatyalab/openface#220]
Hi,

I am new to web design. So how did you connect your face recognition python code to the web page? For example, when you click the train button, your training function runs. How does this happen? Which part should I look into in your web code?

Thanks!

**Comment by bamos** [comment]
Hi @Ripppah - the web demo uses websockets to communicate between the browser and server. See [openface-demo.js](https://github.com/cmusatyalab/openface/blob/master/demos/web/js/openface-demo.js) for the browser js code and [websocket-server.py](https://github.com/cmusatyalab/openface/blob/master/demos/web/websocket-server.py) for the server code.

-Brandon.

**Comment by Mikebarson** [comment]
@bamos How do you access the localhost server for this demo? I've tried going to localhost:8000 on different browsers while the websocket server is running but nothing appears.

**Comment by tonphilip** [comment]
Hi @bamos - I am new to coding.  Iwas interested in face rec. I was checking the websocket-server.py .So I saw the chats regarding Python 3. Do you have the latest  websocket-server.py which I can run ?. I have Python 3.6. Will it run direct or need some additional systems ?.

**Comment by tonphilip** [comment]
I am looking for a basic program for face rec in python with web cam .
