### ISSUE TITLE
Align eyes_1 option

### ISSUE THREAD

**Issue by Tiaguituh05** [cmusatyalab/openface#222]
Hello,
So I took a peek at align-dlib.py and although it as a align option eyes_1 ( which I hope it gives me a aligned image of only the eyes), the function is not working, I belive its because the eyes_1 option is not on the landmarkMap.
landmarkMap = {
        'outerEyesAndNose': openface.AlignDlib.OUTER_EYES_AND_NOSE,
        'innerEyesAndBottomLip': openface.AlignDlib.INNER_EYES_AND_BOTTOM_LIP

Why the code as a option if its not working, or what Im doing wrong ?
If its really a problem in the code, is there any1 that knows how to do it?
My goal is to get something like the image attached
Thank you
![aaron_guiel_0001_l](https://cloud.githubusercontent.com/assets/23557457/21717794/3c7dd6fc-d40b-11e6-8b51-bb1cc001ee5d.jpg)

**Comment by bamos** [comment]
Hi, `align-dlib` doesn't do eye alignment like that.

-Brandon.

**Comment by Tiaguituh05** [comment]
Sorry, do you know any other way I could do it?
