### ISSUE TITLE
Webcam interaction

### ISSUE THREAD

**Issue by Ripppah** [cmusatyalab/openface#225]
Hi,

So locally, I use the cv2.VideoCapture to load video from webcam. How to change that when I access webpage? I use getUserMedia to open the webcam when I on the page, but how can I still process the video with opencv?

Thanks

**Comment by bamos** [comment]
Hi @Ripppah - somebody on our mailing list might have a better idea. You can try doing something similar to our web demo that sends frames to a Python server.

-Brandon.
