### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by PVNathan** [cmusatyalab/openface#226]
### Context of the issue.
[Provide more detailed introduction to the issue itself and why it is relevant]

### Expected behavior.
[Describe what you would expect to have resulted from this process.]

### Actual behavior.
[Describe what you currently experience from this process, and thereby explain the bug.]

### Steps to reproduce.
[Present a minimal example and steps to produce the issue.]

### OS and hardware information.

+ Operating system: [todo]
+ Torch version: [todo]
+ CPU architecture: [todo]
+ GPU type (if using): [todo]

**Comment by PVNathan** [comment]
Hi is the openface code under the CMU license or can someone use it for a commercial product, the latter supported by Apache license? Thanks

**Comment by bamos** [comment]
Hi, OpenFace is licensed under the Apache license and you can use it in a commercial product if you uphold the terms of the Apache license.

-Brandon.
