### ISSUE TITLE
Is openface prone to classify strangers as trained people?

### ISSUE THREAD

**Issue by jrubyuncle** [cmusatyalab/openface#227]
I use openface these days and learn much form the code.

The result is pretty good for trained people. But for strangers, who are not trained into the classifier in advance, the result is not completely as expected.

For strangers, either outcome is expected:
1.  Openface reports strangers as _unknown_.
2.  Openface classifies strangers as any trained person with _low_ confidence such that we could choose a threshold to distinguish trained people or untrained ones.

However, in our test, >60% strangers are classified as one of trained people with high confidence (>0.9). With those high confidences, it is hard to find a threshold to identify strangers.

Is it the characteristics of current openface design/implementation to classify strangers to trained persons? Or any extra preprocess is needed for reducing the confidence level for strangers?

Thanks a lot.

**Comment by bamos** [comment]
Hi, we have an ongoing discussion of this in issue #144 that you are welcome to join in on. Unknown person detection is still unsolved in OpenFace.

-Brandon.
