### ISSUE TITLE
Use openface with CUDA

### ISSUE THREAD

**Issue by Ormgair** [cmusatyalab/openface#228]
### Context of the issue.
Hello to all! I am new in CUDA and I want to know, is it possible to use openface with CUDA for faster face recognition? What I need to do for that? 

### OS and hardware information.

+ Operating system: Ubuntu 14.04
+ Torch version: Torch7
+ CPU: AMD ATHLON-64 X2 3800+
+ GPU: GeForce GTX 550 Ti

**Comment by bamos** [comment]
Yes, for the representation, our batch-represent script and TorchNeuralNet class have cuda options. The detection and alignment parts don't currently have CUDA acceleration.

-Brandon.

**Comment by mbaroody** [comment]
Hello,  I see the cuda options, but no luarocks installation of 'cutorch' or 'cunn' in the Dockerfile. Does that mean that I have to rebuild with those added to Dockerfile? Or am I missing something?
