### ISSUE TITLE
CLI for training and classifying without expertise

### ISSUE THREAD

**Issue by tom-adsfund** [cmusatyalab/openface#23]
The web demo seems to have a similar function already, but I'd like a command-line interface to train and classify people like in the web demo.

This would allow easy integration into other apps, and inevitably lead more people to use this system.

Example interface:

openface_train img.png Name
openface_train *.png Name
openface_classify img.png [output: Name 0.63]

Thanks for the work, and the choice of a good license.

**Comment by bamos** [comment]
Hi @tom-adsfund - thanks for the report. Demo 3 provides [demos/classifier.py](https://github.com/cmusatyalab/openface/blob/master/demos/classifier.py) to train an SVM from a directory of images. The model is exported and the `infer` mode predicts the person in a new image.

I'll add a few more details to the README about using the `train` mode of this to build a new classifier:

1. Align a directory of images organized in subdirectories by their names with `util/align-dlib`
2. Extract the features from aligned images with `batch-represent`
3. Train a classifier on the features with `demos/classifier.py train`, which outputs a model
4. Give the model to `demos/classifier.py infer` to predict who a new image belongs to.

**Comment by kaikuehne** [comment]
Hey @bamos, I tried to do this and have now a directory structure with the aligned photos.
Now I have another question regarding point 2. How do I run batch-represent?
Using luajit or th? I get no output when I run it:

```
luajit batch-represent/batch-represent.lua
```

I tried also -help and --help. Thanks again!

**Comment by bamos** [comment]
Hi @kaikuehne 

+ [ ] Thanks, I'll clarify how `batch-represent` works in the docs.

The default OSX versions of many command-line tools are incompatible with the GNU variants that most Linux distros use. The prefixed `g` stands for the GNU variants in OSX, which can be installed with `findutils` (for `gfind`) and `coreutils` (for `gwc`) from brew or macports. Most people keep the prefix `g` because some command-line and system program for OSX might depend on the non-GNU version of the utilities.

+ [ ] Will also add this to the docs.

-Brandon.

**Comment by kaikuehne** [comment]
Thanks!

**Comment by tom-adsfund** [comment]
@bamos If there's a concrete example of the whole process as described here then that would be sufficient to resolve this issue. Thanks again.

**Comment by kaikuehne** [comment]
Hi @tom-adsfund,
I took a few notes while installing and using the classifier.
Maybe they are of use in the meantime: https://gist.github.com/kaikuehne/d027a0ff3aa353a7322a

**Comment by tom-adsfund** [comment]
@kaikuehne Wow that's excellent. I use Linux, but it should be easy enough to transfer. Thanks.

**Comment by bamos** [comment]
I've added references to `findutils` and `coreutils` to the docs for native OSX execution and have clarified the instructions for training. Happy to merge in or reference any further suggestions if the docs aren't clear anywhere.

-Brandon.
