### ISSUE TITLE
Any plans for pytorch? 

### ISSUE THREAD

**Issue by pythonanonuser** [cmusatyalab/openface#230]
Python version of torch was released recently: http://pytorch.org/

Any plans to move openface over? Might make installation and development tasks easier in the future now that everything is in Python instead of Lua.

**Comment by bamos** [comment]
Yes, I'll merge a PR adding PyTorch support

**Comment by NkululekoThangelane** [comment]
A Pytorch implementation would make installation process much simpler.

**Comment by stassop** [comment]
@bamos Has it been added?
