### ISSUE TITLE
wrong prediction for very small number of images

### ISSUE THREAD

**Issue by ricking06** [cmusatyalab/openface#232]
I used your comparison demo on my own images with pretty good success.

But when im using the classifier demo. it just classifies wrong images. 
Fun Fact : It recognizes wrong image even if im trying to classify same image i trained with!

*By wrong I mean they each  have low confidence < .5 but its wrong image*

I tested it with my images, and two of my friend's image. 
Each had 4 images (selfies) ( we also posed almost same in all images).

Total i used 12 images.

Why it recognizes wrong BUT compares correctly ? i dont get it.

Do i need more images  like 1000 of em for each person? 

I used `1..4` instead of `8` 

http://cmusatyalab.github.io/openface/demo-3-classifier/#1-create-raw-image-directory

P.S. I know negligible about Maths side of DNN and Machine Learning

**Comment by bamos** [comment]
Hi @ricking06 - it's great to hear you're trying out OpenFace. For cases like this, you'll have to experiment more with the datasets and take a look at the embeddings and classifiers to see why you're getting bad performance. If you are ever interested in detecting unknown users, it's an active issue we're trying to solve. Feel free to join in on the discussion in #144.

-Brandon.

**Comment by akirapix** [comment]
Hi @ricking06 @bamos ,
same issue for me. I  tried to train my pickle model with 6 persons and 2 images for each folder (so i have 12 images like you).

I also tried different classifier type, obtaining every time a 1.0 accuracy with a wrong person.

Every test was made using ./classifier.py with one of the photos used to generate pkl file itself.

It would be great to have an advice or and hint.

Thank you all
