### ISSUE TITLE
Extending/Updating Created Classifier from Trained Models without previous images

### ISSUE THREAD

**Issue by ricking06** [cmusatyalab/openface#233]
Hi,

Lets say i have n images of each person ( total 5 person)

```
person 1
  -img1.jpg
  -img2.jpg
  ...
.....
person 5
   - img1
   ...
```

After creating model from these images i deleted those images (raw+ align)

After that I feel like updating the previously created `pickle` model with some new images along with some (new +old) person .

```
person 1
  -img1_new.jpg
  -img_new2.jpg
  ...

person 2
  -img1_new.jpg
  -img_new2.jpg
  ...

person 7
  -img1.jpg
  -img.jpg
  ...
person 6
   - img1
   -img2
   -img3
   ...
``` 

If i again recreate the classifier then the previously made model will be lost.  
I also dont have older images.
Can i update the model with new images on top of old images ?

**Comment by bamos** [comment]
Hi @ricking06 - you can try some of sklearn's incremental training methods: http://scikit-learn.org/stable/modules/scaling_strategies.html

-Brandon.
