### ISSUE TITLE
docker pull issue

### ISSUE THREAD

**Issue by wenmingli** [cmusatyalab/openface#237]
When I use docker to pull the bamos/openface, I meet this problem:
root@ubuntu:~# docker pull bamos/openface
latest: Pulling from bamos/openface
c690013628ea: Pulling fs layer 
4ed7fa155491: Layer already being pulled by another client. Waiting. 
f026f61f9346: Pulling fs layer 
6ad06db455ac: Pulling fs layer 
7f5f3700660b: Pulling fs layer 
646470f52dd8: Pulling fs layer 
7cf66292f88d: Pulling fs layer 
5990336caad5: Pulling fs layer 
54c62b858db3: Pulling fs layer 
a85b5ffb487b: Downloading      0 B/36.98 MB
901fd6c16ad5: Pulling fs layer 
80ed4fe859ea: Pulling fs layer 
9fc6e3fa9175: Pulling fs layer 
cea86fd90f0b: Already exists 
b122d4ef87dc: Already exists 
3fef90246eb1: Already exists 
0e23078ccd33: Already exists 
5513002504a5: Already exists 
fa6123def274: Already exists 
Pulling repository bamos/openface
FATA[0141] Tag latest not found in repository bamos/openface 
 
so, I do it to solve this problem, but 
root@ubuntu:~# docker pull bamos/ubuntu-opencv-dlib-torch
Pulling repository bamos/ubuntu-opencv-dlib-torch
FATA[0020] Tag latest not found in repository bamos/ubuntu-opencv-dlib-torch 

How can I do with it?Thanks!

**Comment by Jacktofine** [comment]
I think your Docker setup is not official. Normally, the images of bamos/openface was in library of Docker Hub which contain most of images you need, so when you use the command " docker pull bamos/openface ", the images will download from the Docker Hub.It's my own ideas, i hope this can help you.
download site :[https://docs.docker.com/engine/getstarted/step_one/](url)
Docker Hub :[https://www.docker.com/products/overview#/docker_hub](url)
