### ISSUE TITLE
I run websocket-server.py, I found those problems below. However, I already installed all dependencies. 

### ISSUE THREAD

**Issue by dongdongqin** [cmusatyalab/openface#238]
/usr/bin/python2.7 /home/dongdongqin/PycharmProjects/openface/demos/web/websocket-server.py
2017-02-18 09:29:21+0800 [-] Log opened.
2017-02-18 09:29:21+0800 [-] WebSocketServerFactory starting on 9000
2017-02-18 09:29:21+0800 [-] Starting factory <autobahn.twisted.websocket.WebSocketServerFactory object at 0x7fd9048b0910>
/home/dongdongqin/torch/install/bin/lua: ...e/dongdongqin/torch/install/share/lua/5.2/trepl/init.lua:389: module 'dpnn' not found:No LuaRocks module found for dpnn
	no field package.preload['dpnn']
	no file '/home/dongdongqin/.luarocks/share/lua/5.2/dpnn.lua'
	no file '/home/dongdongqin/.luarocks/share/lua/5.2/dpnn/init.lua'
	no file '/home/dongdongqin/torch/install/share/lua/5.2/dpnn.lua'
	no file '/home/dongdongqin/torch/install/share/lua/5.2/dpnn/init.lua'
	no file '/home/dongdongqin/torch/install/lib/lua/5.2/dpnn.lua'
	no file '/home/dongdongqin/torch/install/lib/lua/5.2/dpnn/init.lua'
	no file './dpnn.lua'
	no file '/home/dongdongqin/.luarocks/lib/lua/5.2/dpnn.so'
	no file '/home/dongdongqin/torch/install/lib/lua/5.2/dpnn.so'
	no file '/home/dongdongqin/torch/install/lib/dpnn.so'
	no file '/home/dongdongqin/torch/install/lib/lua/5.2/loadall.so'
	no file './dpnn.so'
stack traceback:
	[C]: in function 'error'
	...e/dongdongqin/torch/install/share/lua/5.2/trepl/init.lua:389: in function 'require'
	...in/PycharmProjects/openface/openface/openface_server.lua:20: in main chunk
	[C]: in function 'dofile'
	...gqin/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: in ?

**Comment by sidgan** [comment]
You need to install `dpnn` by: `luarocks install dpnn`.

**Comment by bamos** [comment]
Thanks @sidgan! You're right, @dongdongqin needs to install `dpnn`.
