### ISSUE TITLE
Facing issues in forwardPath

### ISSUE THREAD

**Issue by Prithviraj7** [cmusatyalab/openface#24]
I am trying to use the exemplar code given under 'Usage' in the readme document.  This is the code which I'm using.
``` python
parser.add_argument('--dlibFaceMean', type=str, help="Path to dlib's face predictor.",
                    default=os.path.join(dlibModelDir, "mean.csv"))
parser.add_argument('--dlibFacePredictor', type=str, help="Path to dlib's face predictor.",
                    default=os.path.join(dlibModelDir, "shape_predictor_68_face_landmarks.dat"))
parser.add_argument('--networkModel', type=str, help="Path to Torch network model.",
                    default=os.path.join(openfaceModelDir, 'nn4.v1.t7'))
parser.add_argument('--imgDim', type=int,
                    help="Default image dimension.", default=96)
parser.add_argument('--cuda', action='store_true')
args = parser.parse_args()
print args

align = NaiveDlib(args.dlibFaceMean, args.dlibFacePredictor)
print args.dlibFaceMean
print args.dlibFacePredictor
net = openface.TorchWrap(args.networkModel, imgDim=args.imgDim, cuda=args.cuda)
print align
img = cv2.imread('Andrew-Ng-Photo.jpg')
bb = align.getLargestFaceBoundingBox(img)
alignedFace = align.alignImg("affine", args.imgDim, img, bb)

print args.imgDim
print alignedFace.shape
print bb
rep1 = net.forwardImage(alignedFace)
```
 
But I'm getting error in this line.
<code>rep1 = net.forwardImage(alignedFace)</code>

This is the error:

```
 rep1 = net.forwardImage(alignedFace)
  File "/home/prithviraj/openface/openface/__init__.py", line 80, in forwardImage
    rep = np.array(self.forwardPath(t))
  File "/home/prithviraj/openface/openface/__init__.py", line 73, in forwardPath
    return [float(x) for x in self.p.stdout.readline().strip().split(',')]
ValueError: could not convert string to float:
```
I traced it back and found that the problem is in <code>/openface/openface/__init.py__</code>. 

So I decided to modify the forwardPath and forwardImage functions in __init.py__.
``` python
def forwardPath(self, imgPath):
        print imgPath
        self.p.stdin.write(imgPath + "\n")
        print [(x) for x in self.p.stdout.readline().strip().split(',')]
        return [float(x) for x in self.p.stdout.readline().strip().split(',')]

    def forwardImage(self, rgb):
        print rgb.shape
        t = '/tmp/openface-torchwrap-{}.png'.format(
            binascii.b2a_hex(os.urandom(8)))
        cv2.imwrite(t, rgb)
        rep = np.array(self.forwardPath(t))
        os.remove(t)
        return rep
   ``` 

Here, I found out that this line 
``` python 
print [(x) for x in self.p.stdout.readline().strip().split(',')]
 ``` 
returns an empty list, which results in the error. Please help me with this isssue.
TIA

**Comment by bamos** [comment]
Hi @Prithviraj7 - are you able to run any of the example code on the test images provided? What is the output of: `./demos/compare.py images/examples/{lennon*,clapton*}`

**Comment by bamos** [comment]
A few comments on the code you added - a bounding box might not be found in an image, and then a face within a bounding box might fail to be aligned. In both cases, `None` is returned. Since you've added print statements, I assume you`ve checked this and that something else is happening, but I've filed #25 to go through the Python functions and make there aren't weird errors if `None` is passed into any of the functions.

Also in  your `forwardPath`, the `print` and `return` statements won't be the same since they're reading different lines from stdout.

**Comment by Prithviraj7** [comment]
alignedFace.shape and bb did not return none. 
Anyway, I tried re-sizing the rectangular image to a square image (96,96) and ran it again. This time, I didn't get an empty list . 

But the program has been running for about 20 minutes, yet I haven't got the output. Is it supposed to take this much time, as I'm using a pre-trained model ('nn4.v1.t7') ?

**Comment by bamos** [comment]
Hi @Prithviraj7 - correct, as the demos show, the aligned face bounding box needs to be resized correctly before being passed to `forwardImage`. I'll add a check for this. Otherwise, is this issue resolved for you?

What program is taking over 20 minutes? The one with incorrect sizes?

**Comment by Prithviraj7** [comment]
Yes the issue is resolved now. 
The program was taking a long time as the print and return statements were not the same (as you had mentioned earlier). However I commented out that print statement in <code>forwardPath</code> , and the program is running smoothly.

Thanks

**Comment by bamos** [comment]
Thanks, good to hear!
