### ISSUE TITLE
ArguementError with align_dlib.py

### ISSUE THREAD

**Issue by redspart** [cmusatyalab/openface#240]
When running any bit of OpenFace on my server I yield the error below. 

(This is running compare.py)

```
> python2 compare.py ../images/examples{lennon*, clapton*}
> Traceback (most recent call last):
>   File "compare.py", line 58, in <module>
>     align = openface.AlignDlib(args.dlibFacePredictor)
>   File "/home/cdecker/.local/lib/python2.7/site-packages/openface/align_dlib.py", line 90, in __init__
>     self.predictor = dlib.shape_predictor(facePredictor)
> Boost.Python.ArgumentError: Python argument types in
>     shape_predictor.__init__(shape_predictor, str)
> did not match C++ signature:
>     __init__(boost::python::api::object, std::string)
>     __init__(_object*)
```

### PIP2 list
+ openface (0.2.1)
+ dlib (19.1.0) [I have this version working with openface on another computer]
+ scikit-image (0.12.3)
+ scikit-learn (0.18.1)
+ scipy (0.18.1)
+ opencv (2.4.13)

### OS
+ Operating system: 4.8.13-1-ARCH

**Comment by qacollective** [comment]
Hi,

Are you running this from the docker container or just from a git pull and the installed software on your OS?

I'm guessing the latter but would recommend the former.  There are far more dependencies for OpenFace than the ones you've listed - getting the environment right is not a simple thing, which is a very good reason to use docker - it lets one person get those dependencies right and encapsulate them for everyone to easily use.  So I'd recommend you to [Install docker](https://docs.docker.com/engine/installation/), then simply type:

> docker pull bamos/openface

Then run by:
> docker run -p 9000:9000 -p 8000:8000 -t -i bamos/openface /bin/bash
> cd /root/openface

Then play:
> ./demos/compare.py images/examples/{lennon*,clapton*}
> ./demos/classifier.py infer models/openface/celeb-classifier.nn4.small2.v1.pkl ./images/examples/carell.jpg

See [here](http://cmusatyalab.github.io/openface/setup/) for further details.

Andrew

**Comment by redspart** [comment]
@qacollective 

Thank you very much for the fast reply. We realized that our python was compiled with gcc6 while other dependencies were compiled with gcc4.9. We fixed this by recompiling it all with gcc4.9.

**Comment by MU001999** [comment]
@redspart how recompiling python with gcc4.9?
