### ISSUE TITLE
How to run in GPU mode

### ISSUE THREAD

**Issue by haridatascientist** [cmusatyalab/openface#242]
### Context of the issue.
I have installed Torch and i have GPU system but Openface failed to run in GPU

### Expected behavior.
how to make the system to work in GPU mode

### Actual behavior.
Openface demos takes CPU mode to run makes long time to execute

### Steps to reproduce.
how to change where to change settings to make code run in GPU mode

### OS and hardware information.

+ Operating system: ubuntu  14.04.5
+ Torch version: 7
+ CPU architecture: [todo]
+ GPU type (if using): nvidia GT640

**Comment by bamos** [comment]
You can use the GPU mode with the `cuda` options in the OpenFace scripts and API.
