### ISSUE TITLE
Web demo

### ISSUE THREAD

**Issue by hsoltani** [cmusatyalab/openface#243]
Hi

I want to run the web demo with the video from Hikvision ip camera instead of a webcam. I can stream the video using MJPG-Streamer in the network. The network rtsp address is "rtsp://192.168.2.32/video.cgi?.mjpg". I'd be thankful if anyone can help me.

Thanks,
Hannaneh

**Comment by kernel8liang** [comment]
Hi，

i am very interested how to stream video to remote server, and how to direct it into web demo?

cloud you please give more detail ?

**Comment by daoanhnhat1995** [comment]
@hsoltani I was able to do so. Basically, change the stream video src to your source, the code in the web demo already encodes as data string in form of jpg for the web socket server to process it already

**Comment by deepmore1** [comment]
@daoanhnhat1995 and where exactly did you changed that ? i mean which source file contains the videocapture funtion ?

**Comment by daoanhnhat1995** [comment]
@deepmore1 

- In "web/demo/index.html", the picture is captured from video tag with id="videoel", if you change that to your video stream ( if you're using raspberry pi, you can expose the camera stream through webrtc (Look up UV4Lwebrtc), and replace the video stream with <img src={your_stream_url} id="videoel" />
- The "js/openface-demo.js" file contains the code for encoding the picture to dataUrl and send it back to the training server.

**Comment by deepmore1** [comment]
i changed that value to my video stream URLl but nothing happens, actually what i am trying to find is the like in the Opencv funtion : videocapture("camera ID"); i didnt find in that html file or in the js file you mentioned

**Comment by deepmore1** [comment]
i'm really having a hard time here, i couldn't fing the video src linking the webcam iD to the streaming, i'm not using any raspberry card , i just want to redirect the rtsp stream i get from a video surveillance camera to use it for face recognition with web demo instead of the webcam feed.

**Comment by iamblue** [comment]
You can use ffmpeg to capture the rtmp streaming .

**Comment by mingfengwuye** [comment]
Is this problem solved? I met the same situtation.
