### ISSUE TITLE
mac docker web demo issue

### ISSUE THREAD

**Issue by kernel8liang** [cmusatyalab/openface#244]
I followed the ```setup.md```, can run ```comparison demo``` successfully. 

i start docker image with command
```
docker run -p 9000:9000 -p 8000:8000 -t -i bamos/openface /bin/bash
cd /root/openface
./demos/web/start-servers.sh

```
but can not connect to the web server. 

I have two questions:
1, how could i check if the camera was mapped correctly?

2, when i connected  ```http://172.17.0.2:8000/``` in my host browser, got error 

```
This site can’t be reached

172.17.0.2 refused to connect.
Search Google for 172 8000
ERR_CONNECTION_REFUSED
```
how to fix it.

**Comment by daoanhnhat1995** [comment]
@kernel8liang 
1. I tried running the web demo on docker but couldn't get the camera because "getUserMedia" which gets the webcam doesn't support insecure origins anymore. 
They had the workaround here http://cmusatyalab.github.io/openface/demo-1-web/ 
But I just had an easy workaround by:
- Clone the openface web demo to your local machine
- Change the socket address in "js/openface-demo" to "ws://<docker-machine-ip>:9000" 
- Then  run the web page only by python -m SimpleHTTPServer 8000. 
That way you can easily get the camera correctly, the web only communicates to openface through websocket so as long as you expose Websocket server on Docker, it'll work as expected

2. Pretty sure you didn't get the right IP address for your running docker container, try docker-machine ls to list the addresses.

**Comment by SalehAly** [comment]
+1 

I also followed these instructions 
```
docker pull bamos/openface
docker run -p 9000:9000 -p 8000:8000 -t -i bamos/openface /bin/bash
cd /root/openface
./demos/compare.py images/examples/{lennon*,clapton*}
./demos/classifier.py infer models/openface/celeb-classifier.nn4.small2.v1.pkl ./images/examples/carell.jpg
./demos/web/start-servers.sh
```
And it loads a lot then says Site cannot be reached when requesting `docker-ip:8000`

**Comment by SalehAly** [comment]
reading the comments/docs I realized that I am using the ip from inside my container instead of running with the ip of the docker-machine itself. This solved the issue for me.

**Comment by kernel8liang** [comment]
@daoanhnhat1995 I have connected the web, but it says ```Error fetching video from webcam```

**Comment by kernel8liang** [comment]
@SalehAly I have connected the web but it says "Error fetching video from webcam", did you also have this issue?

**Comment by kernel8liang** [comment]
use firefox it works. thanks @daoanhnhat1995 @SalehAly

**Comment by SalehAly** [comment]
@kernel8liang  check my answer here if you want to run it on chrome.  I was able to do it yesterday
https://github.com/cmusatyalab/openface/issues/75

**Comment by kernel8liang** [comment]
@SalehAly thanks.

**Comment by malik-aliyev-94** [comment]
Hi.
I am trying to run "Real-Time Web Demo" on MacOS using docker. I have successfully installed docker, also "Demo 2: Comparing two images" have been run successfully. 
But when I am trying to run  Demo 1 (Real-Time Web), I can not access it via browser although the example have been running successfully.
The output is as follows:

`Starting the HTTP TLS server on port 8000
and the Secure WebSocket server on port 9000.

Access the demo through the HTTP server in your browser.
If you're running on the same computer outside of Docker, use https://localhost:8000
If you're running on the same computer with Docker, find the IP
address of the Docker container and use https://<docker-ip>:8000.
If you're running on a remote computer, find the IP address
and use https://<remote-ip>:8000.

WARNING: Chromium will warn on self-signed certificates. Please accept the certificate
and reload the app.

WebSocket Server: Logging to '/tmp/openface.websocket.log'

2018-03-28 18:51:59+0000 [-] Log opened.
2018-03-28 18:51:59+0000 [-] WebSocketServerFactory (TLS) starting on 9000
2018-03-28 18:51:59+0000 [-] Starting factory <autobahn.twisted.websocket.WebSocketServerFactory object at 0x7f72f3db1f50>`

I have tried to access it by docker-machine ip address.
1. docker-machine start default
2. eval $(docker-machine env default)
3. docker run .....
4. docker-machine ip default --> returns 192.168.99.100

When I am trying to open this address (192.168.99.100:8000) on browser - It shows "This site can’t be reached".

But when I am trying to open to access :9000 port on browser (to test socket conection)  - "WebSocket connection closed: connection was closed uncleanly (peer dropped the TCP connection without previous WebSocket closing handshake)" log appending to the terminal. 

Please help to solve this problem. What else I need to do to run this example ?
