### ISSUE TITLE
forward function in torch_neural_net.py not returning rep

### ISSUE THREAD

**Issue by chakshuJ** [cmusatyalab/openface#245]
### Context of the issue.
I am trying to run compare.py function in web browser through php,which is internally calling compare.py with two images to compare and then show the final result on the web page. But it is not giving results due to forward function in it. I tried putting print at various places in compare.py in order check where are the issues. So I found out that after calling the forward function it is not getting rep in return.

### Expected behavior.
forward function should return the rep and then the issue will be resolved.

### Actual behavior.
If I am running the same php file in command line then the output is coming as per the expectations but when I run the same php in web browser I am not getting the final end results.

**Comment by bamos** [comment]
Hi, can you send a minimal working code example?

-Brandon.

**Comment by chakshuJ** [comment]
<?php
$command = escapeshellcmd("/usr/bin/python /file/path/compare.py
/image/path/image1.jpeg /image/path/image2.jpeg");
$result = exec("$command",$retval);
var_dump($retval);
?>

Here is the php code I am using to run compare.py with a couple of image.

**Comment by bamos** [comment]
I'm closing this issue because this does not appear to be an issue with OpenFace's core library code. Somebody on our mailing list may be able to help you with this use case.

-Brandon.
