### ISSUE TITLE
Face detection extremely slow on raspberry pi

### ISSUE THREAD

**Issue by lorenzob** [cmusatyalab/openface#252]
Hi, I managed to build and install everything on a Raspberry Pi 3 B 1.2 (with ubuntu Ubuntu 16.04.1).

Linux trz-pi 4.1.19-v7+ #858 SMP Tue Mar 15 15:56:00 GMT 2016 armv7l armv7l armv7l GNU/Linux
/dev/mmcblk0p2 on / type f2fs (rw,noatime,background_gc=off,discard,nouser_xattr,noacl,noinline_data,active_logs=6)

When I run the compare.py demo it runs extremely slow, this is an example:

```
$ time ./demos/compare.py --verbose images/examples/{lennon*,clapton*}
Argument parsing and loading libraries took 0.986265182495 seconds.
Loading the dlib and OpenFace models took 21.041975975 seconds.
Processing images/examples/lennon-1.jpg.
  + Original size: (1050, 1400, 3)
  + Face detection took 136.867900133 seconds.
  + Face alignment took 0.0279901027679 seconds.
  + OpenFace forward pass took 0.910177946091 seconds.
Representation:
...
real    15m43.813s
user    15m42.920s
sys    0m1.770s
```
Face detection time goes from 130 to 15 seconds depending on the pictures (full output [here](https://gist.github.com/lorenzob/6dbb9fa24179709add19a4637bee206d)).

Similar situation for the profile-network.lua script:

```
$ time util/profile-network.lua
Single image forward pass: 903.30 ms +/- 62.08 ms	

real	7m48.926s
user	15m59.320s
sys	0m3.060s
```

I downloaded the nn4.v1.ascii.t7 model from [here](http://openface-models.storage.cmusatyalab.org/nn4.v1.ascii.t7.xz) and converted to binary in this way:

local net = torch.load('./models/openface/nn4.v1.ascii.t7', 'ascii'):float()
torch.save('nn4.v1.arm.t7', net)

There is plenty of free memory, "nothing" else running (multi.user text mode), nothing particularly strange with top, iostat, temperature, just one core running full speed. Pi is connected to main power.

Running a few benchmarks found [here](https://www.element14.com/community/community/raspberry-pi/blog/2016/02/29/the-most-comprehensive-raspberry-pi-comparison-benchmark-ever) the Pi seems to be slower than what shown in the article but not extremely so.

I have no idea if this is normal or not. Any suggestion is welcome.

**Comment by KGOURAV** [comment]
@lorenzob  hi i am currently doing face recognition  i am using this  nn4.v1.ascii.t7 ascii model but at one point i am getting error as u have converted i have also converted this file    but it shows me nill can u upload or mail me(gouravkoutika@gmail.com) the this file  **nn4.v1.arm.t7**

**Comment by lorenzob** [comment]
@KGOURAV 
I've uploaded the arm models here:

https://www.dropbox.com/s/rtq5p99z58hbluu/nn4.v1.arm.t7.xz?dl=1
https://www.dropbox.com/s/8m03csy0xfwxsaa/nn4.small2.v1.arm.t7.xz?dl=1

One is from the download link mentioned in the previous post, the other (small2) is from the current openface repo.

and here is the conversion script:  https://gist.github.com/lorenzob/b6db5c6a160abefbb10e655f6960e3cd

BTW I started over with a new Raspbian installation following the instructions here: 

http://allskyee.blogspot.it/2017/03/face-detection-and-recognition-using.html 

and I still have very slow face detection (and slow everything). It takes me 47 seconds to run the classifier.py demo mentioned there, while it should take 3/4 seconds (for the whole thing I suppose, check the comments).
Please let me know if you get better results.

I'll try to ask on the dlib front as this is not exactly an openface issue.

**Comment by KGOURAV** [comment]
@lorenzob  thanks mate u helped me a lot at last i have got the result i thank u very much

**Comment by lorenzob** [comment]
@KGOURAV Good to hear it helped. How long does it take to you to run the compare demos?

**Comment by iamblue** [comment]
I am also took 40s~1min for compare.py.

**Comment by BarbaL** [comment]
@iamblue So as i

**Comment by iamblue** [comment]
Here is my log:
```
pi@raspberrypi:~/openface $ time ./demos/classifier.py --verbose infer ../generated-embeddings/classifier.pkl ./Michelle_Yeoh_0001.jpg
/usr/local/lib/python2.7/dist-packages/sklearn/lda.py:4: DeprecationWarning: lda.LDA has been moved to discriminant_analysis.LinearDiscriminantAnalysis in 0.17 and will be removed in 0.19
  "in 0.17 and will be removed in 0.19", DeprecationWarning)
Argument parsing and import libraries took 4.27616786957 seconds.
Loading the dlib and OpenFace models took 20.1932799816 seconds.

=== ./Michelle_Yeoh_0001.jpg ===
  + Original size: (250, 250, 3)
Loading the image took 0.00881004333496 seconds.
Face detection took 4.87970781326 seconds.
Alignment took 0.0421969890594 seconds.
This bbox is centered at 133, 122
Neural network forward pass took 33.9644801617 seconds.
Prediction took 0.00277400016785 seconds.
Predict Jennifer_Aniston with 0.23 confidence.
```

**Comment by iamblue** [comment]
'Neural network forward pass took' take lot of time. Any suggestion to solve it ?

**Comment by pravbeatle** [comment]
Argument parsing and import libraries took 2.71801400185 seconds.
Loading the dlib and OpenFace models took 10.1467740536 seconds.

=== test.jpg ===
  + Original size: (1944, 2592, 3)
Loading the image took 0.370079994202 seconds.
Face detection took 205.292082071 seconds.
Alignment took 0.142750024796 seconds.
This bbox is centered at 1416, 1097
Neural network forward pass took 0.590049028397 seconds.
Prediction took 0.00526285171509 seconds.
Predict jawad with 0.45 confidence.

**Comment by pravbeatle** [comment]
I don't think there is a solution to this.
You need RAM for image processing which the pi doesn't have enough of.
Only solution is to send the image or video over to an instance with decent specs and do the processing from it and return the result back to the pi.

**Comment by shamun** [comment]
Should we not write it in C/C++ instead of trying with Python? Maybe a small C/C++ alternative processing for ARM and see if that might help?
