### ISSUE TITLE
After installed, when importing AlignDlib got ImportError

### ISSUE THREAD

**Issue by oxydron** [cmusatyalab/openface#256]
### Context of the issue.
After installed the lib with `python setup.py install` tried to `from openface import AlignDlib` but got:

```Python
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    from openface import AlignDlib
  File "/home/bh/anaconda3/envs/keras/lib/python3.5/site-packages/openface/__init__.py", line 6, in <module>
    import data
ImportError: No module named 'data'
```

### Expected behavior.
Just work.

### Actual behavior.
Got an import exception.

### Steps to reproduce.
1. Install openface.
2. Try the code below (consider changing the paths to a face image):
```Python 
import cv2
from openface import AlignDlib

img = cv2.imread('/home/bh/project/input/afew2016/imgs2/Train/Angry/003108520-003_0.jpg')
img = AlignDlib(img)

cv2.imwrite('/home/bh/project/input/afew2016/output_br.jpg')
```

### OS and hardware information.

+ Operating system: Ubuntu Budgie 16.04.2
+ Torch version: 
+ CPU architecture: Quad-Core Intel® Core™ i3-2100 CPU @ 3.10GHz
+ GPU type (if using): Nope.

### More info
Maybe put `import openface.data` instead of `import data` should fix.

**Comment by bamos** [comment]
The master branch only supports Python 2 and I think this is fixed in the Python 3 PR.
