### ISSUE TITLE
Write explicitly if this lib works on Python 2 o 3 or both.

### ISSUE THREAD

**Issue by oxydron** [cmusatyalab/openface#257]
Some errors and problems may be avoided if the Python version is explicit on everywhere for anyone see.
Is this lib compatible with Python 3.5.2?

**Comment by bamos** [comment]
The master is for Python 2 only but there's a PR for Python 3 support. I'm still not sure why the new version's failing some of the tests so I haven't merged it in yet.

**Comment by oxydron** [comment]
@bamos Maybe updating the main README.md to reflect this information would be nice.

Best regards.

**Comment by bamos** [comment]
I've just merged the PR adding Python 3 support to the master branch so OpenFace should work well in both Python versions now.

-Brandon.

**Comment by oxydron** [comment]
Thank you very much :)
