### ISSUE TITLE
error when I execute start-servers.sh

### ISSUE THREAD

**Issue by raul93611** [cmusatyalab/openface#259]
I get this error : 
/usr/bin/env: «th»: No such file or directory
and I don't know why .......................because when I execute this command:
 ln -s /root/torch/install/bin/* /usr/local/bin/th
ln: fallo al crear el enlace simbólico '/usr/local/bin/th': El archivo ya existe
it says to me that the file already exists.

**Comment by bamos** [comment]
Make sure `th` is on the PATH where it's being called from (I think from Python here)
