### ISSUE TITLE
detecting and recognizing multiple persons in the same frame

### ISSUE THREAD

**Issue by deepmore1** [cmusatyalab/openface#264]
### Expected behavior.
[detecting and then recognizing all the faces appearing in the video frame.]

### Actual behavior.
[only detect and recognize a single face among all the faces present in front on the camera]

### OS and hardware information.

+ Operating system: [Ubuntu 16.04]

**Comment by bamos** [comment]
`getAllFaceBoundingBoxes` will get all of them that dlib detects. You can try using another library for face detection if that's not working well.

**Comment by deepmore1** [comment]
i tried to use the getallFaceboundingboxes instead of the get the largest face function but nothing changes when i run the demo when i change something in the aligndlib file what should i do to apply the changes (excuse me i'm a newbie in python)

**Comment by prateekmehta59** [comment]
just add " --multi " in front of Infer in the code to make it work.
