### ISSUE TITLE
Hint on making openface working much faster on CPU

### ISSUE THREAD

**Issue by jczaja** [cmusatyalab/openface#266]
Hi,

To make openface inference working much faster you could replace Torch with Intel's fork of Torch that has Intel Math kernel library bundled eg.

1) Checkout autoDownloadMKL branch of Intel's fork of Torch
https://github.com/intel/torch/tree/autoDownloadMKL
2) Build Intel's fork of torch, as usual, MKL will be downloaded during that process automatically
3) Use opeface as usual, just make sure that Torch You use is the one from checked out repo.

Result:
On my:
Intel(R) Core(TM) i5-4670R CPU @ 3.00GHz  (two cores, Haswell class processor)

I got openface's NN4 (inference) working 10 times faster than before.

Thanks very much for developing this wonderful open source software

**Comment by bamos** [comment]
Thanks for the useful info!
