### ISSUE TITLE
fail to run /demos/classifier_webcam.py

### ISSUE THREAD

**Issue by deepmore1** [cmusatyalab/openface#269]
I recently tried the classifier.py demo and it's working very well, now i wanted to test the classifier with the webcam feed and maybe later on i'am planning to test with an RTSP feed coming from a video surveillance camera, but the problem is that when i run the command and give the path to the .pkl classifier i trained it gives me the following error : 
```
Traceback (most recent call last):
  File "./demos/classifier_webcam.py", line 191, in <module>
    persons, confidences = infer(frame, args)
  File "./demos/classifier_webcam.py", line 108, in infer
    (le, clf) = pickle.load(f)  # le - label and clf - classifer
  File "/usr/lib/python2.7/pickle.py", line 1384, in load
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
KeyError: '#'

```
i run this command : 
/demos/classifier_webcam.py /home/ghassen/openface/openface-master/openface/align_dlib.py 
where i give the path to the classifier and the dlib face predictor .

**Comment by BarbaL** [comment]
@deepmore1 look at comentary on  line 170 ~ 173 of "classifier_webcam,py"

> parser.add_argument(
>         'classifierModel',
>         type=str,
>         help='**The Python pickle representing the classifier. This is NOT the Torch network model, which can be set with --networkModel.**')

Look, i never used the classifier_webcam.py, only the classifier.py, but i know where u can get Python Pickle. You have to take the instructions to create a classifier.pkl, so you can read [this demo](https://cmusatyalab.github.io/openface/demo-3-classifier/).

**Comment by deepmore1** [comment]
hey @BarbaL  thax mate for your quick reply , i already managed to do that tutorial and got a classifier.pkl trained with a dataset i got from the internet to manage the unknown detection problem , so basically u mean i should include the path to that classifier in the command line arguments ?

**Comment by deepmore1** [comment]
i fixed the problem , the command to type in order to run the webcam demo is as following 
./demos/classifier_webcam.py <path to the feature classifier> 
it's working perfectly and giving output as follows : 

P: ['unknown'] C: [0.76265470536492086]
P: ['ghassen'] C: [0.51449047915875412]
P: ['unknown'] C: [0.5322239569707623]
P: ['ghassen'] C: [0.46277030219658255]
P: ['unknown'] C: [0.47470871402301479]
P: ['ghassen'] C: [0.61751386691297017]
P: ['unknown'] C: [0.7547305639797719]
P: ['unknown'] C: [0.72421109538335238]
P: ['ghassen'] C: [0.53364084226979525]
P: ['unknown'] C: [0.80024436171133884]
P: ['unknown'] C: [0.67699783515868306]
P: ['unknown'] C: [0.75440366027540307]
P: ['unknown'] C: [0.62089120928139441]
P: ['unknown'] C: [0.69419184759473451]
P: ['unknown'] C: [0.62242086391374396]
P: ['unknown'] C: [0.51011845839511472]
P: ['unknown'] C: [0.65243824056912014]
P: ['unknown'] C: [0.56949149874677207]
P: ['ghassen'] C: [0.45642805648465584]
P: ['unknown'] C: [0.68044394123864282]
P: ['ghassen'] C: [0.54406959452160475]
P: ['ghassen'] C: [0.88052890744178769]
P: ['ghassen'] C: [0.80630021894912496]
 the recognized person "ghassen" and the confidence level .

**Comment by BarbaL** [comment]
Feel free to close this issue if it has been fixed. Hoped to have helped and good luck.

**Comment by elahia** [comment]
Hi
after installing i tried to test it but i got follwing error:
`elia@elia:~/openface$ ./demos/classifier.py infer models/openface/celeb-classifier.nn4.small2.v1.pkl ./images/examples/carell.jpg
Traceback (most recent call last):
  File "./demos/classifier.py", line 293, in <module>
    infer(args, args.multi)
  File "./demos/classifier.py", line 177, in infer
    (le, clf) = pickle.load(f)
  File "/usr/lib/python2.7/pickle.py", line 1378, in load
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 1090, in load_global
    klass = self.find_class(module, name)
  File "/usr/lib/python2.7/pickle.py", line 1126, in find_class
    klass = getattr(mod, name)
AttributeError: 'module' object has no attribute '_passthrough_scorer'
`

then i tried for [demo3](https://cmusatyalab.github.io/openface/demo-3-classifier/) but still, the error exists! can anyone please help me?
Regards
