### ISSUE TITLE
CMake Error

### ISSUE THREAD

**Issue by wqysq** [cmusatyalab/openface#27]
When I run  demo1,the first I can not find "src"  folder,so I  build src document,and  then  I run " cmake ../../tools/python",it disply"CMake Error at /usr/share/cmake-3.0/Modules/FindBoost.cmake:1278 (message):
  Unable to find the requested Boost libraries.

  Unable to find the Boost header files.  Please set BOOST_ROOT to the root
  directory containing Boost or BOOST_INCLUDEDIR to the directory containing
  Boost's headers.CMake Error: The following variables are used in this project, but they are set to NOTFOUND."

but I can not solve this error,someone who can help me ,thank you very much!

**Comment by kaikuehne** [comment]
Do you have boost-python installed?

**Comment by wqysq** [comment]
@kaikuehne I had,could you tell me how to run the demo Successfully?

**Comment by bamos** [comment]
Hi @wqysq - I think you're missing a boost library dependency required for building dlib. What OS are you using?

If you're using Ubuntu, make sure you're running everything in the Dockerfile at https://github.com/cmusatyalab/openface/blob/master/Dockerfile

**Comment by wqysq** [comment]
@bamos I am using Ubuntu 15.04,I try it,thank you very much!

**Comment by wqysq** [comment]
Hi  @bamos Thank you for your suggestion，I follow the documentation provided by you has been configured, but I can not open the site ：http://localhost:8000.
can you help me ? thanks.

**Comment by bamos** [comment]
As a sanity check, can you run `./demos/compare.py images/examples/lennon-{1,2}.jpg`?

If so, can you send the output of `./demos/www/server.py`?

**Comment by wqysq** [comment]
sorry @bamos   I can not run ./demos/compare.py images/examples/lennon-{1,2}.jpg 
Error message：“RuntimeError: Unable to open /home/cwt/openface-master/demos/../models/dlib/shape_predictor_68_face_landmarks.dat”
Is the"dlib"have some  problem?or Can you give me some advice?

**Comment by bamos** [comment]
Can you verify `models/dlib/shape_predictor_68_face_landmarks.dat` exists? If not, download it and the other openface models with `./models/get-models.sh`

**Comment by wqysq** [comment]
thank you very much @bamos .now I can run the demo2.I am very grateful for your help. 
Now I run demo 3：./demos/classifier.py infer ./models/openface/celeb-classifier.nn4.v1.pkl <image>
but the error:
"root@cwt-B85M-D2V:/home/cwt/openface-master# ./demos/classifier.py infer ./models/openface/csleb-classifier.nn4.v1.pkl <images>
bash: unexpected symbol  'newline'  Incorrect syntax near"
How should I solve this problem？thank you very much!

**Comment by bamos** [comment]
The error is from bash - are you pasting from somewhere and introducing newlines?

**Comment by wqysq** [comment]
@bamos I'm not to do anything,when I run demo2 OK,I just to run demo3, but in the "./demos/classifier.py infer ./models/openface/celeb-classifier.nn4.v1.pkl " , display this error.

**Comment by bamos** [comment]
Can you please double check and provide more info if possible? I do not expect bash errors from the openface code.

**Comment by wqysq** [comment]
@bamos in the “Demo 3: Training a Classifier”.I follow the steps of guide，At this step,“Run the classifier on your images with:”,The above error occurs"bash: unexpected symbol 'newline' Incorrect syntax near".thank you very much,I then check it again.

**Comment by bamos** [comment]
Hi @wqysq - it's much easier to help you debug when you send the exact command and output. Please do this in the future.

I think I see what you're doing for this.

In the following, `<image>` is supposed to be replaced with a path to an image. With the brackets, your shell is performing IO redirection and giving you the bash error.

```
./demos/classifier.py infer ./models/openface/celeb-classifier.nn4.v1.pkl <image>
```

**Comment by wqysq** [comment]
Hi,you are right,I solved it,thank you very much!

**Comment by bamos** [comment]
Great to hear!
