### ISSUE TITLE
Problem with test example starting (for compare.py)

### ISSUE THREAD

**Issue by pasechnyuk2004** [cmusatyalab/openface#275]
### Context of the issue.

Good afternoon, I installed OpenFace on my Ubuntu 16.04 (in virtual box, Host: OS X) and everything works fine, test examples run without any problems. Yesterday I installed this virtual machine with Ubuntu on my other OS X, but everything works in an unexpected way: when I run test example for compare.py script I see this error message:
`Error getting result from Torch subprocess.`
`Line read: `
`Exception: `
`could not convert string to float:`
`==========`
`stdout: `
And can't find more information about this error. I checked RAM on virtual machine on other computer (6.5 GB) all settings of virtual machine, virtual box, tried to reinstall all libraries, change version of oracle virtual box, but it did not help me. Tell me, please, what is worth doing in this situation?

### OS and hardware information.

+ Operating system: OS X (Host) and Oracle VM VirtualBox 5.1.14 with Ubuntu 16.04
+ 6.5 GB RAM in virtual machine
+ Torch version: 7
+ CPU architecture: Intel i5

**Comment by ethanluoyc** [comment]
I can confirm that I am also having this problem while trying to install openface on Mac.

**Comment by bamos** [comment]
This could be an issue in the latest version of Torch, can you try downgrading Torch to something from a year ago?

**Comment by ethanluoyc** [comment]
I found a fix by @maxmurder from here:
https://github.com/jcjohnson/neural-style/issues/138

I think the problem is due to installing an old version of libpng
the Mono framework (By MS Code I suppose). Getting rid of that helps me to fix the problem.
