### ISSUE TITLE
Is there an enhancement of accuracy?

### ISSUE THREAD

**Issue by David-Jin** [cmusatyalab/openface#282]
Hi.
I noticed that this project startup since Oct, 2015.      I have 3 questions.

(1) Is there any enchancement of accuracy up till now?  better trained models ?
The data following is presented on the official website.
Model	                               Accuracy	                AUC
nn4.small2.v1 (Default)	      0.9292 ± 0.0134	0.973
nn4.small1.v1	                      0.9210 ± 0.0160	0.973
nn4.v2	                               0.9157 ± 0.0152	0.966
nn4.v1	                               0.7612 ± 0.0189	0.853
FaceNet Paper (Reference)     0.9963 ± 0.009	not provided

(2) Is there any plan to porting other networks  or algorithm  to this project like "Center Loss", etc.

(3) There is another prject from "davidsandberg/facenet".  This is a tensorflow project. What's the connections and difference between the two projects?

**Comment by bamos** [comment]
Hi, I'm not actively working on openface improvements anymore other than staying on here and merging in improvements and making sure no serious bugs come up. As a quick response to your questions, 1) there's no improved model, 2) I thought about implementing the center loss but never did, and 3) that's another implementation of facenet, I'm not sure how it compares.
