### ISSUE TITLE
how to run this openface?

### ISSUE THREAD

**Issue by Tejeshwarabm** [cmusatyalab/openface#283]
I have downloaded the openface by this github repo and install all necessary libraries.
But I dont no, from where I have to begin and how to compile!

can you please suggest me to go ahead ? Thank you in advance

**Comment by bamos** [comment]
Hi @Tejeshwarabm - glad you're trying out OpenFace! Somebody may be able to help you out on our mailing list.

-Brandon.

**Comment by Malathi15** [comment]
Hi @Tejeshwarabm  Did you got the procedure? I have the same doubt!
Thanks in advance
