### ISSUE TITLE
Retraining an existing openface classifier

### ISSUE THREAD

**Issue by pranav-korpal** [cmusatyalab/openface#287]
### Context of the issue.
[Provide more detailed introduction to the issue itself and why it is relevant]
If we have a face authentication system to be implemented for an organization in which we want to grant access to the valid employees and reject individuals foreign to the organization.For achieving this we train the openface model with faces of all of the organizations'  employees.However now how can we modify the existing classifier(retrain)  to validate the newly joined employees.Also how can this be done for employees vacating the organization,such that access is no longer granted to them.
 
### Expected behavior.
[Describe what you would expect to have resulted from this process.]
My question  is that, is  there a way to achieve this, with the Openface library,without training the whole new set of images again.In short can we "expand" the existing classifier to incorporate  employee changes.
### Actual behavior.
[Describe what you currently experience from this process, and thereby explain the bug.]

### Steps to reproduce.
[Present a minimal example and steps to produce the issue.]

### OS and hardware information.

+ Operating system: [todo]
+ Torch version: [todo]
+ CPU architecture: [todo]
+ GPU type (if using): [todo]

**Comment by champloo11** [comment]
This would be an extremely useful feature/documented process. It helps significantly with the expansion of services that might be built around this.
