### ISSUE TITLE
Why not Ubuntu 16.04?

### ISSUE THREAD

**Issue by tomjaguarpaw** [cmusatyalab/openface#289]
Is there any particular reason the Docker image hasn't been ported to Ubuntu 16.04?  14.04 is more than three years behind at this point.

**Comment by bamos** [comment]
Happy to add a pointer to a 16.04 container if you or somebody else adds one

**Comment by tomjaguarpaw** [comment]
Thanks.  I may create one.  I just wondered if there was any known incapability with 16.04.
