### ISSUE TITLE
openface  accuracy measure in percentages

### ISSUE THREAD

**Issue by Suraj59** [cmusatyalab/openface#299]
Hi guys
### Context of the issue.
In openface  accuracy  measure in 0.00 some thing in point.can we calculate percentage. 

### Expected behavior.
What we changes the pointer result must be in percentages that used in other project to calculate the two person faces using percentages

**Comment by bamos** [comment]
Hi, the OpenFace measure is a distance and can't be interpreted as a percentage.

**Comment by Suraj59** [comment]
Hi, the OpenFace measure is a distance and can't be interpreted as a percentage.
Hi,
when i was run the project Ex-Predict SteveCarell with 0.97 confidence.Predict SteveCarell with 0.97 confidence.code- ./demos/classifier.py infer models/openface/celeb-classifier.nn4.small2.v1.pkl ./images/examples/carell.jpg the answer in 0.97 it is in float but i don't want to be answer in float or point i want be be answer in integers i need only answer is 97 in integer value.
Lets take one Ex- Image X and image Y is compares using openface using the openface it's answer will be in some float lets take 0.68 but i dont want the answer in 0.68 i need only 68 then what we do for this i need the only answer in integer 68 not in 0.68 what we do now what we change in code and where please send me the code that help the other program that used we calculates the face in interger 
thank you for help i need for my project. it's wonder full project its help me thank you
![screenshot from 2017-08-11 16-01-33](https://user-images.githubusercontent.com/11031352/29240072-83b18ef8-7f7b-11e7-957c-33df1a7f0ea4.png)
