### ISSUE TITLE
ImportError: numpy.core.multiarray failed to import

### ISSUE THREAD

**Issue by onurays** [cmusatyalab/openface#30]
I am trying to setup this project for hours on Mac OS. Could anyone please help me to resolve this import error in server.py.

ImportError: numpy.core.multiarray failed to import
Traceback (most recent call last):
  File "./server.py", line 28, in <module>
    import cv2
ImportError: numpy.core.multiarray failed to import

**Comment by kaikuehne** [comment]
Hi, did you install numpy?
You also need to install scipy, pandas, scikit-learn and scikit-image
and the packages listed in demos/web/requirements.txt.

Note:
If you are using a virtualenv (which I recommend), the cv2 package will not be available
because the python module was only installed for the system-python.
In that case, just copy the cv2 module into your virtualenv:

```
cp /usr/local/lib/python2.7/site-packages/cv* <VIRTUALENV>/lib/python2.7/site-packages
```

**Comment by onurays** [comment]
Yes, I installed all of the dependencies. cv2 is also available. I already copied them to virtualenv.

numpy-1.10.1
pandas-0.17.0
scipy-0.16.0
scikit_image-0.11.3
scikit_learn-0.16.1

**Comment by bamos** [comment]
Do the solutions here help? http://stackoverflow.com/questions/28157976/importing-opencv-and-getting-numpy-core-multiarray-failed-to-import

**Comment by bamos** [comment]
See also http://stackoverflow.com/questions/20518632/importerror-numpy-core-multiarray-failed-to-import

**Comment by onurays** [comment]
I already tried both of your suggestions. numpy and others are up to date. Thanks.

**Comment by bamos** [comment]
What numpy version are you using? I'm using 1.9.2.

```
~$ python2 -c 'import numpy; print (numpy.version.version)'
1.9.2
```

**Comment by bamos** [comment]
Just as a sanity check, can you try outputting the numpy version right before the failed cv2 import?

**Comment by bamos** [comment]
https://github.com/Itseez/opencv/issues/4893 shows importing `numpy` before `cv2` helps in some cases

**Comment by onurays** [comment]
Actually, i just deleted everything to start over, this will take some moment. Thanks a lot.

**Comment by onurays** [comment]
After struggle of another couple hours, I have a clean setup by following these tutorial for Mac OS:
http://www.pyimagesearch.com/2015/06/15/install-opencv-3-0-and-python-2-7-on-osx/

Now, I am stuck on dlib setup. It is not compiling:
CMake Error at /usr/local/Cellar/cmake/3.3.2/share/cmake/Modules/FindBoost.cmake:1245 (message):
  Unable to find the requested Boost libraries.

  Unable to find the Boost header files.  Please set BOOST_ROOT to the root
  directory containing Boost or BOOST_INCLUDEDIR to the directory containing
  Boost's headers.
Call Stack (most recent call first):
  /Users/onurays/Documents/openface/dlib-18.16/dlib/add_python_module:57 (FIND_PACKAGE)
  CMakeLists.txt:5 (include)

**Comment by bamos** [comment]
+ [ ] Sorry, the README doesn't mention dlib's boost dependency. I'll add instructions within the next few days.

**Comment by onurays** [comment]
For MacOS users: "brew install boost-python".

And now server.py throws "Segmentation fault: 11". Seems like an OpenCV bug for MacOS. I think i will give up :)

**Comment by bamos** [comment]
Sorry for the bad setup experience.
Depending on your use case, the Docker container works
well on OSX with an Ubuntu Docker machine.

-Brandon.

**Comment by RapidR3D** [comment]
I just wanted to say that I have been having this issue for the past two days and began after an installation of visual studio 2015. After much trial and error the solution was as simple as going to the sitepackages directory and manually deleting anything that had to do with NumPy or MatPlotLib. After deleting I reinstalled using the command:
python -m pip install --user matplotlib-2.0.0-cp35-cp35m-win_amd64.whl

Everything is now back up and running. Including Jupyter Notebook. Which was an odyssey in itself as well.
I hope this can help someone else. It seems so simple now but I swear I nearly through my rig out into the yard over trying to figure out a viable fix for this  problem.

**Comment by bamos** [comment]
Thanks for the helpful post @RapidR3D!
