### ISSUE TITLE
shape_predictor_68_face_landmarks.dat is missing

### ISSUE THREAD

**Issue by skryv-softserveinc** [cmusatyalab/openface#305]
seems shape_predictor_68_face_landmarks.dat was not added to repository

**Comment by YoungD3v** [comment]
Why is this closed without comment? Is the file shape_predictor_68_face_landmarks.dat in the repository? Because I can't find it either.

**Comment by skryv-softserveinc** [comment]
I guess it was closed because of special scripts to download dat files. Need to fix configure stage.
