### ISSUE TITLE
net:forward bug in openface_server.lua

### ISSUE THREAD

**Issue by Strateus** [cmusatyalab/openface#31]
Im not sure if its my personal Torch installation bug, but when i launch lua server and put test PNG to it, it raises following exception:

    /home/igor/torch/install/bin/luajit: /home/igor/torch/install/share/lua/5.1/nn/Normalize.lua:20: attempt to index field '_output' (a nil value)
    stack traceback:
        /home/igor/torch/install/share/lua/5.1/nn/Normalize.lua:20: in function 'updateOutput'
        /home/igor/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
        /home/igor/openface/openface/openface_server.lua:70: in main chunk
        [C]: in function 'dofile'
        ...igor/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:131: in main chunk
        [C]: at 0x00406510

**Comment by bamos** [comment]
Hi @Strateus - thanks for reporting, and sorry for the issue. This is from a backwards incompatible change that was temporarily in Torch's nn master branch by https://github.com/torch/nn/pull/432. It's been reverted and reinstalling `nn` with `luarocks` should resolve the issue. Let me know if it works!

-Brandon.

**Comment by Strateus** [comment]
Thanx, works now!
