### ISSUE TITLE
Optimizing training and prediction

### ISSUE THREAD

**Issue by bmond** [cmusatyalab/openface#318]
Hi,

Is there any optimize way to automate the process when new face class is coming frequently and already there is one .pkl trained model file present for predicting?

Is there any way to predict correct face class from 2 or more trained .pkl model file what contains different class data?

Please let me know if anyone is done with this kind of situation.

Regards,
Bhaskar

**Comment by irving2** [comment]
now ,i  have the same situation,and searching a way for that

**Comment by thayannevls** [comment]
Hey guys, any updates? I'm having the same situation
