### ISSUE TITLE
Unable to run web demo

### ISSUE THREAD

**Issue by swapnilmarathe007** [cmusatyalab/openface#319]
### Context of the issue.
Hi,

I have been trying to run the Web demo on Ubuntu16 , all is fine except for one thing that the camera only shows the black screen (see attached). I am not able to start the training because of black screen . I am attaching the log file here, please see if you can point me to the right direction.
Log file:[openface.websocket.log](https://github.com/cmusatyalab/openface/files/1452696/openface.websocket.log)
![webdemo2a](https://user-images.githubusercontent.com/33475400/32533125-d1f9cefc-c474-11e7-9ce5-47924444d220.PNG)

Thank you!

### Expected behavior.
video streaming is not possible as not able to start the camera as it is having the black screen

### Actual behavior.
Not able to start the camera , having black screen

### Steps to reproduce.
ubuntu 16.04 ,conda enviorment python 2.7

### OS and hardware information.

+ Operating system: [Ubuntu 16.04]
+ Torch version: [Torch7]
+ CPU architecture: [intel]
+ GPU type (if using): [none]

**Comment by abhilash29998** [comment]
exactly same issue. Can anyone help.

**Comment by abhilash29998** [comment]
also initially i wasnt even getting the black window. it automatically got rectified even though the js remained the same

**Comment by vibhavagarwal5** [comment]
Hi! Even I am facing the same issue. Has anyone solved the issue?

**Comment by vibhavagarwal5** [comment]
I am getting black box on firefox while error "Error fetching video from Camera" in Chrome

**Comment by adipascu** [comment]
Until #420 lands you can run `vid.srcObject = vid.mozSrcObject` in the console to fix the issue.
