### ISSUE TITLE
Error while loading 'nn4.v1.t7'

### ISSUE THREAD

**Issue by xcyan** [cmusatyalab/openface#32]
...an/software/torch_build/share/lua/5.1/torch/File.lua:294: unknown object
stack traceback:
	...an/software/torch_build/share/lua/5.1/trepl/init.lua:480: in function <...an/software/torch_build/share/lua/5.1/trepl/init.lua:473>
	[C]: in function 'error'
	...an/software/torch_build/share/lua/5.1/torch/File.lua:294: in function 'readObject'
	...an/software/torch_build/share/lua/5.1/torch/File.lua:240: in function 'readObject'
	...an/software/torch_build/share/lua/5.1/torch/File.lua:288: in function 'readObject'
	...an/software/torch_build/share/lua/5.1/torch/File.lua:272: in function 'readObject'
	...an/software/torch_build/share/lua/5.1/torch/File.lua:288: in function 'readObject'
	...an/software/torch_build/share/lua/5.1/torch/File.lua:288: in function 'readObject'
	...an/software/torch_build/share/lua/5.1/torch/File.lua:272: in function 'readObject'
	...an/software/torch_build/share/lua/5.1/torch/File.lua:311: in function 'load'
	[string "torch.load('nn4.v1.t7');"]:1: in main chunk
	[C]: in function 'xpcall'
	...an/software/torch_build/share/lua/5.1/trepl/init.lua:648: in function 'repl'
	...re/torch_build/lib/luarocks/rocks/trepl/scm-1/bin/th:185: in main chunk
	[C]: ?

**Comment by bamos** [comment]
Hi @xcyan - is this a partial stack trace? What did you run to get this?

Can you try running the following from the `openface` directory?

```Lua
$ th
th> import 'nn'
th> import 'dpnn'
th> net = torch.load('models/openface/nn4.v1.t7')
th> net:size()
25
```

-Brandon.

**Comment by xcyan** [comment]
Hi @bamos ,

Thanks! I've tried the script you suggested, but got the same error.

**Comment by hbredin** [comment]
Same problem here.
```
th> net = torch.load('models/openface/nn4.v1.t7')
```
fails with the following (complete) stack traceback:

````
th> net = torch.load('models/openface/nn4.v1.t7')
/people/bredin/install/share/lua/5.1/torch/File.lua:294: unknown object
stack traceback:
	[C]: in function 'error'
	/people/bredin/install/share/lua/5.1/torch/File.lua:294: in function 'readObject'
	/people/bredin/install/share/lua/5.1/torch/File.lua:240: in function 'readObject'
	/people/bredin/install/share/lua/5.1/torch/File.lua:288: in function 'readObject'
	/people/bredin/install/share/lua/5.1/torch/File.lua:272: in function 'readObject'
	/people/bredin/install/share/lua/5.1/torch/File.lua:288: in function 'readObject'
	/people/bredin/install/share/lua/5.1/torch/File.lua:288: in function 'readObject'
	/people/bredin/install/share/lua/5.1/torch/File.lua:272: in function 'readObject'
	/people/bredin/install/share/lua/5.1/torch/File.lua:319: in function 'load'
	[string "net = torch.load('models/openface/nn4.v1.t7')"]:1: in main chunk
	[C]: in function 'xpcall'
	/people/bredin/install/share/lua/5.1/trepl/init.lua:648: in function 'repl'
	...ple/bredin/install/lib/luarocks/rocks/trepl/scm-1/bin/th:187: in main chunk
	[C]: at 0x00405460
```

**Comment by xcyan** [comment]
@bamos @hbredin 
I solved the problem by re-installing the torch7:
https://github.com/torch/distro
You need to check if "luajit", "luarocks", and "lua" are properly installed.

**Comment by bamos** [comment]
Hi all, I just built a new Docker container from scratch to make sure none of the dependencies have changed and am unable to reproduce this. The demos still work and I'm able to load the model with Torch's command-line interface.

**Comment by bamos** [comment]
cc @maxsombra - can you try re-installing torch as @xcyan suggests?

**Comment by maxsombra** [comment]
try re-installing but still not work i got :

LuaJIT 2.0.4
Lua 5.1
LuaRocks 2.2

**Comment by bamos** [comment]
Can you send the full error and trace?

**Comment by maxsombra** [comment]
is this 

net = torch.load('/home/dguio/Desktop/openface-master/models/openface/nn4.v1.t7')
/home/dguio/torch/install/share/lua/5.1/torch/File.lua:262: unknown Torch class <nn.Sequential>
stack traceback:
	[C]: in function 'error'
	/home/dguio/torch/install/share/lua/5.1/torch/File.lua:262: in function 'readObject'
	/home/dguio/torch/install/share/lua/5.1/torch/File.lua:311: in function 'load'
	[string "net = torch.load('/home/dguio/Desktop/openfac..."]:1: in main chunk
	[C]: in function 'xpcall'
	/home/dguio/torch/install/share/lua/5.1/trepl/init.lua:648: in function 'repl'
	...guio/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:185: in main chunk
	[C]: at 0x0804d6d0

I'll try un-install my VM an try all again I'll tell you if I have success

**Comment by bamos** [comment]
@maxsombra - in the future, can you please surround code with fenced code blocks (see https://help.github.com/articles/github-flavored-markdown/). 

This has hidden a critical error in your stack trace that I almost overlooked.
Your message leaves off the `nn.Sequential` part of: `unknown Torch class <nn.Sequential>`.

Did you import `nn` and `dpnn` before loading the Torch model?

**Comment by bamos** [comment]
Clarification: `<nn.Sequential>` is hidden because Markdown parses it as an HTML tag.

**Comment by shimen** [comment]
I had installed LuaJIT 2.1.0-beta1.
now the command got no errors!!!
net = torch.load('nn4.v1.t7')

download from:
https://github.com/torch/luajit-rocks

make sure to add this option to the cmake "-DWITH_LUAJIT21=ON" !!!!!!!!!!!!!

git clone https://github.com/torch/luajit-rocks.git
cd luajit-rocks
mkdir build
cd build
cmake .. -DWITH_LUAJIT21=ON
