### ISSUE TITLE
Web demo recognize multiple faces at a time? 

### ISSUE THREAD

**Issue by Khurram-Ali** [cmusatyalab/openface#323]
I just tried running web demo and it worked. However it identifies only one face on camera at a time. If two people appears at the same time it will only recognize one of them. How is it possible to recognize more than one people at the same time?

**Comment by richardm47** [comment]
It does have feature for recognition of multiple faces in a single frame/picture. It is done on faces left to right. Add the "--multi" argument in the end.

./demos/classifier.py infer <pkl file location> <image location> --multi
