### ISSUE TITLE
batch-represent : Could not find any image file in the given input paths

### ISSUE THREAD

**Issue by tr-gis** [cmusatyalab/openface#326]
I am following [this guide](https://medium.com/@ageitgey/machine-learning-is-fun-part-4-modern-face-recognition-with-deep-learning-c3cffc121d78) to setup docker container and explore openface. I pulled the docker image **_bamos/openface_** and copied training images to a directory called _training-images_ (located inside /root/openface/). I then copied 10 images of the person I want to recognize into this directory and ran the following commands : 

```
1)Pose detection and alignment:
./util/align-dlib.py ./training-images/ align outerEyesAndNose ./aligned/ --size 96

2)generate the representations from the aligned images:
./batch-represent/main.lua -outDir ./generated-embeddings/ -data ./aligned/

```

However when executing step 2, if get the following ouput : 
```
root@e917ad344dc4:~/openface# ./batch-represent/main.lua -outDir generated-embeddings/ -data aligned
{
  data : "aligned"
  imgDim : 96
  model : "/root/openface/models/openface/nn4.small2.v1.t7"
  device : 1
  outDir : "generated-embeddings/"
  cache : false
  cuda : false
  batchSize : 50
}
aligned	
cache lotation: 	/root/openface/aligned/cache.t7	
Creating metadata for cache.	
{
  sampleSize : 
    {
      1 : 3
      2 : 96
      3 : 96
    }
  split : 0
  verbose : true
  paths : 
    {
      1 : "aligned"
    }
  samplingMode : "balanced"
  loadSize : 
    {
      1 : 3
      2 : 96
      3 : 96
    }
}
running "find" on each class directory, and concatenate all those filenames into a single file containing all image paths for a given class	
now combine all the files to a single large file	
load the large concatenated list of sample paths to self.imagePath	
/root/torch/install/bin/luajit: /root/openface/batch-represent/dataset.lua:193: Could not find any image file in the given input paths
stack traceback:
	[C]: in function 'assert'
	/root/openface/batch-represent/dataset.lua:193: in function '__init'
	/root/torch/install/share/lua/5.1/torch/init.lua:91: in function </root/torch/install/share/lua/5.1/torch/init.lua:87>
	[C]: in function 'dataLoader'
	/root/openface/batch-represent/batch-represent.lua:19: in function 'batchRepresent'
	./batch-represent/main.lua:42: in main chunk
	[C]: in function 'dofile'
	/root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670

```
I looked inside aligned directory and it has the aligned and cropped face images (in .png format) for the 10 images corresponding to the ones present in training-images folder. Following [this](https://groups.google.com/forum/#!topic/cmu-openface/NWyM0VHIOEg) thread I executed the commands below : 
```
$ mkdir -p classify-test/raw/{lennon,clapton}
$ cp images/examples/lennon-* classify-test/raw/lennon
$ cp images/examples/clapton-* classify-test/raw/clapton
$ ./util/align-dlib.py classify-test/raw align innerEyesAndBottomLip classify-test/aligned --size 96
$ ./batch-represent/main.lua -outDir classify-test/features -data classify-test/aligned
```
Which works fine with and gives the following output:
```
root@e917ad344dc4:~/openface# ./util/align-dlib.py classify-test/raw align innerEyesAndBottomLip classify-test/aligned --size 96
=== classify-test/raw/lennon/lennon-2.jpg ===
=== classify-test/raw/clapton/clapton-2.jpg ===
=== classify-test/raw/clapton/clapton-1.jpg ===
=== classify-test/raw/lennon/lennon-1.jpg ===
root@e917ad344dc4:~/openface# ./batch-represent/main.lua -outDir classify-test/features -data classify-test/aligned
{
  data : "classify-test/aligned"
  imgDim : 96
  model : "/root/openface/models/openface/nn4.small2.v1.t7"
  device : 1
  outDir : "classify-test/features"
  cache : false
  cuda : false
  batchSize : 50
}
classify-test/aligned	
cache lotation: 	/root/openface/classify-test/aligned/cache.t7	
Loading metadata from cache.	
If your dataset has changed, delete the cache file.	
nImgs: 	4	
Represent: 4/4	
root@e917ad344dc4:~/openface# 
```

I double checked ensuring path to directories are correct. What else could throw this error ?

System Information : 

    Operating system: [Ubuntu 16.04]    64 bit version
    Processor : Intel i5

**Comment by GISDev01** [comment]
Have you tried it with the trailing /'s as listed in your linked tutorial?
For example: 
`./batch-represent/main.lua -outDir ./generated-embeddings/ -data ./aligned-images/
`
vs. yours:
`./batch-represent/main.lua -outDir classify-test/features -data classify-test/aligned
`

**Comment by tr-gis** [comment]
Yup. Tried with trailing /'s. Sorry I forgot to mention that above.

**Comment by dillontiner** [comment]
@tr-gis are your images contained in a subdirectory of `./aligned-images/`? I just encountered the same issue and solved it by creating an arbitrary subdirectory to hold my images, literally `./aligned-images/arbitrary-subdirectory/`. The `dataset.lua` file seems to expect that images will be grouped in folders representing people (e.g. `./aligned-images/will-ferrell/`, `./aligned-images/chad-smith/`, `./aligned-images/jimmy-fallon/` for the [tutorial](https://medium.com/@ageitgey/machine-learning-is-fun-part-4-modern-face-recognition-with-deep-learning-c3cffc121d78))
