### ISSUE TITLE
classifier_web issue

### ISSUE THREAD

**Issue by Khurram-Ali** [cmusatyalab/openface#328]
i am trying to run the demo/classifier_web.py in standalone format from terminal and providing the generated classifier from the classifier.py demo but am getting unable to load image/frame error

**Comment by GISDev01** [comment]
Can you post the exact commands you're running, and the exact error? And also please share your environment (Docker container or built by hand, etc.).

**Comment by AnastasiaAnastasii** [comment]
I have this problem too. I want to run demo/classifier_web.py with .pkl classifier from example with 'demos/classifier.py' - ./models/openface/celeb-classifier.nn4.small2.v1.pkl. If it will work, I will create my classifier.

root@c433cfd4b076:~/openface# ./demos/classifier_webcam.py --captureDevice 0 models/openface/celeb-classifier.nn4.small2.v1.pkl
Traceback (most recent call last):
  File "./demos/classifier_webcam.py", line 191, in <module>
    persons, confidences = infer(frame, args)
  File "./demos/classifier_webcam.py", line 112, in infer
    reps = getRep(img)
  File "./demos/classifier_webcam.py", line 52, in getRep
    raise Exception("Unable to load image/frame")
Exception: Unable to load image/frame

I work with docker. Other examples works very well. Please, help. What's wrong?

**Comment by taureanamir** [comment]
I am also facing the same issue while trying to run with a classifier that i created.

`Traceback (most recent call last):
  File "./demos/classifier.py", line 293, in <module>
    infer(args, args.multi)
  File "./demos/classifier.py", line 183, in infer
    reps = getRep(img, multiple)
  File "./demos/classifier.py", line 58, in getRep
    raise Exception("Unable to load image: {}".format(imgPath))
Exception: Unable to load image: for_test/Amir
`

could not find a post that could solve this
