### ISSUE TITLE
problem torch load

### ISSUE THREAD

**Issue by maxsombra** [cmusatyalab/openface#33]
i try to load the model nn4.v1.t7 in torch because the compare-demo throw a error when i run this :

th '/openface/openface_server.lua' -model '/models/openface/nn4.v1.t7' -imgDim '96'

 i got that : 

[C]: in function 'dofile'
	/usr/local/lib/luarocks/rocks/trepl/scm-1/bin/th:133: in main chunk
[C]: at 0x0804d6d0

i need a little of help :(

**Comment by bamos** [comment]
Hi, sorry for this problem, it looks like other users are facing it too. I'm closing this as a duplicate and will continue debugging in #32.
