### ISSUE TITLE
Wrong Prediction with classifier.py

### ISSUE THREAD

**Issue by ramanjotkaur90** [cmusatyalab/openface#330]
### Context of the issue.
i trained 400 cases with 790 images (approx 2 images of each person)

### Expected behavior.
i tried to classify from one of the image from the trained data.
it should predict correctly
### Actual behavior.

It predicts wrongly

### OS and hardware information.

+ Operating system: Ubuntu 14.04

**Comment by salemoh** [comment]
Hitting a similar issue where we have 1-2 images per-user and a large number of users (north of 10,000 users) so wanted to check if the SVM classifier can handle such a scenario?
