### ISSUE TITLE
Error during evaluation

### ISSUE THREAD

**Issue by ramanjotkaur90** [cmusatyalab/openface#331]
root@instance-3:/home/ramanjot_kaur0307/openface/evaluation# ./lfw.py nn4.small2.v1 lfw.nn4.small2.v1.reps --lfwPairs pairs.txt 
Loading embeddings.
  + Reading pairs.
  + Computing accuracy.
Traceback (most recent call last):
  File "./lfw.py", line 313, in <module>
    main()
  File "./lfw.py", line 76, in main
    verifyExp(args.workDir, pairs, embeddings)
  File "./lfw.py", line 198, in verifyExp
    writeROC(fname, thresholds, embeddings, pairs[test])
  File "./lfw.py", line 115, in writeROC
    (x1, x2, actual_same) = getEmbeddings(pair, embeddings)
  File "./lfw.py", line 104, in getEmbeddings
    (x1, x2) = (embeddings[name1], embeddings[name2])
KeyError: 'Saeb_Erekat_0002'

**Comment by xiaofuguilala** [comment]
I meet the same problem.are you solved it?

**Comment by taureanamir** [comment]
@ramanjotkaur90 @xiaofuguilala ,

It is your image file names and your keynames are not matching, so the routine is not able to find the key. You need to remove .zfill from the method getEmbeddings() and try.
