### ISSUE TITLE
wget 1.19.2 segfault 11 causes models/get-models.sh to crash on macOS 10.13.1

### ISSUE THREAD

**Issue by jtlz2** [cmusatyalab/openface#332]
### Context of the issue.
[Provide more detailed introduction to the issue itself and why it is relevant]

openface installs fine, but when executing `models/get-models.sh` on macOS 10.13.1 wget segfaults (11), which causes get-models.sh to fall over, which renders openface of limited use.

### Expected behavior.
[Describe what you would expect to have resulted from this process.]

Script should download all dlib models or at least exit graciously.

### Actual behavior.
[Describe what you currently experience from this process, and thereby explain the bug.]

`wget --version`

GNU Wget 1.19.2 built on darwin17.3.0.

-cares +digest -gpgme +https +ipv6 +iri +large-file -metalink +nls 
+ntlm +opie -psl +ssl/openssl 

Wgetrc: 
    /usr/local/etc/wgetrc (system)
Locale: 
    /usr/local/Cellar/wget/1.19.2_1/share/locale 
Compile: 
    clang -DHAVE_CONFIG_H -DSYSTEM_WGETRC="/usr/local/etc/wgetrc" 
    -DLOCALEDIR="/usr/local/Cellar/wget/1.19.2_1/share/locale" -I. 
    -I../lib -I../lib -I/usr/local/opt/openssl@1.1/include -DNDEBUG 
Link: 
    clang -DNDEBUG -lidn2 -L/usr/local/opt/openssl@1.1/lib -lssl 
    -lcrypto -ldl -lz ftp-opie.o openssl.o http-ntlm.o ../lib/libgnu.a 
    -liconv -lintl -Wl,-framework -Wl,CoreFoundation -lunistring 

Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later
<http://www.gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Originally written by Hrvoje Niksic <hniksic@xemacs.org>.
Please send bug reports and questions to <bug-wget@gnu.org>.

`models/get-models.sh`

====================================================
Downloading dlib's public domain face landmarks model.
Reference: https://github.com/davisking/dlib-models

This will incur about 60MB of network traffic for the compressed
models that will decompress to about 100MB on disk.
====================================================

./get-models.sh: line 34: 89646 Segmentation fault: 11  wget -nv http://dlib.net/files/shape_predictor_68_face_landmarks.dat.bz2 -O dlib/shape_predictor_68_face_landmarks.dat.bz2
+ Error in wget.

Script does not continue - not all models are therefore downloadable using the script as is.

### Steps to reproduce.
[Present a minimal example and steps to produce the issue.]

brew install wget
cd openface
cd models
./get-models.sh

### OS and hardware information.

+ Operating system: macOS 10.13.1 High Sierra
+ Torch version: N/A
+ CPU architecture: Intel Core i7
+ GPU type (if using): Radeon Pro 450 2 GB, Intel HD Graphics 530 1536 MB

**Comment by Weijay** [comment]
same here

**Comment by dominicfollett** [comment]
I have been able to resolve this by upgrading wget to version 1.19.3:

`$ brew update wget`

MacOS Sierra 10.12.6
Intel Iris Graphics 6100 1536 MB

**Comment by bamos** [comment]
Thanks @dominicfollett!
