### ISSUE TITLE
Is this a "(mostly) Pure Python" project

### ISSUE THREAD

**Issue by DonaldTsang** [cmusatyalab/openface#340]
To Quote from http://cmusatyalab.github.io/openface/:  
`OpenFace is a Python and Torch implementation of face recognition with deep neural networks`  
So, why is the majority of the code in Lua instead of Python?

Side note: Is it possible to use this to convert images into vectors for custom image classifications,either as a built-in function, or as a an output vector that can be used as input in Keras NN?

**Comment by bamos** [comment]
When I wrote this, Lua/Torch was the best way to write the triplet learning.
