### ISSUE TITLE
Does this library provides incremental learning of my traning dataset ? 

### ISSUE THREAD

**Issue by MLDSBigGuy** [cmusatyalab/openface#341]
I  am using scikit knn classifier. But, Knn classifier does not come with incremental learning in scikit

why only knn is i am interested in getting the closest matches of my training data

If my only option is to use scikit incremental learning classifier algos, which is best one in terms of accuracy, fastness, scalability to huge datasets ?

**Comment by bamos** [comment]
No we don't provide this feature
