### ISSUE TITLE
Is there a python implementation of batch represent?

### ISSUE THREAD

**Issue by rexlow** [cmusatyalab/openface#342]
As per the title, is there a python implementation of batch represent? 

I am relatively new to lua and in the process of understanding how to create 128 facial embeddings with the codes in [batch-represent folder](https://github.com/cmusatyalab/openface/tree/master/batch-represent). 

I began to have some ideas of how it actually works by going through every single line of the code and I reckoned that it would be better if we have a python implementation. 

If there isn't any, I would be happy to port it and submit a PR.

Rex.

**Comment by bamos** [comment]
Sure I'll merge a python version if that's helpful to you or anybody else.

**Comment by laviua** [comment]
any updates?
