### ISSUE TITLE
problem with setup opencv and libd 

### ISSUE THREAD

**Issue by Hannabrahman** [cmusatyalab/openface#343]
Hello,

I am trying to follow your guide on OpenCV install,
I tries this command in build folder: cmake --build . --config Release
and I am getting this error: gmake: *** No targets specified and no makefile found. Stop.

I appreciate your help, thanksnt]

**Comment by bamos** [comment]
OpenCV can be difficult to install sometimes and I'm not sure what's going on here. Try searching in the OpenCV community and ask there if you can't find anything.

**Comment by Hannabrahman** [comment]
Hey,

thanks for getting back to me. Just in case is there any version working
with python 3?

Best,
Faeze

**Comment by Hannabrahman** [comment]
Hey Brandon,

My problem was resolved. However, I am wondering why when I try to align
the pictures, it does not align all the pictures. Say out of 202000, only
51000 will be aligned.
I tried on a different dataset and the folder I am getting have 933
pictures out of roughly 41000 picture dataset.


Best,
Faeze
