### ISSUE TITLE
include, PDM, and, PAW, in, openface.

### ISSUE THREAD

**Issue by EhsanOthman** [cmusatyalab/openface#344]
When I compiled FaceLandmarkImg code in the OpenFace project, an error appeared which is "C2039 'PDM': is not a member of 'FaceAnalysis' ". In fact, the included headers file include one PAW and one PDM, and the code calls two PAW and two PDM. FaceAnalyser includes PAW and PDM, and LandmarkDetector includes PAW and PDM. The PAW and PDM header files in FaceAnalyser is overwritten.

### Context of the issue.
[Provide more detailed introduction to the issue itself and why it is relevant]

### Expected behavior.
[Describe what you would expect to have resulted from this process.]

### Actual behavior.
[Describe what you currently experience from this process, and thereby explain the bug.]

### Steps to reproduce.
[Present a minimal example and steps to produce the issue.]

### OS and hardware information.

+ Operating system: [todo]
+ Torch version: [todo]
+ CPU architecture: [todo]
+ GPU type (if using): [todo]

**Comment by bamos** [comment]
This is the wrong openface project, you should submit your issue to https://github.com/TadasBaltrusaitis/OpenFace
