### ISSUE TITLE
MINMAX_TEMPLATE Discussion in align_dlib.py

### ISSUE THREAD

**Issue by rexlow** [cmusatyalab/openface#345]
I am trying to understand the  face alignment for my academic study. 

I was studying the `align_dlib.py` code and I have a few questions about the constant `MINMAX_TEMPLATE`.

According to my understanding, as faces might move from one coordinate to another in one frame. Hence, the resulting coordinate matrix would express different numerical ranges. However, the relationships between the coordinates will be similar in both matrices so some information is present in a location invariant form, meaning it is the same no matter where in the picture my face is.

Correct me if I am wrong, `MINMAX_TEMPLATE` is use to normalise the coordinates between 0 - 1 in order to remove the numerical differences of faces appear in different places.

But, how do you come out with the `TEMPLATE` array? Was it randomised? Or there is a background study?

Best regards,
Rex.

**Comment by bamos** [comment]
Hi, it's great you're further looking into the code and implementation! I computed the template by averaging the landmarks on a dataset of faces.

**Comment by rexlow** [comment]
Thanks for the clarification!

**Comment by rexlow** [comment]
@bamos Can you tell me which dataset was the template based on? I am trying to recreate the template and do some accuracy testing. It would be better if you could provide me the script that you used to compute the template.

Best regards,
Rex.
