### ISSUE TITLE
Got error in comparison.py

### ISSUE THREAD

**Issue by Alamincse12** [cmusatyalab/openface#348]
I installed OpenFace by hand in ubuntu 14.04
Now , how can i run the demo code(comparison.py)?
I was placed the comparison.py in the home directory.
And run the code in the home directory.
I got Error.
Traceback (most recent call last):
  File "comparison.py", line 33, in <module>
    import openface
ImportError: No module named openface 
![error1](https://user-images.githubusercontent.com/36919917/36785931-96b474a6-1c52-11e8-93fe-a26ce162a42c.png)
![error1](https://user-images.githubusercontent.com/36919917/36785954-aaa2655e-1c52-11e8-8457-34f923998765.png)

**Comment by bamos** [comment]
It looks like openface isn't installed. Make sure you've followed all of the steps in the setup guide, and that the python you're using to run this here is the same version of python that you've installed openface to.

-Brandon.

**Comment by vtslab** [comment]
Did you set your PYTHONPATH?

`export PYTHONPATH=~/openface`
