### ISSUE TITLE
About improving the demo "classifier.py"

### ISSUE THREAD

**Issue by LiuYangICV** [cmusatyalab/openface#352]
I modified the demo "classifier.py" so that it can recognize many pictures at once.
But at the same time there is such a problem:

************************************************************
Traceback (most recent call last):
  File "main.py", line 52, in <module>
    movieDic = classifier.inferFace(imgPath)
  File "/xxxxx/OpenFace/openface/demos/classifier.py", line 289, in inferFace
    reps = getRep_2(imgpath)
  File "/xxxxx/OpenFace/openface/demos/classifier.py", line 323, in getRep_2
    net = openface.TorchNeuralNet('/home/hwy/dachuang/OpenFace/openface/demos/../models/openface/nn4.small2.v1.t7', imgDim=96,cuda=False)
  File "/usr/local/lib/python2.7/dist-packages/openface/torch_neural_net.py", line 84, in __init__
    self.p = Popen(self.cmd, stdin=PIPE, stdout=PIPE, bufsize=0, universal_newlines=True)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1215, in _execute_child
    errpipe_read, errpipe_write = self.pipe_cloexec()
  File "/usr/lib/python2.7/subprocess.py", line 1167, in pipe_cloexec
    r, w = os.pipe()
OSError: [Errno 24] Too many open files
********************************************************************

The modified demo is as follows:

`
def inferFace(picsPath):
    classifierModel = '../OpenFace/openface/generated-embeddings/classifier.pkl'
    with open(classifierModel, 'rb') as f:
        if sys.version_info[0] < 3:
                (le, clf) = pickle.load(f)
        else:
                (le, clf) = pickle.load(f, encoding='latin1')
    movieDic = []
    imgs = os.listdir(picsPath)
   
    shotDic = {'Num.':'','Actor':[]}
    
    imgs.sort()
    for img in imgs:
        actDic = {'Name':'','Confidence':''}

        imgpath = picsPath+"/"+img
        shotNum = re.findall('.*?(?=_)',img)
        if(shotNum[0] != shotDic['Num.']):
            if (shotNum[0] != '00001'):
                tempDic_2 = {'Num.':shotDic['Num.'],'Actor':shotDic['Actor']}
                movieDic.append(tempDic_2)
            shotDic['Num.'] = shotNum[0]
            shotDic['Actor'] = []
        print("\n=== {} ===".format(imgpath))
        reps = getRep_2(imgpath)
        if len(reps) > 1:
            print("List of faces in image from left to right")
        if len(reps) > 0:
            for r in reps:
                temp = []
                rep = r[1].reshape(1, -1)
                bbx = r[0]
                predictions = clf.predict_proba(rep).ravel()
                maxI = np.argmax(predictions)
                person = le.inverse_transform(maxI)
                confidence = predictions[maxI]
                print("Predict {} @ x={} with {:.2f} confidence.".format(person.decode('utf-8'), bbx,confidence))
                for actor in shotDic['Actor']:
                    temp += list(actor.values())
                if person.tostring() in temp:
                    cnt = 0
                    for t in temp:
                        if person.tostring() == t:
                            if float(confidence) > float(temp[cnt-1]):
                                shotDic['Actor'][cnt/2]['Confidence'] = confidence
                        cnt += 1
                else:
                    actDic['Name'] = person.tostring()
                    actDic['Confidence'] = confidence
                    tempDic = {"Name":actDic['Name'],"Confidence":actDic['Confidence']}
                    shotDic['Actor'].append(tempDic)
        if(img == imgs[-1]):
            movieDic.append(shotDic)
    return movieDic

def getRep_2(imgPath):
    
    align = openface.AlignDlib('/home/hwy/dachuang/OpenFace/openface/demos/../models/dlib/shape_predictor_68_face_landmarks.dat')
    net = openface.TorchNeuralNet('/home/hwy/dachuang/OpenFace/openface/demos/../models/openface/nn4.small2.v1.t7', imgDim=96,cuda=False)
    
    bgrImg = cv2.imread(imgPath)
    if bgrImg is None:
        raise Exception("Unable to load image: {}".format(imgPath))

    rgbImg = cv2.cvtColor(bgrImg, cv2.COLOR_BGR2RGB)

    bbs = align.getAllFaceBoundingBoxes(rgbImg)
    
    if len(bbs) == 0 or (not True and bb1 is None):
        print("Unable to find a face: {}".format(imgPath))

    reps = []
    
    if len(bbs) > 0:
        for bb in bbs:
            alignedFace = align.align(
                96,
                rgbImg,
                bb,
                landmarkIndices=openface.AlignDlib.OUTER_EYES_AND_NOSE)
            if alignedFace is None:
                raise Exception("Unable to align image: {}".format(imgPath))

            rep = net.forward(alignedFace)
            reps.append((bb.center().x, rep))
        sreps = sorted(reps, key=lambda x: x[0])
        return sreps
    else:
        return reps
`

How can I solve this problem?
Looking forward to getting your solution sincerely.

**Comment by xugaoxiang** [comment]
@LiuYangICV you should open the file beyond the func inferFace.
