### ISSUE TITLE
video window not responding when classifier_webcam.py connect to RTSP streaming

### ISSUE THREAD

**Issue by xugaoxiang** [cmusatyalab/openface#363]
### Context of the issue.
I use the demo classifier_webcam.py to connect a IP camera(rtsp), cv2.imshow works, but window crashed after a few seconds.

### Expected behavior.
calculate the face confidence in the video like a usb camera smoothly.

### Steps to reproduce.
just change 

video_capture = cv2.VideoCapture(args.captureDevice)

to

video_capture = cv2.VideoCapture("rtsp://admin:12345678@10.1.1.12:554/streaming/channels/102")

### OS and hardware information.

+ Operating system: [ubuntu 16.04 desktop 64bit]
+ Torch version: [torch7]
+ CPU architecture: [core i5]
+ GPU type (if using): [No]

**Comment by jesen8** [comment]
I have the same question now!and need a answer.thanks
