### ISSUE TITLE
Add expected output of running the example in setup

### ISSUE THREAD

**Issue by Dyex719** [cmusatyalab/openface#366]
Step 4 from https://cmusatyalab.github.io/openface/setup/ gives an example to ensure that openface is running properly. However, the expected output of running `./demos/classifier.py infer models/openface/celeb-classifier.nn4.small2.v1.pkl ./images/examples/carell.jpg` is not mentioned.

**Comment by xugaoxiang** [comment]
@Dyex719 error message?

**Comment by Dyex719** [comment]
Not an error, just a helpful message to tell the user that everything is working properly. I think this would be helpful to the end user to know that the setup has completed successfully.

**Comment by kaisark** [comment]
Predict SteveCarell with 0.99 confidence.
