### ISSUE TITLE
What are the difference between OpenFace and openface?

### ISSUE THREAD

**Issue by jiapei100** [cmusatyalab/openface#373]
Hi:

Just wonder what are the differences between [https://github.com/cmusatyalab/openface](https://github.com/cmusatyalab/openface) and [https://github.com/TadasBaltrusaitis/OpenFace](https://github.com/TadasBaltrusaitis/OpenFace) ?

Cheers

**Comment by ChrizzyM87** [comment]
These are two completely different Libraries!
cmusatyalab openface is a face recognition library.
baltrusaitis OpenFace aims at facial landmark detection, head pose estimation, facial action unit recognition, and eye-gaze estimation.
