### ISSUE TITLE
i can't install dlib and face_recognition on python 2, i used win 7

### ISSUE THREAD

**Issue by etherNDr** [cmusatyalab/openface#379]
https://help.github.com/articles/basic-writing-and-formatting-syntax/
![error](https://user-images.githubusercontent.com/42597262/44442416-44d5bd00-a5fc-11e8-8846-94dbb399f7db.png)

     
can u help me fix it

**Comment by thayannevls** [comment]
hey @etherNDr 

Are you still having this issue? Can you show the steps you followed do install *dlib*? And did you try to install Cmake too?
