### ISSUE TITLE
"module 'graphicsmagick' not found:" when training DNN model

### ISSUE THREAD

**Issue by weihua04** [cmusatyalab/openface#380]
i'd like to train the DNN with my own datasets. so i "run training/main.lua to start training the model".
the  mistake as follows: (i have installed graphicsmagick,but still didn't work )

"/root/torch/install/bin/luajit: /root/torch/install/share/lua/5.1/threads/threads.lua:183: [thread 1 callback] /root/src/openface/openface/training/donkey.lua:10: module 'graphicsmagick' not found:
	no field package.preload['graphicsmagick']
	no file '/root/.luarocks/share/lua/5.1/graphicsmagick.lua'
	no file '/root/.luarocks/share/lua/5.1/graphicsmagick/init.lua'
	no file '/root/torch/install/share/lua/5.1/graphicsmagick.lua'
	no file '/root/torch/install/share/lua/5.1/graphicsmagick/init.lua'
	no file './graphicsmagick.lua'
	no file '/root/torch/install/share/luajit-2.1.0-beta1/graphicsmagick.lua'
	no file '/usr/local/share/lua/5.1/graphicsmagick.lua'
	no file '/usr/local/share/lua/5.1/graphicsmagick/init.lua'
	no file '/root/torch/install/lib/graphicsmagick.so'
	no file '/root/.luarocks/lib/lua/5.1/graphicsmagick.so'
	no file '/root/torch/install/lib/lua/5.1/graphicsmagick.so'
	no file './graphicsmagick.so'
	no file '/usr/local/lib/lua/5.1/graphicsmagick.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'"

**Comment by lixiang123321** [comment]
Try install graphicsmagick.
May work.
