### ISSUE TITLE
'No module named openface' on running in Debug mode in Spyder

### ISSUE THREAD

**Issue by toofo** [cmusatyalab/openface#389]
Hello,

I am running code from [this example](https://gist.github.com/ageitgey/63304fce6963cddec800afac5e3b065e) . Everything works perfectly when I launch align of ./util/align-dlib.py from command line. However, when I am debugging "util/align-dlib" from Spyder I have:
it falls on line
`import openface`
With error
 'No module named openface'

Is there some way to hardcode the reference to openface? 

Thanks!

**Comment by mrgloom** [comment]
Looks like setup instructions are here, it will be good to add link to them in the github repo too.
http://cmusatyalab.github.io/openface/setup/
