### ISSUE TITLE
i have problem like this "Error fetching video from webcam"

### ISSUE THREAD

**Issue by nakhonsoft** [cmusatyalab/openface#397]
[https://i.pinimg.com/originals/4a/06/89/4a06894922f37c87c3a1e265b9c46f77.png](url)

**Please help me**

**Comment by nakhonsoft** [comment]
open url on opera browser 

[https://i.pinimg.com/originals/f8/82/0f/f8820f9d05777f6c4563f46b6709828b.png](url)

**Comment by angelinux** [comment]
I solved this problem in Chrome by changing the function umSuccess(stream) in openface-demo.js with the following content:
```
function umSuccess(stream) {
    if (vid.mozCaptureStream) {
        vid.mozSrcObject = stream;
    } else {
        vid.srcObject = stream;
    }
    vid.play();
    vidReady = true;
    sendFrameLoop();
} 
```

In Firefox, by the way, I get only a black screen.

**Comment by angelinux** [comment]
Update: the black screen problem with Firefox can be solved by rewriting the function umSuccess as:

```
function umSuccess(stream) {
    vid.srcObject = stream;
    vid.play();
    vidReady = true;
    sendFrameLoop();
}
```

**Comment by karllacr** [comment]
hi,
did you just modify the code and used the 'docker run' normally, or did you do some update in dockerfile?

**Comment by angelinux** [comment]
I changed the file inside the docker container through a bash session.

**Comment by karllacr** [comment]
Hi again,
Sorry to bother you, but could you please show me the steps you followed until you were able to use the web demo. I've been trying for a long time and I've modified the file as you showed it, but I can not do it at all.

**Comment by nakhonsoft** [comment]
I changed to face_recognition already

https://github.com/ageitgey/face_recognition

#database and webcam

https://github.com/vearutop/face-postgre
https://github.com/vearutop/face-postgre/issues/7

**Comment by nakhonsoft** [comment]
I changed to face_recognition already

https://github.com/ageitgey/face_recognition

database and webcam

>https://github.com/vearutop/face-postgre
>https://github.com/vearutop/face-postgre/issues/7

**Comment by angelinux** [comment]
@karllacr: you should launch docker container as docker run ... ending with /bin/bash, then you will find a prompt where you can modify the file with vi and then execute openface/demos/web/start_servers.sh

**Comment by angelinux** [comment]
@nakhonsoft: thank you, I will give a try, I was searching for a python 3 implementation!

**Comment by nakhonsoft** [comment]
@angelinux face_recognition

support py2 and p3

**Comment by ideallyworld** [comment]
> Hi again,
> Sorry to bother you, but could you please show me the steps you followed until you were able to use the web demo. I've been trying for a long time and I've modified the file as you showed it, but I can not do it at all.

You need restart the browser after all changed .  I also meet the same black problem . And This is fixed by angelinux's comment.

**Comment by nakhonsoft** [comment]
> > สวัสดีอีกครั้ง
> > ขออภัยที่รบกวนคุณ แต่โปรดช่วยแสดงขั้นตอนที่คุณทำตามที่ฉันทำจนกว่าคุณจะสามารถใช้เว็บตัวอย่างได้ ฉันลองมานานแล้วและฉันได้แก้ไขไฟล์ตามที่คุณแสดง แต่ฉันไม่สามารถทำได้เลย
> 
> คุณต้องรีสตาร์ทเบราว์เซอร์หลังจากการเปลี่ยนแปลงทั้งหมด ฉันยังพบปัญหาสีดำเหมือนกัน และนี่คือการแก้ไขโดยความคิดเห็นของ angelinux

you try test in opera browser

**Comment by chandancolab** [comment]
thanks @angelinux

**Comment by Chappie74** [comment]
> Update: the black screen problem with Firefox can be solved by rewriting the function umSuccess as:
> 
> ```
> function umSuccess(stream) {
>     vid.srcObject = stream;
>     vid.play();
>     vidReady = true;
>     sendFrameLoop();
> }
> ```

Thank you brother.
