### ISSUE TITLE
Error running util/prune-dataset.py

### ISSUE THREAD

**Issue by davidglivar** [cmusatyalab/openface#40]
When running the following command on a set of aligned images

```
$ ./util/prune-dataset.py data/test/aligned/ --numImagesThreshold 2
```

The following error is reported:

```
Traceback (most recent call last):
  File "./util/prune-dataset.py", line 27, in <module>
    if nImgs < args.numImagesThreshold:
TypeError: unorderable types: int() < str()
```

**Solution**:

On line 12 of 'util/prune-dataset.py', change `str` to `int`

**Comment by maximus009** [comment]
Change it to <code>int(args.numImagesThreshold):</code>

The error was gone when I did that.

**Comment by bamos** [comment]
Thanks, fixed!
