### ISSUE TITLE
Training appears to have CUDA dependency

### ISSUE THREAD

**Issue by davidglivar** [cmusatyalab/openface#41]
There seems to be references to `cutorch` and `cunn` in the training directory. This is problematic when running the docker container.

Full trace to document the issue:

```
root@c0280b956f59:/openface# ./training/main.lua -data data/test/aligned/
/root/torch/install/bin/luajit: /root/torch/install/share/lua/5.1/trepl/init.lua:363: module 'cutorch' not found:No LuaRocks module found for cutorch
        no field package.preload['cutorch']
        no file '/root/.luarocks/share/lua/5.1/cutorch.lua'
        no file '/root/.luarocks/share/lua/5.1/cutorch/init.lua'
        no file '/root/torch/install/share/lua/5.1/cutorch.lua'
        no file '/root/torch/install/share/lua/5.1/cutorch/init.lua'
        no file './cutorch.lua'
        no file '/root/torch/install/share/luajit-2.1.0-alpha/cutorch.lua'
        no file '/usr/local/share/lua/5.1/cutorch.lua'
        no file '/usr/local/share/lua/5.1/cutorch/init.lua'
        no file '/root/.luarocks/lib/lua/5.1/cutorch.so'
        no file '/root/torch/install/lib/lua/5.1/cutorch.so'
        no file './cutorch.so'
        no file '/usr/local/lib/lua/5.1/cutorch.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'error'
        /root/torch/install/share/lua/5.1/trepl/init.lua:363: in function 'require'
        ./training/main.lua:4: in main chunk
        [C]: in function 'dofile'
        /root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:133: in main chunk
        [C]: at 0x00406670
```

Is there a way to train a new model without CUDA? If there is not, perhaps it would be best to specify in the readme that CUDA is indeed needed for training.

**Comment by bamos** [comment]
Thanks @davidglivar - I've added a note to the README that the training code assumes CUDA is installed and I'd be happy to merge a PR that adds a cuda option to the training code, should just be a few conditional statements. However, training is so computationally expensive that I'd expect training a model on the CPU to take 100 days, maybe more.

**Comment by davidglivar** [comment]
thanks @bamos - I might check out what it will take to run it with a cuda option. Definitely a solid assumption that most devs will want to toss those processes onto the gpu, however, the specific needs I have right now is a for smaller dataset with incompatible hardware. Will open a PR if I make any progress.
