### ISSUE TITLE
Error occurred when running Real-time web demo on latest Chrome

### ISSUE THREAD

**Issue by gtbl2012** [cmusatyalab/openface#415]
### Context of the issue.
Chrome has deprecated the `createObjectURL` function(in `web/js/openface-demo.js` line 239). In that case, the demo shows `Error fetching video from webcam` when running in the latest Chrome.

### Actual behavior.
the demo shows `Error fetching video from webcam` when running in the latest Chrome.

### Steps to reproduce.
Just run it in latest Chrome.

### Possible solution(worked in lateset Chrome)
Changing line 239
`vid.src = (window.URL && window.URL.createObjectURL(stream)) ||
            stream;`
to
`vid.srcObject = stream;`
**but it may cause problem in older Chrome version.**

### OS and hardware information.

+ Chrome version: [74.0.3729.169]
+ Operating system: [Not Related]
+ Torch version: [Not Related]
+ CPU architecture: [Not Related]
+ GPU type (if using): [Not Related]

**Comment by piwodlaiwo** [comment]
I believe this should be closed as line 239 is now vid.srcObject = stream;
