### ISSUE TITLE
ImportError: No module named grid_search

### ISSUE THREAD

**Issue by nsivaramakrishnan** [cmusatyalab/openface#421]
### Context of the issue.
grid_search import error while running classifier.py

### Expected behavior.
The image should get classified properly

### Actual behavior.
The following error is shown:
ImportError: No module named grid_search

### Steps to reproduce.
Performed the installation as mentioned in https://cmusatyalab.github.io/openface/setup/#installing-open-face-using-conda-osx-and-gnulinux.

(openface) user1@user1-GPU3:~/facereco/openface$ ./demos/classifier.py infer models/openface/celeb-classifier.nn4.small2.v1.pkl ./images/examples/carell.jpg
Traceback (most recent call last):
  File "./demos/classifier.py", line 43, in <module>
    from sklearn.grid_search import GridSearchCV
ImportError: No module named grid_search

### OS and hardware information.

+ Operating system: Ubuntu 16.04
+ Torch version: Latest checked-out code
+ CPU architecture: Intel 4 Core
+ GPU type (if using): GeForce GTX 1060

**Comment by jaharkes** [comment]
Looks like they moved GridSearchCV to a different module. I haven't tried this, but maybe try

```
from sklearn.model_selection import GridSearchCV
```

https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html#sklearn.model_selection.GridSearchCV

**Comment by nsivaramakrishnan** [comment]
Thanks for the insight. Even after changing this in classifier.py, it fails while trying to load using pickle where the same class gets loaded.

**Comment by jaharkes** [comment]
Yeah, that is a problem with pickled things in python. You would have to roll back to an earlier version of scikit learn that hasn't changed the data structures around.

**Comment by chuong-phung** [comment]
You should use scikit-learn version: 0.17.1
by the following commands:
- Uninstall scikit-learn: pip uninstall scikit-learn
- Install scikit-learn: pip install scikit-learn==0.17.1
