### ISSUE TITLE
Licence issue

### ISSUE THREAD

**Issue by corentin87** [cmusatyalab/openface#426]
Hi,
You are saying OpenFace can be use for commercial purposes (Apache 2.0 license). But In your code you are using the 68 face landmarks descriptor from DLIB which is not matching this license. I found a statement saying this file is not for [commercial use](https://github.com/davisking/dlib-models) 

> The license for this dataset excludes commercial use and Stefanos Zafeiriou, one of the creators of the dataset, asked me to include a note here saying that the trained model therefore can't be used in a commercial product.

It seems there is a conflict here. But the 5 face landmarks descriptor can be used for commercial use.

Cheers,

**Comment by lefem1** [comment]
I’m the real owner of this account , I’m just gonna have to close this
hacked email

**Comment by lefem1** [comment]
I have no idea what this email is about I will be presenting this to the
police department.

**Comment by bamos** [comment]
Thanks for pointing this out, I just added a reference to this in the licensing section of the README -- https://github.com/cmusatyalab/openface/commit/92d61fdd53e6e2a01d0b73bc32f5db8a93271e4d

**Comment by neeraj-21** [comment]
> Hi,
> You are saying OpenFace can be use for commercial purposes (Apache 2.0 license). But In your code you are using the 68 face landmarks descriptor from DLIB which is not matching this license. I found a statement saying this file is not for [commercial use](https://github.com/davisking/dlib-models)
> 
> > The license for this dataset excludes commercial use and Stefanos Zafeiriou, one of the creators of the dataset, asked me to include a note here saying that the trained model therefore can't be used in a commercial product.
> 
> It seems there is a conflict here. But the 5 face landmarks descriptor can be used for commercial use.
> 
> Cheers,

Hello @corentin87 and @bamos  from the comment above and looking at the link                                               
https://github.com/davisking/dlib-models                                                                                                                                           
I understand that the dlib pretrained 68 face landmarks descriptor model can't be used to build a commercial product but 5 face landmarks descriptor model can be used (correct me if I'm wrong) If this is correct suppose someone wants to build a product using this can he/she sell it directly or needs some prior permission (written / via email etc.) Any insights / description / links regarding this will be much appreciated. Are there online tools available for verifying if some repo license permits commercial use ? Thank you in advance. Also are there any commercial products built out of the pretrained models used in openface library  OR openface lib itself
