### ISSUE TITLE
ok I have already solved it by copying the shape_predictor_68_face_landmarks.dat file in the same directory as my python file. Thanks.

### ISSUE THREAD

**Issue by messi10hitu** [cmusatyalab/openface#433]
ok I have already solved it by copying the shape_predictor_68_face_landmarks.dat file in the same directory as my python file. Thanks.

_Originally posted by @RaynerPailus in https://github.com/cmusatyalab/openface/issues/404#issuecomment-471245863_

**Comment by Himanshu2818040** [comment]
> ok I have already solved it by copying the shape_predictor_68_face_landmarks.dat file in the same directory as my python file. Thanks.
> 
> _Originally posted by @RaynerPailus in [#404 (comment)](https://github.com/cmusatyalab/openface/issues/404#issuecomment-471245863)_

but how to do it. I'm  new to it.
