### ISSUE TITLE
Windows installation problems 

### ISSUE THREAD

**Issue by L5mp** [cmusatyalab/openface#438]
Hi!

I am trying to install everything in windows but I am unable, it gives me a lot of problems with python, could someone who has done it tell me the steps that he has followed? thanks!

**Comment by Kataphractoi** [comment]
I don't know how to install this. could some one please help.

**Comment by mjan2021** [comment]
Issue with 'th' command since its doesnt work in windows. Is there any workaround to that?

thank you
