### ISSUE TITLE
I cannot find the nn4.small2.v1.t7 in the models file

### ISSUE THREAD

**Issue by chen-311** [cmusatyalab/openface#439]
### Context of the issue.
[Provide more detailed introduction to the issue itself and why it is relevant]

### Expected behavior.
[Describe what you would expect to have resulted from this process.]

### Actual behavior.
[Describe what you currently experience from this process, and thereby explain the bug.]

### Steps to reproduce.
[Present a minimal example and steps to produce the issue.]

### OS and hardware information.

+ Operating system: [todo]
+ Torch version: [todo]
+ CPU architecture: [todo]
+ GPU type (if using): [todo]

**Comment by GoutamKelam** [comment]
In the models folder there will be get-models.sh file run the file as follows:
`bash get-models.sh`
