### ISSUE TITLE
RuntimeError: Unable to open shape_predictor_68_face_landmarks.dat .......i have tried to put this in the same directory also....and downloaded latest version and uncompressed it and still this issue is not getting solved. Please Help

### ISSUE THREAD

**Issue by vikramadityaw01** [cmusatyalab/openface#449]
![ss](https://user-images.githubusercontent.com/91077592/158317059-bf92c46f-11fc-4aa6-ac90-737a1ef9bc76.png)

**Comment by SirZexx** [comment]
I faced  the same issue tomorrow and I found that you just have to download that dat file an place it in your project folder with python file. the link is : [http://dlib.net/files/shape_predictor_68_face_landmarks.dat.bz2](http://dlib.net/files/shape_predictor_68_face_landmarks.dat.bz2)    , just download it and extract it and re-run the program it should be fine.

**Comment by boogaming** [comment]
Use pyinstaller -c PyFileName.py (with console) or pyinstaller -w PyFileName.py (without console) instead of pyinstaller --onefile PyFileName.py. Then add folder containing face_recognition models .dat files. Example, "face_recognition_models/models/shape_predictor_68_face_landmarks.dat" in the same folder of the executable file.

**Comment by sahil06habile** [comment]
> Use pyinstaller -c PyFileName.py (with console) or pyinstaller -w PyFileName.py (without console) instead of pyinstaller --onefile PyFileName.py. Then add folder containing face_recognition models .dat files. Example, "face_recognition_models/models/shape_predictor_68_face_landmarks.dat" in the same folder of the executable file.

what will be the file structure if i am adding "face_recognition_models/models/shape_predictor_68_face_landmarks.dat" in code. Because i added this file as binary but exe file still showing the same error.
