### ISSUE TITLE
in the compare.py what should i add in the path of Torch network model

### ISSUE THREAD

**Issue by anthonyab30** [cmusatyalab/openface#452]
### Context of the issue.
[Provide more detailed introduction to the issue itself and why it is relevant]

### Expected behavior.
[Describe what you would expect to have resulted from this process.]

### Actual behavior.
[Describe what you currently experience from this process, and thereby explain the bug.]

### Steps to reproduce.
[Present a minimal example and steps to produce the issue.]

### OS and hardware information.

+ Operating system: [todo]
+ Torch version: [todo]
+ CPU architecture: [todo]
+ GPU type (if using): [todo]

**Comment by aleeasdas** [comment]
@anthonyab30   请问in the compare.py what should i add in the path of Torch network model这个问题解决了吗，可以给一下运行代码的示例吗
