### ISSUE TITLE
Speed-up Training

### ISSUE THREAD

**Issue by melgor** [cmusatyalab/openface#49]
I was thinking about speeding up learning process. I think that in current version of code too many forward propagation is done for each triplet. So far the process looks like that:
1. Get batch 
2. Forward all batch, get embeddings
3. Choose randomly anchor and positive example
4. Based on embeddings, choose negative example
5. Create pairs of triplet
6. In OptimTriplet, forward again all the examples, some of the images even more that ones (as the occur  in several triplets)

I think, that it is possible to process the data less time. We can calculate, that for batch size=100, we process 400 images (100 for emb, 300 for learning).The idea is taken from here: https://github.com/Atcold/torch-TripletEmbedding/blob/master/data/data-test.lua , commented code at the bottom of file. 

So, the idea is following:
1. Firstly choose randomly positive images for each anchor.
2. Then, using <code> model.module[1].forward[anchors] </code> process anchor images and positive (for positive change module from 1 to 2). As I understand torch, the model will remember value in each layer, which will be used for backward propagation. 
3. Having emending for anchor images,  choose negative images.
4. Process it by <code> model.module[3] </code>
5. Then, the OptimTriplet does not do forward propagation of data (we provide all embedding for anchor, positive and negative), just only forward by criterion and all backward.

This is not maybe great speed up, but reduce computation from 400 to 300, so it is 25% faster.

Do you think, that my idea is correct?

**Comment by bamos** [comment]
Hi @melgor - good idea. The redundant forward passes made initial prototyping much simpler and we can reduce the training time by getting rid of them.

Your idea seems reasonable but may have some implementation complexities, such as:

1. The current redundant passes cleanly maximize the mini-batch size for the triplets between the offline samplings by using different anchors and positives in the same mini-batch. To maximize the mini-batches with your idea, you either need to sample exactly the same number of images per person (which may require many images per person, I'm currently not doing this), or you'll need to overlap people in the mini-batches.

2. I can see how after the first person is processed, the results from the anchors and positives can be saved as negatives for the other people in the mini-batch. However, it seems like you still need to redundantly go through some (not all) negatives by making multiple passes with `model.module[3]` for the first person to select semi-hard negatives.

-Brandon.
