### ISSUE TITLE
Error getting result from Torch subprocess

### ISSUE THREAD

**Issue by Strateus** [cmusatyalab/openface#54]
Error getting result from Torch subprocess.

Line read: 

Exception:

could not convert string to float: 

============

stdout: 

============

stderr: /root/torch/install/bin/luajit: inconsistent tensor size at /root/torch/pkg/torch/lib/TH/generic/THTensorCopy.c:7
stack traceback:
        [C]: at 0x7fc6874ae020
        [C]: in function '__newindex'
        /root/openface/openface/openface_server.lua:63: in main chunk
        [C]: in function 'dofile'
        /root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:133: in main chunk
        [C]: at 0x00406670

This happens with attached picture (when align fails).
![last](https://cloud.githubusercontent.com/assets/5196895/11178125/ac3a0586-8c5b-11e5-80d6-9efc7bc2298d.jpg)

**Comment by Strateus** [comment]
Actually this one
![modified](https://cloud.githubusercontent.com/assets/5196895/11178263/b704570e-8c5c-11e5-8fc9-21e69f891493.jpg)

**Comment by Strateus** [comment]
Its because 96x95?

**Comment by bamos** [comment]
Hi @Strateus - what commands are you running? I'm just an `unable to align` error.

```
openface(master*)$ wget https://cloud.githubusercontent.com/assets/5196895/11178263/b704570e-8c5c-11e5-8fc9-21e69f891493.jpg -O issue54.jpg --quiet
openface(master*)$ ./demos/classifier.py infer ./models/openface/celeb-classifier.nn4.v1.pkl ./issue54.jpg
Warning: Unable to align and crop to the face's bounding box.
Traceback (most recent call last):
  File "./demos/classifier.py", line 158, in <module>
    infer(args)
  File "./demos/classifier.py", line 104, in infer
    rep = getRep(args.img)
  File "./demos/classifier.py", line 65, in getRep
    raise Exception("Unable to align image: {}".format(imgPath))
Exception: Unable to align image: ./issue54.jpg
```

**Comment by Strateus** [comment]
yes, it happened because i pushed this image with original shape (ie 96x95x3) after align failed, that caused this error.
