### ISSUE TITLE
Need Clarification on Openface

### ISSUE THREAD

**Issue by gopi1989** [cmusatyalab/openface#57]
Hi @all
Just now i gone through the OpenFace Documentation
I need some clarification,
1.It is a 100% opensource or not
2.It is Possible to use the OpenFace for FaceAuthenticaion Application
3.What about Accuracies?
4.What is the Purpose of Using Torch
Please anyone can provide information for me.Because i am exploring on Openface my friends

**Comment by sschnug** [comment]
Just a few remarks by some other newbie :-)

1. Well. Define open-source! Licenses are complicated stuff, but the [doc](http://cmusatyalab.github.io/openface/) lists all the different ones for different parts of this project! Now it's up to you to decide if you may use these in your project!

2. No idea :-/.

3. There are some accuracies given in the [doc](http://cmusatyalab.github.io/openface/accuracy/). Face-recognition seems to be all about data-sets (therefore some common sets are used to compare different approaches) so this numbers won't tell you much abour your use-case (besides the fact, that this approach approaches the state-of-the-art)

4. Torch is a very common library for implementing Deep Learning. There are others (which might have some advantages and disadvantages) but the author decided (i can't give you any hints but i think torch seems to be more mature than some others like lasagne/keras and co.) to use this one which results in a project which mixes (at least) Lua, C++ and Python.

**Comment by bamos** [comment]
Great response @sschnug - thanks!

**Comment by gopi1989** [comment]
Hi,
@sschnug ,@bamos. I understand,hereafter i will follow your points.

Thanks for your valuable Reply!
