### ISSUE TITLE
Web/demo testing Issues

### ISSUE THREAD

**Issue by gopi1989** [cmusatyalab/openface#58]
Hi bamos,

I tried to test the web/demo of Openface face-recognition system.Facing Web socket issues.

My Environment:

Ubuntu 14.04 32 bit Operating System.

Steps I done:

1. Followed the Instruction from the Link: "http://cmusatyalab.github.io/openface/demo-1-web/".

2. Then followed the "Setup Guide" and installed all the libraries to test the Openface Algorithm.

3. Then open the terminal and run the "./install-deps.sh","sudo pip install -r requirements.txt" from the web/demo folder.

4. Then i start the server by using the command "python server.py" from web/demo folder.

5. Then i run the command "python2 -m SimpleHTTPServer 8000" in the terminal.

6. Then i connected the webcamera and open the browser and typed "localhost:8080",then demo application is opened.Then started Testing.

7. I didn't do any changes in the "index.html" file.

8. I noted the log in terminal "Received FRAME message of length 12322".The log is printing for continuous and then throws an exception.

9. I attached the log file for "python server.py" and "python2 -m SimpleHTTPServer 8000" commands in the terminal.

10. One more doubt ,I want to use this code for my application.It is possible or not?

Please apologize for my bad English,Thanks in advance for your valuable help!!!

[python server.py_log.txt](https://github.com/cmusatyalab/openface/files/41629/python.server.py_log.txt)

[python2 -m SimpleHTTPServer 8000_log.txt](https://github.com/cmusatyalab/openface/files/41638/python2.-m.SimpleHTTPServer.8000_log.txt)

**Comment by bamos** [comment]
Hi @gopi1989 - the issue tracker is for bug tracking and development discussions. To help future users with similar setup issues, can you repost this to our mailing list at https://groups.google.com/forum/#!forum/cmu-openface? Happy to help you there.

-Brandon.

**Comment by gopi1989** [comment]
Of Course Brandon! thank you
