### ISSUE TITLE
Unlabeled training with datasets like megaface

### ISSUE THREAD

**Issue by mrgloom** [cmusatyalab/openface#6]
For larger datasets you can request http://megaface.cs.washington.edu/

**Comment by bamos** [comment]
Thanks for the reference! Training new models with megaface would be interesting, but the current training with triplet loss can't be used because the images aren't labeled.

**Comment by mrgloom** [comment]
What status of this ussue?  On what data OpenFace trained?

**Comment by bamos** [comment]
We can't train on megaface directly since they don't provide labels. We train on CASIA+FaceScrub, the two largest labeled datasets I'm aware of.
