### ISSUE TITLE
someone can provide a pure python demo？

### ISSUE THREAD

**Issue by 422053362** [cmusatyalab/openface#60]
pure python maybe more clear for then lib

**Comment by AKSHAYUBHAT** [comment]
This is an already open issue. https://github.com/cmusatyalab/openface/issues/1
I am trying to integrate VGG  deep face networks which has a "pure" python implementation using Tensor Flow.

**Comment by bamos** [comment]
Thanks @AKSHAYUBHAT - closing as a duplicate issue of #1.

@422053362 - the demos are mostly in Python, with the exception of calling into Torch for the neural network, which I've provided as a Python library call.
See the [usage](http://cmusatyalab.github.io/openface/usage/) documentation for a short Python example.
