### ISSUE TITLE
classifier demo fails to run with train command because classifierModel argument is not present

### ISSUE THREAD

**Issue by andyisnowskynet** [cmusatyalab/openface#65]
The classifier demo failed for me when trying to run the train command with this error message:

AttributeError: 'Namespace' object has no attribute 'classifierModel'

I've created a pull request to fix this issue: https://github.com/cmusatyalab/openface/pull/64

**Comment by bamos** [comment]
Thanks! Instead of checking for the attribute as in your PR, I resolved this by checking `arg.mode == 'infer'`.
