### ISSUE TITLE
Compaling openface in centos

### ISSUE THREAD

**Issue by shimen** [cmusatyalab/openface#66]
I had to add these code lines to the __init__.py, for the compare.py example to work:
# Start dirty hack.
os.environ['TERM'] = 'linux'
# End of hack.

Without it I got an exception "Error getting result from Torch subprocess."

 
import atexit
import binascii
from subprocess import Popen, PIPE
import os
import os.path
import time
import sys

import numpy as np
import cv2

myDir = os.path.dirname(os.path.realpath(__file__))

#***************************************************
# Start dirty hack.
os.environ['TERM'] = 'linux'
# End of hack.
#***************************************************

class TorchWrap:
    # Warning: This is very unstable!
    # Please join us in improving it at:
    #   https://github.com/cmusatyalab/openface/issues/1
    #   https://github.com/cmusatyalab/openface/issues/4

**Comment by bamos** [comment]
Hi @shimen - thanks for the report. What is the full error message if you don't set the `TERM` environment variable in Python? Hopefully there's a better solution to supporting CentOS.

**Comment by shimen** [comment]
root@213.x11.black.bionic8.com openface# python ./demos/compare.py images/test/{Albert_Costa_*,Bill_Graham_*,Charles_Taylor_*,Elsa_Zylberstein_*} --dlibRoot /usr/local/dlib/dlib-18.16/python_examples --verbose
libdc1394 error: Failed to initialize libdc1394
Argument parsing and loading libraries took 0.314191102982 seconds.
Loading the dlib and OpenFace models took 1.23153495789 seconds.
Processing images/test/Albert_Costa_0001.jpg.
  + Original size: (94, 94, 3)
  + Face detection took 0.0102400779724 seconds.
  + Face alignment took 0.0202901363373 seconds.



Error getting result from Torch subprocess.

Line read: -0.012453161180019,0.039752688258886,0.046378534287214,-0.048598032444715,-0.11067679524422,0.076201967895031,-0.058761306107044,0.2002699226141,-0.02447091974318,0.075192674994469,0.020967984572053,-0.18897868692875,0.22314542531967,-0.0045311753638089,0.052120685577393,0.063324980437756,0.032319582998753,-0.06793574988842,-0.13613133132458,-0.032558031380177,0.096573896706104,0.0055099194869399,0.00294578820467,0.072829701006413,0.15988650918007,0.077054969966412,0.062441028654575,-0.032521419227123,0.052600912749767,0.165931224823,-0.043584603816271,0.1056549474597,0.16857299208641,-0.22476401925087,-0.069148778915405,-0.11709856241941,-0.021948622539639,-0.0087665282189846,0.0053409044630826,-0.019395366311073,-0.029293719679117,-0.085206106305122,0.076467037200928,0.045424342155457,0.037209369242191,-0.075216382741928,0.061872139573097,0.048223782330751,-0.14456968009472,-0.073155350983143,-0.093855142593384,0.011636625044048,-0.25136107206345,-0.034420054405928,-0.042390309274197,-0.06055112183094,0.001150059280917,-0.060826729983091,0.010364850983024,0.15570162236691,0.12299963086843,0.092260122299194,-0.083668559789658,-0.11442413926125,-0.040691960602999,-0.047644060105085,-0.06696030497551,0.042007341980934,0.047437902539968,0.11834111809731,-0.05615196377039,0.083392061293125,0.055926654487848,-0.033915620297194,0.08199468255043,-0.045196656137705,0.03459158539772,-0.031725764274597,0.042842101305723,0.041985511779785,-0.15320219099522,0.036371350288391,-0.1090942248702,0.09391750395298,0.04904655739665,0.05396481230855,0.042778339236975,0.046174261718988,0.045297011733055,0.067810080945492,0.10477747768164,-0.032176949083805,0.075003914535046,-0.081487871706486,-0.096687205135822,-0.089121997356415,-0.082898788154125,0.031131189316511,0.078179240226746,-0.16054120659828,-0.047405384480953,0.064340375363827,0.12052276730537,0.045161448419094,0.042451169341803,-0.12515306472778,-0.091314911842346,-0.086720354855061,0.015044091269374,0.0057204645127058,-0.093178309500217,0.0219332780689,0.015847731381655,-0.15586383640766,-0.12918540835381,-0.076626412570477,-0.040208965539932,-0.077441066503525,0.080029532313347,-0.061407808214426,-0.093963079154491,-0.17090472579002,-0.16776797175407,0.051998253911734,0.03003297559917,-0.098626889288425,-0.0076981438323855,-0.02688723616302


Exception:

could not convert string to float: -0.012453161180019

============

stdout:

============

stderr:

**Comment by bamos** [comment]
Hi @shimen - I don't understand what's causing this. Why does `os.environ['TERM'] = 'linux'` fix it?

**Comment by shimen** [comment]
There seems to be a problem in init.py:

this is the original version:
""".format(self.cmd, self.p.stdout.read(), self.p.stderr.read()))

        self.p.stdin.write(imgPath + "\n")
        output = self.p.stdout.readline()
        try:
            return [float(x) for x in output.strip().split(',')]
        except Exception as e:
            self.p.kill()
            stdout, stderr = self.p.communicate()
            print("""

this is my version to show what is the bug a n what the fix does:
""".format(self.cmd, self.p.stdout.read(), self.p.stderr.read()))
        self.p.stdin.write(imgPath + "\n")
        output = self.p.stdout.readline()
        print output
        cleanOutput = output.strip().split(',')
        print cleanOutput
        output = "1,2"
        cleanOutput = output.strip().split(',')
        try:
            return [float(x) for x in cleanOutput]
        except Exception as e:
            self.p.kill()
            stdout, stderr = self.p.communicate()
            print("""

The problem is in the buffers and the command: output.strip().split(',')
It seems to be that some "junk" is added to the output causing the program to crush.
This is the output:
Argument parsing and loading libraries took 0.267912864685 seconds.                                                                                                                                       
Loading the dlib and OpenFace models took 1.18063807487 seconds.                                                                                                                                          
Processing /home/dev/workspace/jet_opencv/py_openFace_dev/src/new_code/../images/examples/lennon-1.jpg.                                                                                                   
  + Original size: (1050, 1400, 3)                                                                                                                                                                        
/home/dev/workspace_matlab/DeepFaces_err                                                                                                                                                                  
  + Face alignment took 3.81913208961 seconds.                                                                                                                                                            
0.20604400336742,0.077919863164425,0.077178478240967,0.016285706311464,0.14765217900276,-0.0018286623526365,-0.050955783575773,0.061559334397316,0.020092267543077,-0.010352652519941,0.018583970144391,0.052166644483805,0.0093261087313294,-0.02949714846909,0.03013982065022,0.030312934890389,0.0062962644733489,-0.10442773252726,-0.19326290488243,-0.045474946498871,-0.056284416466951,0.017041191458702,-0.036930754780769,0.10171640664339,0.070785284042358,0.0095238322392106,0.14773067831993,0.09470284730196,-0.07384566962719,0.051972005516291,-0.073149167001247,-0.047472093254328,0.023110976442695,-0.18772062659264,-0.23721957206726,0.022152695804834,-0.0085910633206367,0.069459497928619,-0.093688257038593,-0.08848125487566,0.049425151199102,-0.1894426047802,0.12194432318211,-0.1227119192481,0.076608747243881,-0.043617937713861,-0.17858521640301,0.018808541819453,-0.096025757491589,0.046532265841961,-0.03964389115572,0.0036526140756905,0.0094993263483047,0.02625747025013,-0.013224842958152,-0.069054901599884,-0.028403108939528,-0.078694872558117,0.05133306235075,-0.085062004625797,0.11920328438282,0.037904389202595,-0.11445862054825,0.017763895913959,0.010620097629726,-0.14076396822929,0.10324115306139,-0.021075477823615,0.093120761215687,0.033993303775787,-0.13540399074554,0.00083821354201064,0.051621183753014,-0.077468939125538,-0.059118699282408,0.059642199426889,0.068750746548176,-0.047235053032637,0.031562175601721,0.010907704010606,-0.065355494618416,-0.16369423270226,-0.11222054809332,-0.0093877706676722,0.087405078113079,0.17594961822033,0.052573472261429,-0.078457877039909,0.093858860433102,0.19248966872692,0.017559995874763,-0.041851624846458,0.16061328351498,-0.070455089211464,-0.026497583836317,0.025715369731188,-0.077055715024471,0.060185689479113,0.0067397975362837,0.035512242466211,0.14132373034954,0.14162221550941,0.12800864875317,0.058875296264887,-0.026321964338422,-0.013164821080863,0.025004949420691,-0.032057337462902,-0.12017620354891,0.018216371536255,0.0452178157866,0.16022576391697,-0.18443749845028,0.057625107467175,0.029812268912792,0.071827083826065,-0.13502457737923,-0.046073250472546,0.037478938698769,0.039473138749599,0.0076605184003711,-0.21684549748898,-0.054122138768435,0.065855041146278,0.0066578695550561,-0.11500262469053,-0.046083379536867,0.0084551377221942                                                                                               

['\x1b[?1034h0.20604400336742', '0.077919863164425', '0.077178478240967', '0.016285706311464', '0.14765217900276', '-0.0018286623526365', '-0.050955783575773', '0.061559334397316', '0.020092267543077', '-0.010352652519941', '0.018583970144391', '0.052166644483805', '0.0093261087313294', '-0.02949714846909', '0.03013982065022', '0.030312934890389', '0.0062962644733489', '-0.10442773252726', '-0.19326290488243', '-0.045474946498871', '-0.056284416466951', '0.017041191458702', '-0.036930754780769', '0.10171640664339', '0.070785284042358', '0.0095238322392106', '0.14773067831993', '0.09470284730196', '-0.07384566962719', '0.051972005516291', '-0.073149167001247', '-0.047472093254328', '0.023110976442695', '-0.18772062659264', '-0.23721957206726', '0.022152695804834', '-0.0085910633206367', '0.069459497928619', '-0.093688257038593', '-0.08848125487566', '0.049425151199102', '-0.1894426047802', '0.12194432318211', '-0.1227119192481', '0.076608747243881', '-0.043617937713861', '-0.17858521640301', '0.018808541819453', '-0.096025757491589', '0.046532265841961', '-0.03964389115572', '0.0036526140756905', '0.0094993263483047', '0.02625747025013', '-0.013224842958152', '-0.069054901599884', '-0.028403108939528', '-0.078694872558117', '0.05133306235075', '-0.085062004625797', '0.11920328438282', '0.037904389202595', '-0.11445862054825', '0.017763895913959', '0.010620097629726', '-0.14076396822929', '0.10324115306139', '-0.021075477823615', '0.093120761215687', '0.033993303775787', '-0.13540399074554', '0.00083821354201064', '0.051621183753014', '-0.077468939125538', '-0.059118699282408', '0.059642199426889', '0.068750746548176', '-0.047235053032637', '0.031562175601721', '0.010907704010606', '-0.065355494618416', '-0.16369423270226', '-0.11222054809332', '-0.0093877706676722', '0.087405078113079', '0.17594961822033', '0.052573472261429', '-0.078457877039909', '0.093858860433102', '0.19248966872692', '0.017559995874763', '-0.041851624846458', '0.16061328351498', '-0.070455089211464', '-0.026497583836317', '0.025715369731188', '-0.077055715024471', '0.060185689479113', '0.0067397975362837', '0.035512242466211', '0.14132373034954', '0.14162221550941', '0.12800864875317', '0.058875296264887', '-0.026321964338422', '-0.013164821080863', '0.025004949420691', '-0.032057337462902', '-0.12017620354891', '0.018216371536255', '0.0452178157866', '0.16022576391697', '-0.18443749845028', '0.057625107467175', '0.029812268912792', '0.071827083826065', '-0.13502457737923', '-0.046073250472546', '0.037478938698769', '0.039473138749599', '0.0076605184003711', '-0.21684549748898', '-0.054122138768435', '0.065855041146278', '0.0066578695550561', '-0.11500262469053', '-0.046083379536867', '0.0084551377221942']                                                                                                       
  + OpenFace forward pass took 0.135200977325 seconds.         
 



As you can see after the conversion the first cell in the array gets the value:'\x1b[?1034h0.20604400336742'
This value can not be converted to float() and the program fails.


I had used the hack as described here:
http://reinout.vanrees.org/weblog/2009/08/14/readline-invisible-character-hack.html

Hope that this helps

**Comment by bamos** [comment]
Interesting, thanks for the details. I just added the code to set `TERM` to Linux.
Moving the Lua subprocess to a server should make this hack not necessary: https://github.com/cmusatyalab/openface/issues/4
