### ISSUE TITLE
   How can i work this programme !!!!         WE NEED THESE ANSWER URGENT

### ISSUE THREAD

**Issue by jihademir** [cmusatyalab/openface#69]
I am begginer level at software coding. Can you help me about the steps to run this project ? Which operating systems and programming languages that I need make this project work.

**Comment by sschnug** [comment]
There is a documentation [here](http://cmusatyalab.github.io/openface/) which explains everything, you need to know to obtain first results on your data. Start with [setup](http://cmusatyalab.github.io/openface/setup/).

There is also a google group for discussion and questions [here](https://groups.google.com/forum/#!forum/cmu-openface), but i can assure you, that such broad and unprepared question like yours won't be answered. **This issue-tracker is for bugs & code-changes in general**.

Be aware, that face-recognition and deep-learning are highly complex topics (theory & practice), where "beginner level of coding" might not be enough (when working with complex software tackling a complex problem), especially if you wan't to work on the code. This project uses at least *Lua* and *Python* which might be enough to generate some confusion.
Nonetheless: reading the docs carefully should be enough to work with the demos!

**Comment by bamos** [comment]
Thanks @sschnug - great response!
@jihademir - we're happy to help with more specific questions on our mailing list.

-Brandon.
