### ISSUE TITLE
Do "all other open-source face recognition implementations you are aware of" include the Oxford VGG-Face model?

### ISSUE THREAD

**Issue by futurely** [cmusatyalab/openface#7]
http://www.robots.ox.ac.uk/~vgg/software/vgg_face/

@bamos

**Comment by futurely** [comment]
They built a large scale face dataset to achieve results comparable with or better than Google's FaceNet and Facebook's DeepFace.
http://www.robots.ox.ac.uk/~vgg/publications/2015/Parkhi15/poster.pdf

**Comment by happynear** [comment]
Here is an implementation and model even better than VGG's softmax model. VGG have not made their Triplet model public available now.
https://github.com/AlfredXiangWu/lfw_face_verification_experiment/

As far as I know, this is the best model being open sourced right now. It reaches accuracy of 97.77% on LFW.

**Comment by bamos** [comment]
Thanks for the references! Great to see progress being made here by other researchers. I've referenced both projects in the README.
