### ISSUE TITLE
Comparison results not consistent with the docs

### ISSUE THREAD

**Issue by shimen** [cmusatyalab/openface#70]
Hi, there seems to be a problem with the transformation of the face based on the land marks.
I had attached the debug output of the face aliment process

Original Image:
![amit1](https://cloud.githubusercontent.com/assets/10295217/11841665/88ac6f6e-a407-11e5-8e74-0ad90c8a4197.jpg)

annotated
![amit1-annotated](https://cloud.githubusercontent.com/assets/10295217/11841457/1552c0c8-a406-11e5-92e4-9504fbc6e5a9.png)

warped-annotated
![amit1-warped-annotated](https://cloud.githubusercontent.com/assets/10295217/11841455/154fc1de-a406-11e5-9568-d2b8682d4b84.png)

The result:
![amit1](https://cloud.githubusercontent.com/assets/10295217/11841550/bd723bb2-a406-11e5-865f-a38db6115afa.png)

If I add black area to the original image to make it square it work fine:

annotated
![temp-annotated](https://cloud.githubusercontent.com/assets/10295217/11841554/c7ef6948-a406-11e5-9219-e610fa00a2f3.png)

warped-annotated
![temp-warped-annotated](https://cloud.githubusercontent.com/assets/10295217/11841555/c7f180d4-a406-11e5-8726-03acfd4b6345.png)

The result:

![temp](https://cloud.githubusercontent.com/assets/10295217/11841563/d2b9019a-a406-11e5-8b22-11c9319d37e0.png)

**Comment by bamos** [comment]
Hi @shimen - how did you produce these images?
I am able to align the image with the latest version of the code.

Can you try the following?

```
openface(master*)$ tree shimen
shimen
└── shimen.jpg

0 directories, 1 file
openface(master*)$ ./util/align-dlib.py shimen align innerEyesAndBottomLip shimen/out
('shimen/out/shimen/shimen.png', <type 'numpy.ndarray'>, (1350, 589, 3))
openface(master*)$ tree shimen
shimen
├── out
│   └── shimen
│       └── shimen.png
└── shimen.jpg
```

![shimen](https://cloud.githubusercontent.com/assets/707462/11848309/b33d0404-a3ef-11e5-83f2-36817b887d68.png)

**Comment by shimen** [comment]
Just updated it, it works!!
I had retested the compare test and got different results:

Comparing /images/examples/lennon-1.jpg with /images/examples/lennon-2.jpg.
  + Squared l2 distance between representations: 0.352
Comparing /images/examples/lennon-1.jpg with /images/examples/clapton-1.jpg.
  + Squared l2 distance between representations: 1.104
Comparing /images/examples/lennon-1.jpg with /images/examples/clapton-2.jpg.
  + Squared l2 distance between representations: 1.179
Comparing /images/examples/lennon-2.jpg with /images/examples/clapton-1.jpg.
  + Squared l2 distance between representations: 1.211
Comparing /images/examples/lennon-2.jpg with /images/examples/clapton-2.jpg.
  + Squared l2 distance between representations: 1.079
Comparing /images/examples/clapton-1.jpg with /images/examples/clapton-2.jpg.
  + Squared l2 distance between representations: 0.531 

instead of:

Image 1	Image 2	Distance_old	Distance_new
Lennon 1	Lennon 2	        0.298               0.352
Lennon 1	Clapton 1 	0.985               1.104
Lennon 1	Clapton 2	        0.855               1.179
Lennon 2	Clapton 1         0.904               1.211
Lennon 2	Clapton 2  	0.955               1.079
Clapton 1	Clapton 2 	0.712               0.531

**Comment by shimen** [comment]
Just tried the old code again on 2 different computers, the results were the same and are:
root@213.x11.black.bionic8.com src# python ./demos/compare.py images/examples/{lennon*,clapton*}
libdc1394 error: Failed to initialize libdc1394                                                 
Comparing images/examples/lennon-1.jpg with images/examples/lennon-2.jpg.                       
  + Squared l2 distance between representations: 0.309903433325                                 
Comparing images/examples/lennon-1.jpg with images/examples/clapton-1.jpg.                      
  + Squared l2 distance between representations: 1.24080061286                                  
Comparing images/examples/lennon-1.jpg with images/examples/clapton-2.jpg.                      
  + Squared l2 distance between representations: 1.05589421611                                  
Comparing images/examples/lennon-2.jpg with images/examples/clapton-1.jpg.                      
  + Squared l2 distance between representations: 1.38612383046                                  
Comparing images/examples/lennon-2.jpg with images/examples/clapton-2.jpg.                      
  + Squared l2 distance between representations: 1.07297646102                                  
Comparing images/examples/clapton-1.jpg with images/examples/clapton-2.jpg.                     
  + Squared l2 distance between representations: 0.258562021983


When I had installed the package for the first time I got the posted results.
After I made a copy and worked only on the project copy.

I think it is due to the packages:

root@213.x11.black.bionic8.com src# luajit -v
LuaJIT 2.1.0-beta1 -- Copyright (C) 2005-2015 Mike Pall. http://luajit.org/
root@213.x11.black.bionic8.com src# lua -v
Lua 5.1.4  Copyright (C) 1994-2008 Lua.org, PUC-Rio
root@213.x11.black.bionic8.com src# luarocks list                                               
Installed rocks:
----------------
csvigo
   scm-1 (installed) - /usr/local/lib/luarocks/rocks
cwrap
   scm-1 (installed) - /usr/local/lib/luarocks/rocks                                                                                                                                                                                                                                                                             
dok                                                                                                                                                                
   scm-1 (installed) - /usr/local/lib/luarocks/rocks                                                                                                                                                                                                                                                                         
dpnn                                                                                                                                                               
   scm-1 (installed) - /usr/local/lib/luarocks/rocks                                                                                                               
gnuplot
   scm-1 (installed) - /usr/local/lib/luarocks/rocks
image
   1.1.alpha-0 (installed) - /usr/local/lib/luarocks/rocks
lua-cjson
   2.1.0-1 (installed) - /usr/local/lib/luarocks/rocks
luafilesystem
   1.6.3-1 (installed) - /usr/local/lib/luarocks/rocks
moses
   1.4.0-1 (installed) - /usr/local/lib/luarocks/rocks
nn
   scm-1 (installed) - /usr/local/lib/luarocks/rocks
nnx
   0.1-1 (installed) - /usr/local/lib/luarocks/rocks
optim
   1.0.5-0 (installed) - /usr/local/lib/luarocks/rocks
paths
   scm-1 (installed) - /usr/local/lib/luarocks/rocks
penlight
   1.3.2-2 (installed) - /usr/local/lib/luarocks/rocks
qtlua
   scm-1 (installed) - /usr/local/lib/luarocks/rocks
qttorch
   scm-1 (installed) - /usr/local/lib/luarocks/rocks
sundown
   scm-1 (installed) - /usr/local/lib/luarocks/rocks
sys
   1.1-0 (installed) - /usr/local/lib/luarocks/rocks
torch
   scm-1 (installed) - /usr/local/lib/luarocks/rocks
trepl
   scm-1 (installed) - /usr/local/lib/luarocks/rocks
xlua
   1.0-0 (installed) - /usr/local/lib/luarocks/rocks

**Comment by bamos** [comment]
Hi @shimen,

> Just tried the old code again on 2 different computers, the results
> were the same and are:

The new and old alignment techniques produce slightly different features.
The values you are posting are consistent with the values I got from
the old code [0].
See my announcement message with more details about the new technique
at [1].

-Brandon.

[0]: https://github.com/cmusatyalab/openface/commit/12a86489590c31ef17714354272b5cb60c00589b
[1]: https://groups.google.com/forum/#!topic/cmu-openface/SAiOT_j4NjE

**Comment by shimen** [comment]
Thank you!
Now I see that for that I'm using the old aliment version, so the expected results as disturbed in "docs/demo-2-comparison.md" are:
| Image 1 | Image 2 | Distance |
|---|---|---|
| Lennon 1 | Lennon 2 | 0.310 |
| Lennon 1 | Clapton 1 | 1.241 |
| Lennon 1 | Clapton 2 | 1.056 |
| Lennon 2 | Clapton 1 | 1.386 |
| Lennon 2 | Clapton 2 | 1.073 |
| Clapton 1 | Clapton 2 | 0.259 |

I get these results!

Still can't explain why for the new code I get not the expected  
Image 1 Image 2  Distance_new_expected Distance_new
Lennon 1 Lennon 2      0.298                           0.352
Lennon 1 Clapton 1      0.985                           1.104
Lennon 1 Clapton 2      0.855                           1.179
Lennon 2 Clapton 1      0.904                           1.211
Lennon 2 Clapton 2      0.955                           1.079
Clapton 1 Clapton 2      0.712                           0.531

**Comment by bamos** [comment]
> Still can't explain why for the new code I get not the expected
> Image 1 Image 2  Distance_new_expected Distance_new
> Lennon 1 Lennon 2      0.298                           0.352
> Lennon 1 Clapton 1      0.985                           1.104
> Lennon 1 Clapton 2      0.855                           1.179
> Lennon 2 Clapton 1      0.904                           1.211
> Lennon 2 Clapton 2      0.955                           1.079
> Clapton 1 Clapton 2      0.712                           0.531

I just re-built a Docker container from scratch,
which has the latest dependencies.
I'm getting the expected results from the OpenFace docs,
which indicates this probably isn't a versioning issue.
Assuming you haven't modified any of the code,
I'm not sure why your results are different.

These aren't very good solutions and won't be very insightful if
things start working, but can you try:

  1. Running in Docker, and
  2. Removing and then re-installing as much of the dependencies and
     OpenFace as possible.

-Brandon.

**Comment by bamos** [comment]
Hi @shimen - I'm not sure why, but I think the mis-matches values you're seeing here are from a place where I forgot to convert back to BGR before using OpenCV's image write function. I just committed this correction at: https://github.com/cmusatyalab/openface/commit/5177deb351de576fb3459a2d6a79dfc92c6ddb57

Now I'm getting the same values as your `Distance_new`, but I'm not sure why your code was using different channels than mine. Can you pull the latest version of the code and try re-running the comparison demo?

-Brandon.

**Comment by shimen** [comment]
Hi @bamos - sorry for the late answer.
I had changed the alignment function to suite my needs and because of that I  didn't had the BGR, RGB problem.

**Comment by bamos** [comment]
Hi @shimen - I'm closing this issue because I think it's resolved,
but please re-open if you want to discuss anything else related to it.

-Brandon.
