### ISSUE TITLE
Images pre-processing

### ISSUE THREAD

**Issue by MarcorOnline** [cmusatyalab/openface#72]
Hello.

I've two questions abount images pre-processing:
1) Why BGR2RGB conversion? the faces becomes "blue"... there is an improvement in this way?
2) The equalization of the images could be used?

Thanks

**Comment by bamos** [comment]
Hi @MarcorOnline,

> 1) Why BGR2RGB conversion? the faces becomes "blue"... there is an improvement in this way?

Most of OpenFace uses dlib, which uses RGB.
To save images with OpenCV's `imwrite`, convert the image back to BGR.

I just noticed I forgot this conversion before saving for the neural network pass
and pushed a correction at https://github.com/cmusatyalab/openface/commit/5177deb351de576fb3459a2d6a79dfc92c6ddb57

> 2) The equalization of the images could be used?

You can try experimenting with equalization before the neural network pass, but this requires training a new model (see http://cmusatyalab.github.io/openface/training-new-models/). My intuition is that it wouldn't improve the accuracy.

-Brandon.
