### ISSUE TITLE
Make web demo secure because of Chrome's deprecation of powerful features on insecure origins

### ISSUE THREAD

**Issue by bamos** [cmusatyalab/openface#75]
Original mailing list post: https://groups.google.com/forum/#!topic/cmu-openface/TNZR_QVR8Nc

> When I try to use the web demo connecting to a Docker container,
> I get the following message:
> 
>    getUserMedia() no longer works on insecure origins. To use this
>    feature, you should consider switching your application to a secure
>    origin, such as HTTPS. See https://goo.gl/rStTGz for more details.
> 
> They suggest three workarounds:
> 1. localhost is treated as a secure origin over HTTP, so if you're
>    able to run your server from localhost, you should be able to test
>    the feature on that server.
> 2. You can run chrome with the
>    --unsafely-treat-insecure-origin-as-secure="example.com" flag
>    (replacing "example.com" with the origin you actually want to test),
>    which will treat that origin as secure for this session. Note that
>    you also need to include the --user-data-dir=/test/only/profile/dir
>    to create a fresh testing profile for the flag to work.
> 3. Use secure protocols

**Comment by barrettclark** [comment]
I've generated the certs for https and wss connections so that I could make calls on the same network from different computers (similar to docker on OS X), but self-signed certs did not appear to be good enough for the `getUserMedia()` calls. I'll post an update if I chase this down further.

**Comment by Tom-Neverwinter** [comment]
https://www.kirupa.com/html5/accessing_your_webcam_in_html5.htm This may be a good place to start

**Comment by SalehAly** [comment]
Hey,

I have found another solution to the getUserMedia issue on OSX  from this answer [here](http://stackoverflow.com/questions/35372399/connect-to-docker-machine-using-localhost). where you can run the demo from your localhost:8000

you can execute this commands from your terminal which adds a VirtualBox port forward to map a port on the docker host to your local machine
```
vboxmanage controlvm default natpf1 "nameformapping,tcp,,8000,,8000"
vboxmanage controlvm default natpf1 "nameformapping2,tcp,,9000,,9000"
```

Or you can open 
``` 
1- VirtualBox
2- Click on your docker machine 
3- Go To Settings -> Network -> Port Forwarding
3- add the port mapping rules 
```
 

<img width="946" alt="screen shot 2017-03-15 at 3 18 58 pm" src="https://cloud.githubusercontent.com/assets/15343258/23952779/d8c42086-0992-11e7-8a21-0f09f7d9e8e4.png">
