### ISSUE TITLE
Classifier train is not working.

### ISSUE THREAD

**Issue by bbhushan-ds** [cmusatyalab/openface#77]
Hi,

Thanks for your great effort for this project.

while working with classifier training I am getting some error below. It was working before but It not now after changes for v2.

[CV] ......... kernel=rbf, C=100, gamma=0.001, score=1.000000 -   0.0s
[CV] kernel=rbf, C=100, gamma=0.001 ..................................
Traceback (most recent call last):
  File "./demos/classifier.py", line 187, in <module>
    train(args)
  File "./demos/classifier.py", line 106, in train
    ).fit(embeddings, labelsNum)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/grid_search.py", line 732, in fit
    return self._fit(X, y, ParameterGrid(self.param_grid))
  File "/usr/local/lib/python2.7/dist-packages/sklearn/grid_search.py", line 505, in _fit
    for parameters in parameter_iterable
  File "/usr/local/lib/python2.7/dist-packages/sklearn/externals/joblib/parallel.py", line 666, in __call__
    self.retrieve()
  File "/usr/local/lib/python2.7/dist-packages/sklearn/externals/joblib/parallel.py", line 549, in retrieve
    raise exception_type(report)
sklearn.externals.joblib.my_exceptions.JoblibValueError: JoblibValueError
___________________________________________________________________________
Multiprocessing exception:
    ...........................................................................
/root/src/openface/demos/classifier.py in <module>()
    182     if args.verbose:
    183         print("Loading the dlib and OpenFace models took {} seconds.".format(time.time() - start))
    184         start = time.time()
    185 
    186     if args.mode == 'train':
--> 187         train(args)
    188     elif args.mode == 'infer':
    189         infer(args)
    190 
    191 

...........................................................................
/root/src/openface/demos/classifier.py in train(args=Namespace(cuda=False, dlibFacePredictor='/root/s..., verbose=False, workDir='/root/src/openface/f/'))
    101             'kernel': ['rbf']}
    102     ]
    103     svm = GridSearchCV(
    104         SVC(probability=True),
    105         param_grid, verbose=4, cv=5, n_jobs=16
--> 106     ).fit(embeddings, labelsNum)
        embeddings = array([[  8.47e-03,   1.29e-01,  -4.87e-03,  -7....01,
          8.84e-02,   6.08e-02,   1.28e-02]])
        labelsNum = array([0, 1, 3, 3, 2, 2])
    107     print("Best estimator: {}".format(svm.best_estimator_))
    108     print("Best score on left out data: {:.2f}".format(svm.best_score_))
    109 
    110     with open("{}/classifier.pkl".format(args.workDir), 'w') as f:

...........................................................................
/usr/local/lib/python2.7/dist-packages/sklearn/grid_search.py in fit(self=GridSearchCV(cv=5, error_score='raise',
       e... score_func=None, scoring=None,
       verbose=4), X=array([[  8.47e-03,   1.29e-01,  -4.87e-03,  -7....01,
          8.84e-02,   6.08e-02,   1.28e-02]]), y=array([0, 1, 3, 3, 2, 2]))
    727         y : array-like, shape = [n_samples] or [n_samples, n_output], optional
    728             Target relative to X for classification or regression;
    729             None for unsupervised learning.
    730 
    731         """
--> 732         return self._fit(X, y, ParameterGrid(self.param_grid))
        self._fit = <bound method GridSearchCV._fit of GridSearchCV(...score_func=None, scoring=None,
       verbose=4)>
        X = array([[  8.47e-03,   1.29e-01,  -4.87e-03,  -7....01,
          8.84e-02,   6.08e-02,   1.28e-02]])
        y = array([0, 1, 3, 3, 2, 2])
        self.param_grid = [{'C': [1, 10, 100, 1000], 'kernel': ['linear']}, {'C': [1, 10, 100, 1000], 'gamma': [0.001, 0.0001], 'kernel': ['rbf']}]
    733 
    734 
    735 class RandomizedSearchCV(BaseSearchCV):
    736     """Randomized search on hyper parameters.

...........................................................................
/usr/local/lib/python2.7/dist-packages/sklearn/grid_search.py in _fit(self=GridSearchCV(cv=5, error_score='raise',
       e... score_func=None, scoring=None,
       verbose=4), X=array([[  8.47e-03,   1.29e-01,  -4.87e-03,  -7....01,
          8.84e-02,   6.08e-02,   1.28e-02]]), y=array([0, 1, 3, 3, 2, 2]), parameter_iterable=<sklearn.grid_search.ParameterGrid object>)
    500         )(
    501             delayed(_fit_and_score)(clone(base_estimator), X, y, self.scorer_,
    502                                     train, test, self.verbose, parameters,
    503                                     self.fit_params, return_parameters=True,
    504                                     error_score=self.error_score)
--> 505                 for parameters in parameter_iterable
        parameters = undefined
        parameter_iterable = <sklearn.grid_search.ParameterGrid object>
    506                 for train, test in cv)
    507 
    508         # Out is a list of triplet: score, estimator, n_test_samples
    509         n_fits = len(out)

...........................................................................
/usr/local/lib/python2.7/dist-packages/sklearn/externals/joblib/parallel.py in __call__(self=Parallel(n_jobs=16), iterable=<itertools.islice object>)
    661             if pre_dispatch == "all" or n_jobs == 1:
    662                 # The iterable was consumed all at once by the above for loop.
    663                 # No need to wait for async callbacks to trigger to
    664                 # consumption.
    665                 self._iterating = False
--> 666             self.retrieve()
        self.retrieve = <bound method Parallel.retrieve of Parallel(n_jobs=16)>
    667             # Make sure that we get a last message telling us we are done
    668             elapsed_time = time.time() - self._start_time
    669             self._print('Done %3i out of %3i | elapsed: %s finished',
    670                         (len(self._output),

    ---------------------------------------------------------------------------
    Sub-process traceback:
    ---------------------------------------------------------------------------
    ValueError                                         Sun Jan 10 22:21:53 2016
PID: 3677                                    Python 2.7.6: /usr/bin/python2
...........................................................................
/usr/local/lib/python2.7/dist-packages/sklearn/cross_validation.pyc in _fit_and_score(estimator=SVC(C=1, cache_size=200, class_weight=None, coef...None,
  shrinking=True, tol=0.001, verbose=False), X=array([[  8.47e-03,   1.29e-01,  -4.87e-03,  -7....01,
          8.84e-02,   6.08e-02,   1.28e-02]]), y=array([0, 1, 3, 3, 2, 2]), scorer=<function _passthrough_scorer>, train=array([0, 1, 2, 3, 4, 5]), test=array([], dtype=int64), verbose=4, parameters={'C': 1, 'kernel': 'linear'}, fit_params={}, return_train_score=False, return_parameters=True, error_score='raise')
   1473                              " numeric value. (Hint: if using 'raise', please"
   1474                              " make sure that it has been spelled correctly.)"
   1475                              )
   1476 
   1477     else:
-> 1478         test_score = _score(estimator, X_test, y_test, scorer)
   1479         if return_train_score:
   1480             train_score = _score(estimator, X_train, y_train, scorer)
   1481 
   1482     scoring_time = time.time() - start_time

...........................................................................
/usr/local/lib/python2.7/dist-packages/sklearn/cross_validation.pyc in _score(estimator=SVC(C=1, cache_size=200, class_weight=None, coef...None,
  shrinking=True, tol=0.001, verbose=False), X_test=array([], shape=(0, 128), dtype=float64), y_test=array([], dtype=int64), scorer=<function _passthrough_scorer>)
   1529 def _score(estimator, X_test, y_test, scorer):
   1530     """Compute the score of an estimator on a given test set."""
   1531     if y_test is None:
   1532         score = scorer(estimator, X_test)
   1533     else:
-> 1534         score = scorer(estimator, X_test, y_test)
   1535     if not isinstance(score, numbers.Number):
   1536         raise ValueError("scoring must return a number, got %s (%s) instead."
   1537                          % (str(score), type(score)))
   1538     return score

...........................................................................
/usr/local/lib/python2.7/dist-packages/sklearn/metrics/scorer.pyc in _passthrough_scorer(estimator=SVC(C=1, cache_size=200, class_weight=None, coef...None,
  shrinking=True, tol=0.001, verbose=False), *args=(array([], shape=(0, 128), dtype=float64), array([], dtype=int64)), **kwargs={})
    196     return scorer
    197 
    198 
    199 def _passthrough_scorer(estimator, *args, **kwargs):
    200     """Function that wraps estimator.score"""
--> 201     return estimator.score(*args, **kwargs)
    202 
    203 
    204 def check_scoring(estimator, scoring=None, allow_none=False):
    205     """Determine scorer from user options.

...........................................................................
/usr/local/lib/python2.7/dist-packages/sklearn/base.pyc in score(self=SVC(C=1, cache_size=200, class_weight=None, coef...None,
  shrinking=True, tol=0.001, verbose=False), X=array([], shape=(0, 128), dtype=float64), y=array([], dtype=int64), sample_weight=None)
    290         score : float
    291             Mean accuracy of self.predict(X) wrt. y.
    292 
    293         """
    294         from .metrics import accuracy_score
--> 295         return accuracy_score(y, self.predict(X), sample_weight=sample_weight)
    296 
    297 
    298 ###############################################################################
    299 class RegressorMixin(object):

...........................................................................
/usr/local/lib/python2.7/dist-packages/sklearn/svm/base.pyc in predict(self=SVC(C=1, cache_size=200, class_weight=None, coef...None,
  shrinking=True, tol=0.001, verbose=False), X=array([], shape=(0, 128), dtype=float64))
    495         Returns
    496         -------
    497         y_pred : array, shape = [n_samples]
    498             Class labels for samples in X.
    499         """
--> 500         y = super(BaseSVC, self).predict(X)
    501         return self.classes_.take(np.asarray(y, dtype=np.intp))
    502 
    503     # Hacky way of getting predict_proba to raise an AttributeError when
    504     # probability=False using properties. Do not use this in new code; when

...........................................................................
/usr/local/lib/python2.7/dist-packages/sklearn/svm/base.pyc in predict(self=SVC(C=1, cache_size=200, class_weight=None, coef...None,
  shrinking=True, tol=0.001, verbose=False), X=array([], shape=(0, 128), dtype=float64))
    285 
    286         Returns
    287         -------
    288         y_pred : array, shape (n_samples,)
    289         """
--> 290         X = self._validate_for_predict(X)
    291         predict = self._sparse_predict if self._sparse else self._dense_predict
    292         return predict(X)
    293 
    294     def _dense_predict(self, X):

...........................................................................
/usr/local/lib/python2.7/dist-packages/sklearn/svm/base.pyc in _validate_for_predict(self=SVC(C=1, cache_size=200, class_weight=None, coef...None,
  shrinking=True, tol=0.001, verbose=False), X=array([], shape=(0, 128), dtype=float64))
    418             self.probA_, self.probB_)
    419 
    420     def _validate_for_predict(self, X):
    421         check_is_fitted(self, 'support_')
    422 
--> 423         X = check_array(X, accept_sparse='csr', dtype=np.float64, order="C")
    424         if self._sparse and not sp.isspmatrix(X):
    425             X = sp.csr_matrix(X)
    426         if self._sparse:
    427             X.sort_indices()

...........................................................................
/usr/local/lib/python2.7/dist-packages/sklearn/utils/validation.pyc in check_array(array=array([], shape=(0, 128), dtype=float64), accept_sparse=['csr'], dtype=<type 'numpy.float64'>, order='C', copy=False, force_all_finite=True, ensure_2d=True, allow_nd=False, ensure_min_samples=1, ensure_min_features=1)
    355     if ensure_min_samples > 0:
    356         n_samples = _num_samples(array)
    357         if n_samples < ensure_min_samples:
    358             raise ValueError("Found array with %d sample(s) (shape=%s) while a"
    359                              " minimum of %d is required."
--> 360                              % (n_samples, shape_repr, ensure_min_samples))
    361 
    362     if ensure_min_features > 0 and array.ndim == 2:
    363         n_features = array.shape[1]
    364         if n_features < ensure_min_features:

ValueError: Found array with 0 sample(s) (shape=(0, 128)) while a minimum of 1 is required.

Could you please try to figure this out.

Thanks
Bharat

**Comment by bamos** [comment]
Hi Bharat,

The classifier training is still working for me using nn4.v2
in the latest master branch.

The following lines from your stack trace look like they may
be causing the problem:

>         embeddings = array([[  847e-03,   129e-01,  -487e-03,  -701,
>           884e-02,   608e-02,   128e-02]])
>         labelsNum = array([0, 1, 3, 3, 2, 2])
>
> ValueError: Found array with 0 sample(s) (shape=(0, 128)) while a
> minimum of 1 is required.

Since you only have one sample with label 0 and 1, I think the
cross-validation might be putting this sample in the testing set
and then causing the `0 samples` error from not having any samples
in the training set.

I'm closing this issue since I don't think it's caused by OpenFace,
but please re-open if you find information indicating we need to
change the OpenFace code.

-Brandon.

**Comment by bbhushan-ds** [comment]
Hi bamos,

I am still getting this error, I updated with master branch and dockerfile but still no hope.
Steps which performed.

1). Created two person folders for images each is having 5+ images.
2). ./util/align-dlib.py images/ align innerEyesAndBottomLip aligned/ --size 96
3). ./batch-represent/main.lua -outDir feature/ -data aligned/
4). ./demos/classifier.py train feature/

After these commands I get the above error. Could you please help me on this. OR Is there any step which I am missing.

Thanks
Bharat

**Comment by bamos** [comment]
Hi Bharat, your steps seem correct and my previous diagnosis is wrong since you have two people with 5 or more images each. I'm re-opening this so we can further debug.

Can you try:

1. Printing out `labels` from [line 91 of classifier.py](https://github.com/cmusatyalab/openface/blob/6246fada8320eacd7ea84d32c638d45024d00307/demos/classifier.py#L91)? With just two people, I expect this to only have two values.

2. Running our automated tests with `./run-tests.sh`? Testing requires nose, which can be installed with `pip2 install nose`. These are new and are running well on my system, but they're not yet working on Travis. Interested to see the output and how they work on your system.

-Brandon.

**Comment by bbhushan-ds** [comment]
Hi bamos,

Thanks for your reply on the issue. I have checked this again and Its working fine with your yesterday changes.

You can mark it close.

Thanks
Bharat

**Comment by bamos** [comment]
Hi @bbhushan-ds - great to hear it's working! However, I don't understand how my recent changes have resolved this issue. Did you change anything else to resolve this that I can better document somewhere?

-Brandon.

**Comment by sayak1711** [comment]
Hi @bbhushan-ds What changes did u make?  Please tell me because I am also stuck with same problem

when i type this command

`./demos/classifier.py train ./generated-embeddings/
`
I get this error

**Training for 1 classes.
Traceback (most recent call last):
 File “./demos/classifier.py”, line 291, in <module>
 train(args)
 File “./demos/classifier.py”, line 166, in train
 clf.fit(embeddings, labelsNum)
 File “/root/.local/lib/python2.7/site-packages/sklearn/svm/base.py”, line 151, in fit
 y = self._validate_targets(y)
 File “/root/.local/lib/python2.7/site-packages/sklearn/svm/base.py”, line 521, in _validate_targets
 % len(cls))
ValueError: The number of classes has to be greater than one; got 1**

**Comment by sayak1711** [comment]
Ok I overcame the error by introducing more images per person. Then it worked perfectly.
