### ISSUE TITLE
demo2:RuntimeError 

### ISSUE THREAD

**Issue by jiangyuguang** [cmusatyalab/openface#79]
hi，I am a newcomer.I failed to run the demo2.when I run the demo2.the error is:
usage: compare.py [-h] [--dlibFacePredictor DLIBFACEPREDICTOR]
                  [--networkModel NETWORKMODEL] [--imgDim IMGDIM] [--verbose]
                  imgs [imgs ...]
compare.py: error: too few arguments

**Comment by bamos** [comment]
Hi @jiangyuguang - try to post usage questions like this to our mailing list in the future since the issue tracker is for development discussions and bug reports. I recommend using the docker container and running the following commands to get started with the comparison demo:

```
$ sudo docker run -t -i bamos/openface /bin/bash
root@99c74f90eb21:/# cd /root/src/openface/
root@99c74f90eb21:~/src/openface# ./demos/compare.py ./images/examples/lennon-{1,2}*
Comparing ./images/examples/lennon-1.jpg with ./images/examples/lennon-2.jpg.
  + Squared l2 distance between representations: 0.763
```

-Brandon.

**Comment by jiangyuguang** [comment]
thank you very much,

**Comment by Suraj59** [comment]
sudo docker run -t -i bamos/openface /bin/bash
root@98a347540f1c:/# cd /root/src/openface/
bash: cd: /root/src/openface/: No such file or directory
root@98a347540f1c:/# 
what should i do now??
