### ISSUE TITLE
batch-represent: Remove unused data loading code

### ISSUE THREAD

**Issue by bamos** [cmusatyalab/openface#80]
From [this mailing list discussion](https://groups.google.com/d/msg/cmu-openface/LtEfygsgEdU/61-IM7uFCAAJ).

`dataset.lua` is copied from the
training code where the dataset can be partitioned into training and
test sets. In batch-represent, I just load all of the data into 'training'.

**Comment by junaid6141** [comment]
Hi,
@bamos i just trained it on LFW dataset.
But when i test it it gives me an output:

Predict Nestor_Kirchner with 0.00 confidence.

Will you plz tell me any solution. And how do i split training set and test test.
