### ISSUE TITLE
batch-represent/main.lua -outDir classify-test/features -data classify-test/aligned/ -----Error

### ISSUE THREAD

**Issue by anthonyyuan** [cmusatyalab/openface#81]
sudo ./batch-represent/main.lua -outDir classify-test/features -data classify-test/aligned/
Password:
{
  data : "classify-test/aligned/"
  imgDim : 96
  cache : false
  model : "/Users/lihong/src/openface-master/models/openface/nn4.small2.v1.t7"
  outDir : "classify-test/features"
  cuda : false
  batchSize : 50
}
classify-test/aligned/	
cache lotation: 	/Users/lihong/src/openface-master/classify-test/aligned/cache.t7	
Creating metadata for cache.	
{
  sampleSize : 
    {
      1 : 3
      2 : 96
      3 : 96
    }
  split : 0
  verbose : true
  paths : 
    {
      1 : "classify-test/aligned/"
    }
  samplingMode : "balanced"
  loadSize : 
    {
      1 : 3
      2 : 96
      3 : 96
    }
}
running "find" on each class directory, and concatenate all those filenames into a single file containing all image paths for a given class	
/tmp/lua_GR5PHA: line 1: gfind: command not found
/tmp/lua_GR5PHA: line 2: gfind: command not found
now combine all the files to a single large file	
load the large concatenated list of sample paths to self.imagePath	
sh: gwc: command not found
/Users/lihong/torch/install/bin/luajit: ...s/lihong/src/openface-master/batch-represent/dataset.lua:189: attempt to perform arithmetic on a nil value
stack traceback:
	...s/lihong/src/openface-master/batch-represent/dataset.lua:189: in function '__init'
	/Users/lihong/torch/install/share/lua/5.1/torch/init.lua:91: in function </Users/lihong/torch/install/share/lua/5.1/torch/init.lua:87>
	[C]: in function 'dataLoader'
	.../src/openface-master/batch-represent/batch-represent.lua:19: in function 'batchRepresent'
	./batch-represent/main.lua:42: in main chunk
	[C]: in function 'dofile'
	...hong/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x0106d88bd0
DaviddeMacBook-Pro:openface-master lihong$

**Comment by anthonyyuan** [comment]
I know it is my wrong!
In OSX, install findutils and coreutils with Brew or MacPorts

**Comment by bamos** [comment]
Hi @anthonyyuan - sorry the OSX findutils and coreutils dependencies weren't clear from the setup docs. Can I improve the docs so this is clearer for people in the future?

-Brandon.
