### ISSUE TITLE
Torch version hardcoded in model

### ISSUE THREAD

**Issue by pannous** [cmusatyalab/openface#83]
with a very fresh Torch on Mac and Ubuntu we get
`unknown Torch class <nn.SpatialCrossMapLRN>`
```
me@:~/openface$ th demos/vis-outputs.lua 
/torch/install/bin/luajit: /torch/install/share/lua/5.1/torch/File.lua:290: unknown Torch class <nn.SpatialCrossMapLRN>
stack traceback:
	[C]: in function 'error'
	/torch/install/share/lua/5.1/torch/File.lua:290: in function 'readObject'
	/torch/install/share/lua/5.1/torch/File.lua:316: in function 'readObject'
	/torch/install/share/lua/5.1/torch/File.lua:316: in function 'readObject'
	/torch/install/share/lua/5.1/torch/File.lua:300: in function 'readObject'
	/torch/install/share/lua/5.1/torch/File.lua:347: in function 'load'
	demos/vis-outputs.lua:51: in main chunk
	[C]: in function 'dofile'
	/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00405d70
```
this seems to be hardcoded into the nn4.small2.v1.t7 model

possibly because we don't have cudnn?

**Comment by bamos** [comment]
Hi @pannous - `nn.SpatialCrossMapLRN` is a relatively new class in the `nn` module:
https://github.com/torch/nn/blob/master/SpatialCrossMapLRN.lua

Can you update your nn installation with luarocks and try again?

-Brandon.

**Comment by pannous** [comment]
Thanks! Tried `luarocks install nn` 10 times
Finally got it working
Trick was to call
`/opt/torch$ ./update.sh`
before
`/opt/torch$ ./install.sh`
necessary even after fresh git clone --recursive !!
