### ISSUE TITLE
Improve face detection speed

### ISSUE THREAD

**Issue by bamos** [cmusatyalab/openface#85]
Try:
- OpenCV's LBP cascade with eye detection to remove false negatives [Reference from @jwcrawley in [this HN comment](https://news.ycombinator.com/item?id=10941436)]
- http://libccv.org [Reference from @SyRenity in the gitter chat]
- Others? https://github.com/search?utf8=%E2%9C%93&q=face+detection

**Comment by apprisi** [comment]
Modify "dlib/image_processing/scan_fhog_pyramid.h" with tbb can improve face detection speed, like this file:
https://github.com/TadasBaltrusaitis/CLM-framework/blob/master/lib/3rdParty/dlib/include/dlib/image_processing/scan_fhog_pyramid.h

**Comment by apprisi** [comment]
https://github.com/mc-jesus/face_detect_n_track

**Comment by FedericoRuiz1** [comment]
Brandon, there's a paper that details how to use a CNN to do Face detection ridiculously fast: https://arxiv.org/ftp/arxiv/papers/1508/1508.01292.pdf 

Some guy implemented it here: https://github.com/Bkmz21/FD-Evaluation  
He gets 28fps at 4K, 54fps at 1080p. Its absolutely bonkers fast. 

Unfortunately he didn't open-source his code. However, I think it would be relatively simple to implement that paper based on what I've read. Only problem is that I know basically nothing about training neural networks and machine learning, so this is completely out of my area. 

Maybe you, or somebody else would like to give it a shot? It'd make Face detection, which is currently what takes the bulk of the time super fast.

**Comment by bamos** [comment]
Hi @FedericoRuiz1 - great idea. I've been thinking recently about using or implementing a faster (GPU-accelerated) face detector into OpenFace, but I'm not actively working on it. If anybody wants to look into this, and even implement something as a separate project, I'd be happy to review and give some feedback on the implementation and results.

-Brandon.

**Comment by FedericoRuiz1** [comment]
Brandon, would a GPU-accelerated implementation be possible with Docker?

**Comment by bamos** [comment]
@FedericoRuiz1 - potentially with https://github.com/NVIDIA/nvidia-docker. I was thinking of using a neural network-based technique that could optionally be GPU-accelerated. I'd expect even the CPU performance to be better than what we currently have.

**Comment by Mohamed5amy** [comment]
In this file [align_dlib.py](https://github.com/cmusatyalab/openface/blob/5e0ab14049f29afaaf336003bbaa0aabc0a8baed/openface/align_dlib.py) running `self.detector(rgbImg, 1)` with the second argument = 1, maximizes the image by 2 as mentioned [here](http://dlib.net/face_detection_ex.cpp.html) resulting in 4x more time.
**BUT** this solution is constrained to photos that contain a face with at least 80x80.

**Comment by Pico2x** [comment]
Brandon, I've implemented a solution similar to @jcrawley's one in my project. OpenCV LBP cascade with a min face ize of 96px by 96px, with the neural net neighbours paremeter set at one. This detects faces with very, very few false negatives, and very fast (around 0.02 seconds for 1080p). Problem is there's a lot of false positives. I solved this by applying Open CVs Haar Cascade face detection after the Lbp detection, but only in the areas where faces where detected by the LBP Cascade. For my purposes this is super fast (well under 0.01 seconds with a min face  size of 50*50px) because faces don't usually take up a very big chunk of the frame. It should still be way faster than the current dlib detection even if faces take up sizable chunks of the frame. 

I could implement this here in the weekend if you like this solution.

**Comment by bamos** [comment]
Hi @Pico2x - good idea to further validate the face bounding boxes with the haar cascade. However I still worry the results would be as bad as in [this video](https://www.youtube.com/watch?v=LsK0hzcEyHI). Have you tried using dlib's face detector on the smaller regions instead of OpenCV's haar cascade?

I'd like to have this as part of OpenFace. I'm thinking about pulling OpenFace face detection outside of the `align_dlib` module and into it's own `openface.detection` module to make alternative methods like this easier to choose from. I'd be happy if you want to do this first and then contribute the modified OpenCV technique. Updating the docs, examples, and CI will be a little tricky, especially since we'll need to switch the data format from `dlib.rectangle` to something more generic. You can alternatively add the modifications as a new function to `align_dlib` so it works for now and I'll pull everything into `openface.detection` later.

-Brandon.

**Comment by FedericoRuiz1** [comment]
Brandon, I'm @Pico2x 

The results were nowhere near as bad as that video. False positive detections are quite rare, in fact. But we could use dlib as well.

Right now I'm using the OpenCV rectangles, but we could make a more generic one ourselves. Converting between OpenCV and dlib rectangles is dead simple though.

I'd be happy to get started, but I started my midterms this week, so between that and work my schedule is pretty packed. I could do it in a couple of weeks.

**Comment by bamos** [comment]
Hi @FedericoRuiz1 - ok, sounds good! Let me know how it goes over the next few weeks.

**Comment by qingnianzhi** [comment]
I have two ideas:
1. refer to https://github.com/mc-jesus/face_detect_n_track this code,when detect face in video,detect and track,it can be faster about several times,I tried it.The code is easy to realize.
2. I try to replace dlib face detector with opencv detector,it is faster but landmark is inaccurate,especialy to side face.But dlib have a train API,https://github.com/davisking/dlib/blob/bbeac285d15be3fa93ab19be7c7d3d5a9bd45f7c/examples/train_shape_predictor_ex.cpp
https://github.com/davisking/dlib/blob/7f611ea765ac8db1ad6125bb84faf874d2d6f965/python_examples/train_shape_predictor.py
you can train the shape model with your face detector,mabey NPD face detector is a better choice(I just read the papper,it is faster and more accurate).

**Comment by garex** [comment]
@Mohamed5amy may be extract those var in param? Then when I'm sure regarding my image face size -- I will not use "1" there.

**Comment by Mohamed5amy** [comment]
@garex That would be a nice idea, unfortunately I don't have much time now.
