### ISSUE TITLE
fine tune

### ISSUE THREAD

**Issue by omriba** [cmusatyalab/openface#86]
Hellio,

Is there a way to do fine tuning? I want to start from your model and continue training the network for my task..

Thanks

**Comment by bamos** [comment]
Hi @omriba - please try to post questions to the mailing list in the future since the GitHub issue tracker is for development discussions and bug tracking. We had a short discussion on fine tuning on the mailing list at https://groups.google.com/forum/#!topic/cmu-openface/niJuhF5jvM0

-Brandon.

**Comment by omriba** [comment]
@bamos OK, thanks for the link.
