### ISSUE TITLE
How to increase the box size 

### ISSUE THREAD

**Issue by jianminsun** [cmusatyalab/openface#88]
I am using
bb = align.getLargestFaceBoundingBox(rgbImg)
alignedFace = align.align(args.imgDim, rgbImg, bb)

to get the cropped face. Is there any parameter to control the size of bounding box?

**Comment by bamos** [comment]
Hi @jianminsun - I'm closing this because the issue tracker is for development discussions and bug reports. Happy to help on our mailing list at https://groups.google.com/forum/#!forum/cmu-openface.

-Brandon.
