### ISSUE TITLE
Problems with training a custom model

### ISSUE THREAD

**Issue by aikewoody** [cmusatyalab/openface#89]
I am trying to create my own model and already preprocessed the training and test set with the following commands:

`for N in {1..8}; do ./util/align-dlib.py <path-to-raw-data> align outerEyesAndNose <path-to-aligned-data> --size 96 & done`

`./util/prune-dataset.py <path-to-aligned-data> --numImagesThreshold 3`

`./util/create-train-val-split.py <path-to-aligned-data> --valRatio 0.5`

This went without any problems and produced good images where the nose is always at the center.

When I run training/main.lua it starts training but all of a sudden an error occurs in train.lua, the stack traceback is:

`/home/$user/torch/install/bin/luajit: /home/$user/torch/install/share/lua/5.1/threads/threads.lua:264: 
[thread 1 endcallback] /home/$user/torch/install/share/lua/5.1/torchx/concat.lua:9: attempt to index a nil value
stack traceback:
	/home/$user/torch/install/share/lua/5.1/torchx/concat.lua:9: in function 'concat'
	/home/$user/Desktop/openface/training/train.lua:240: in function </home/$user/Desktop/openface/training/train.lua:164>
	[C]: in function 'xpcall'
	/home/$user/torch/install/share/lua/5.1/threads/threads.lua:173: in function 'dojob'
	/home/$user/torch/install/share/lua/5.1/threads/threads.lua:259: in function 'synchronize'
	/home/$user/Desktop/openface/training/train.lua:130: in function 'train'
	./training/main.lua:44: in main chunk
	[C]: in function 'dofile'
	...$user/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670
stack traceback:
	[C]: in function 'error'
	/home/$user/torch/install/share/lua/5.1/threads/threads.lua:264: in function 'synchronize'
	/home/$user/Desktop/openface/training/train.lua:130: in function 'train'
	./training/main.lua:44: in main chunk
	[C]: in function 'dofile'
	...$user/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670`

I hope someone can tell me why this happens.

**Comment by bamos** [comment]
Hi @aikewoody - what version of the code are you using? I can't match up your line numbers with the code in the master or v0.2.0 tag. Can you try pulling the latest code from master and try again? This may have been fixed by https://github.com/cmusatyalab/openface/commit/8bbfd4da0568225ebdf5f6db9a927de4ba37428e

-Brandon.

**Comment by aikewoody** [comment]
Hi @bamos, pulling the latest version of openface seems to fix the error. Strange that I didn't have a correct version because I used the automated docker build `bamos/openface`.

Thanks for the reply.

**Comment by bamos** [comment]
Thanks, somehow the Docker automated build was disabled from automatically building and hasn't been updated in 19 days. I just manually started a build and re-enabled the option to auto re-build on repo updates.

-Brandon.
