### ISSUE TITLE
model file generation method for face verification

### ISSUE THREAD

**Issue by sharmasaravanan** [cmusatyalab/openface#90]
hi ,i am sharma , i am just trying the #openface for face verification but i cant able to create a individual model file for face verification how to do that??

**Comment by bamos** [comment]
Hi @sharmasaravanan  - I'm closing this issue because the GitHub issue tracker is for development discussions and bug tracking. Also please don't double post messages between our issue tracker and chat room.

-Brandon.

**Comment by sharmasaravanan** [comment]
i am developing the open face verification but i am struggling in generating model file for individual person
