### ISSUE TITLE
Error when running models/get-models.sh

### ISSUE THREAD

**Issue by bgth** [cmusatyalab/openface#92]
Hi Team,

I am getting an error when running models/get-models.sh. It fails for string comparison in the below line. 
 if [ $EXPECTED == $ACTUAL ]; then

Can you please check and change it to below?
 if [ $EXPECTED = $ACTUAL ]; then

Happening in ubuntu 14.04. Sorry if I am wrong.

Thanks.

**Comment by bamos** [comment]
Hi @bgth - I'm surprised changing `==` to `=` fixes an error for you, maybe there's something else going on. `==` is working well on my Ubuntu 14.04 Docker container and http://tldp.org/LDP/abs/html/comparison-ops.html describes `==` as being a synonym for `=`.

Has anybody else experienced issues with this comparison?

-Brandon.

**Comment by jaharkes** [comment]
Check the man page for test, it is supposed to be a single =. The fact it works with bash is probably because it is a common mistake for C programmers.

**Comment by bamos** [comment]
Thanks for the reference @jaharkes! I just updated the script to use `=`.

-Brandon.
