### ISSUE TITLE
Training validation script error

### ISSUE THREAD

**Issue by shimen** [cmusatyalab/openface#99]
Hi,
I'm trying to train a nn model with the use of validation.
I had followed the instruction and changed the '-testEpochSize' parameter in main.lua training script. The training epoch works fine. A model is saved and I had checked that it's loading and working fine.

I have 2 issues with the validation
1) It seems that there is a missing parameter '-batchSize' at main.lua script.
Without adding this parameter to main.lua I get this error:

/usr/local/bin/luajit: /usr/local/share/lua/5.1/threads/threads.lua:264:
[thread 1 endcallback] ...a/OpenFace/py_openFace_dev_trainNN/src/training/test.lua:89: bad argument #2 to 'sub' (number expected, got nil)
stack traceback:
        [C]: in function 'sub'
        ...a/OpenFace/py_openFace_dev_trainNN/src/training/test.lua:89: in function <...a/OpenFace/py_openFace_dev_trainNN/src/training/test.lua:79>
        [C]: in function 'xpcall'
        /usr/local/share/lua/5.1/threads/threads.lua:173: in function 'dojob'
        /usr/local/share/lua/5.1/threads/threads.lua:259: in function 'synchronize'
        ...a/OpenFace/py_openFace_dev_trainNN/src/training/test.lua:54: in function 'test'
        training/main_with_test.lua:46: in main chunk
        [C]: in function 'dofile'
        /usr/local/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x00405800
stack traceback:
        [C]: in function 'error'
        /usr/local/share/lua/5.1/threads/threads.lua:264: in function 'synchronize'
        ...a/OpenFace/py_openFace_dev_trainNN/src/training/test.lua:54: in function 'test'
        training/main_with_test.lua:46: in main chunk
        [C]: in function 'dofile'
        /usr/local/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x00405800

This is the error line at the test.lua script:
  local embeddings = model:forward({
         inputs:sub(1,opt.batchSize),
         inputs:sub(opt.batchSize+1, 2*opt.batchSize),
         inputs:sub(2*opt.batchSize+1, 3*opt.batchSize)})

As you can see there should be a 'batchSize' parmeter, while it is missing.
I manually added it.

2) After adding the 'batchSize' parmeter, I get a different error:

 /usr/local/bin/luajit: /usr/local/share/lua/5.1/threads/threads.lua:264:
[thread 1 endcallback] /usr/local/share/lua/5.1/nn/SpatialConvolutionMM.lua:47: attempt to call method 'isContiguous' (a nil value)
stack traceback:
        /usr/local/share/lua/5.1/nn/SpatialConvolutionMM.lua:47: in function 'makeContiguous'
        /usr/local/share/lua/5.1/nn/SpatialConvolutionMM.lua:71: in function 'updateOutput'
        /usr/local/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
        ...a/OpenFace/py_openFace_dev_trainNN/src/training/test.lua:94: in function <...a/OpenFace/py_openFace_dev_trainNN/src/training/test.lua:79>
        [C]: in function 'xpcall'
        /usr/local/share/lua/5.1/threads/threads.lua:173: in function 'dojob'
        /usr/local/share/lua/5.1/threads/threads.lua:259: in function 'synchronize'
        ...a/OpenFace/py_openFace_dev_trainNN/src/training/test.lua:54: in function 'test'
        training/main_with_test.lua:46: in main chunk
        [C]: in function 'dofile'
        /usr/local/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x00405800
stack traceback:
        [C]: in function 'error'
        /usr/local/share/lua/5.1/threads/threads.lua:264: in function 'synchronize'
        ...a/OpenFace/py_openFace_dev_trainNN/src/training/test.lua:54: in function 'test'
        training/main_with_test.lua:46: in main chunk
        [C]: in function 'dofile'
        /usr/local/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x00405800

The error line at the test.lua script is the same:
  local embeddings = model:forward({
         inputs:sub(1,opt.batchSize),
         inputs:sub(opt.batchSize+1, 2*opt.batchSize),
         inputs:sub(2*opt.batchSize+1, 3*opt.batchSize)})

It seems to be that the collection of tensors is the problem:
{inputs:sub(1,opt.batchSize),inputs:sub(opt.batchSize+1, 2*opt.batchSize),
         inputs:sub(2*opt.batchSize+1, 3*opt.batchSize)}

When I just try:
local embeddings = model:forward(inputs)

it works fine.

What seems to be the problem?

I use this configuration:
  cmd:option('-cuda', false, 'Use cuda.')
  cmd:option('-cudnn', false, 'Convert the model to cudnn.')
  cmd:option('-testEpochSize', 1, 'Number of batches to test per epoch')

**Comment by bamos** [comment]
Hi @shimen - sorry, I now just manually use the LFW evaluation for testing and the file named `test.lua` is outdated. I've moved these to `training/attic` to make this more clear. I plan to add an automatic LFW validation soon, follow issue #100 for this.
